import test from 'node:test';import assert from 'node:assert/strict';
import {loadGameUI} from './helpers/game-ui-harness.mjs';
import {buildArmoryRecords} from '../site/dist/armory-catalog-data.mjs';
import {cardIdentity,STANDARD_EDITION} from '../site/dist/armory-presentation.mjs';
import {ARMORY_PLANS,discoveryPlans,budgetPicks} from '../site/dist/armory-discovery.mjs';
import {createArmoryCatalogUI} from '../site/dist/armory-catalog.mjs';
import {createArmorySnapshot} from '../site/dist/armory-catalog-model.mjs';
import {SKILLS,PlayerProfile} from '../site/dist/engine/progression.mjs';import {COMPANIONS} from '../site/dist/engine/recruitment.mjs';
const records=buildArmoryRecords(SKILLS,COMPANIONS,{});
const search=(ui,value)=>{const el=ui.get('shopSearch');el.value=value;el.focus();ui.dispatch(el,'input');ui.dispatch(ui.get('shopSearchForm'),'submit');};
const change=(ui,id,value)=>{const el=ui.get(id);el.value=value;el.focus();ui.dispatch(el,'change');};
async function market(t,gold=20000){const ui=await loadGameUI(t,{search:'?mode=test'});ui.click('introTesting');ui.click('testVictory');ui.frames(105);ui.battle.profile.gold=gold;ui.click('endingShop');return ui;}

test('Discover contains actionable real battle-plan collections with transparent individual totals and tradeoffs',async t=>{
 const ui=await market(t);assert.equal(ui.get('shopDiscover').querySelectorAll('.market-plan-card').length,4);assert.match(ui.get('shopDiscover').textContent,/No limited-edition cards/);const plan=ARMORY_PLANS[0],price=plan.ids.reduce((sum,id)=>sum+SKILLS[id].price,0);ui.click('plan-open-'+plan.id);assert.equal(ui.visible('shopPlanView'),true);assert.match(ui.get('shopPlanView').textContent,/How these cards work together/);assert.match(ui.get('shopPlanView').textContent,/Know the tradeoff/);assert.match(ui.get('shopPlanView').textContent,/No bundle discount/);assert.match(ui.get('shopPlanView').textContent,new RegExp(price.toLocaleString()));assert.equal(ui.get('shopPlanView').querySelectorAll('.market-mini-card').length,3);ui.click('shopPlanAdd');ui.click('shopPlanAdd');assert.equal(ui.get('shopCartCount').textContent,'3');assert.equal(ui.battle.profile.gold,20000);ui.click('shopPlanCart');assert.match(ui.get('shopCartView').textContent,/All or nothing/);assert.equal(ui.get('shopCartView').querySelectorAll('.market-cart-line').length,3);
});
test('plan detail, cart and Escape return to their actual origin without losing scroll',async t=>{
 const ui=await market(t);ui.get('shopDiscover').scrollTop=420;ui.click('plan-open-frost-and-fire');ui.get('shopPlanView').scrollTop=170;ui.get('plan-inspect-iceArrow').focus();ui.click('plan-inspect-iceArrow');assert.equal(ui.visible('shopDetailDrawer'),true);ui.key('keydown','Escape');assert.equal(ui.visible('shopPlanView'),true);assert.equal(ui.document.activeElement.id,'plan-inspect-iceArrow');assert.equal(ui.get('shopPlanView').scrollTop,170);ui.click('shopPlanCart');ui.key('keydown','Escape');assert.equal(ui.visible('shopPlanView'),true);ui.key('keydown','Escape');assert.equal(ui.visible('shopDiscover'),true);assert.equal(ui.get('shopDiscover').scrollTop,420);assert.equal(ui.document.activeElement.id,'plan-open-frost-and-fire');
});
test('budget picks retain editable controls and never imply the displayed group fits together',async t=>{
 const ui=await market(t,2000);const input=ui.get('shopBudget');input.focus();input.value='1001';ui.key('keydown','1',{target:input});assert.equal(ui.get('shopBudget'),input);assert.equal(ui.battle.input.right,false);ui.dispatch(ui.get('shopBudgetForm'),'submit');assert.equal(ui.document.activeElement.id,'shopBudget');assert.match(ui.get('shopDiscover').textContent,/Each pick fits your limit individually/);const picks=budgetPicks(records,createArmorySnapshot(ui.battle.profile),1001);assert.ok(picks.length>0);assert.ok(picks.every(item=>item.price+(item.kind==='skill'?1:0)<=1001));ui.get('shopBudget').value='0';ui.dispatch(ui.get('shopBudgetForm'),'submit');assert.match(ui.get('shopDiscover').textContent,/No unowned cards fit/);assert.equal(ui.battle.profile.gold,2000);
});
test('cart batch acquisition is atomic, repeat-safe, creates reserve cards and keeps a receipt through equip',async t=>{
 const ui=await market(t,5001),p=ui.battle.profile,basic=p.skills[0];ui.click('shopCatalogTab');ui.click('cart-fireArrow');ui.click('cart-iceArrow');const total=SKILLS.fireArrow.price+SKILLS.iceArrow.price;ui.click('shopCartOpen');const checkout=ui.get('shopCheckout');checkout.click();checkout.click();assert.equal(p.gold,5001-total);assert.equal(p.skills.length,3);assert.equal(p.skills.find(s=>s.id==='fireArrow').binding,-1);assert.equal(p.skills.find(s=>s.id==='iceArrow').binding,-1);assert.equal(p.skills[0],basic);assert.equal(basic.binding,0);assert.equal(ui.get('shopCartCount').textContent,'0');assert.equal(ui.document.activeElement.id,'receipt-equip-fireArrow');ui.click('receipt-equip-fireArrow');assert.match(ui.get('shopDetails').textContent,/Place in your loadout/);ui.click('shop-slot-2');ui.click('shopEquipConfirm');assert.equal(p.skills.find(s=>s.id==='fireArrow').binding,2);assert.equal(ui.battle.hotbar.bars[0][2]?.id,'fireArrow');ui.key('keydown','Escape');assert.equal(ui.visible('shopCartView'),true);assert.ok(ui.get('receipt-equip-iceArrow'));ui.click('shopReceiptDismiss');assert.equal(ui.get('shopCartView').querySelectorAll('.market-receipt').length,0);
});
test('a stale balance blocks the entire checkout and leaves every cart card reviewable',async t=>{
 const ui=await market(t,5000);ui.click('shopCatalogTab');ui.click('cart-fireArrow');ui.click('cart-iceArrow');ui.click('shopCartOpen');const checkout=ui.get('shopCheckout'),p=ui.battle.profile;p.gold=1000;checkout.click();assert.equal(p.gold,1000);assert.equal(p.skills.length,1);assert.equal(ui.get('shopCartCount').textContent,'2');assert.match(ui.get('shopCartMessage').textContent,/Need/);assert.equal(ui.get('shopCheckout').disabled,true);ui.click('cart-remove-iceArrow');assert.equal(ui.get('shopCheckout').disabled,true);p.gold=1001;ui.click('shopCartBack');ui.click('shopCartOpen');assert.equal(ui.get('shopCheckout').disabled,false);ui.click('shopCheckout');assert.equal(p.gold,1);assert.equal(p.owned.has('fireArrow'),true);
});
test('checkout rechecks purchase window even after review and does not buy a partial cart',async t=>{
 const ui=await market(t),p=ui.battle.profile;ui.click('shopCatalogTab');ui.click('cart-fireArrow');ui.click('cart-iceArrow');ui.click('shopCartOpen');ui.battle.summary=null;ui.click('shopCheckout');assert.equal(p.gold,20000);assert.equal(p.skills.length,1);assert.equal(ui.get('shopCartCount').textContent,'2');assert.match(ui.get('shopCartMessage').textContent,/Finish this battle to purchase/);
});
test('a card bought individually leaves the cart and preserves Available-to-equip continuation',async t=>{
 const ui=await market(t,1001);ui.click('shopCatalogTab');ui.click('cart-fireArrow');ui.click('save-fireArrow');change(ui,'shopOwnership','available');ui.click('buy-fireArrow');assert.equal(ui.get('shopCartCount').textContent,'0');assert.equal(ui.get('shopWishlistCount').textContent,'0');assert.equal(ui.visible('shopDetailDrawer'),true);assert.match(ui.get('shopDetails').textContent,/Place in your loadout/);ui.click('shopCloseDetails');assert.equal(ui.get('shopOwnership').value,'available');
});
test('wishlist filters are paged catalog views and preserve a separate browse query',async t=>{
 const ui=await market(t);ui.click('shopCatalogTab');ui.click('save-fireArrow');ui.click('save-iceArrow');search(ui,'fire');change(ui,'shopSort','price-desc');ui.click('shopWishlistTab');assert.equal(ui.get('shopGrid').querySelectorAll('article').length,2);assert.equal(ui.get('shopSearch').value,'');ui.click('save-iceArrow');assert.equal(ui.get('shopGrid').querySelectorAll('article').length,1);assert.equal(ui.document.activeElement.id,'inspect-fireArrow');ui.click('shopCatalogTab');assert.equal(ui.get('shopSearch').value,'fire');assert.equal(ui.get('shopSort').value,'price-desc');ui.click('shopWishlistTab');assert.ok(ui.get('inspect-fireArrow'));
});
test('cart back restores the selected drawer and browse state, and clear never spends gold',async t=>{
 const ui=await market(t);ui.click('shopCatalogTab');search(ui,'ice');change(ui,'shopSort','name');ui.click('inspect-iceArrow');ui.click('shopCartSelected');ui.get('shopCartSelected').focus();ui.click('shopCartOpen');ui.click('shopCartClear');assert.equal(ui.battle.profile.gold,20000);ui.click('shopCartBack');assert.equal(ui.get('shopSearch').value,'ice');assert.equal(ui.get('shopSort').value,'name');assert.equal(ui.visible('shopDetailDrawer'),true);assert.equal(ui.document.activeElement.id,'shopCartSelected');assert.match(ui.get('shopDetails').textContent,/Ice Arrow/);
});
test('cart and wishlist do not cross profile identity or silently enter an exported campaign',async t=>{
 const ui=await market(t);ui.click('shopCatalogTab');ui.click('cart-fireArrow');ui.click('save-iceArrow');const p=ui.battle.profile;assert.ok(!Object.hasOwn(p,'cart'));assert.ok(!Object.hasOwn(p,'wishlist'));ui.click('shopLoadout');ui.get('skillsPanel').querySelector('[data-menu-route="profiles"]').click();ui.get('newProfileName').value='Different campaign';ui.click('createProfile');ui.click('introTesting');ui.click('testVictory');ui.frames(105);ui.click('endingShop');assert.equal(ui.get('shopCartCount').textContent,'0');assert.equal(ui.get('shopWishlistCount').textContent,'0');
});
test('card identity is semantic and trusted across the real collection without invented rarity',()=>{
 assert.equal(records.length,26);assert.equal(new Set(records.map(item=>cardIdentity(item).tone)).size,8);assert.equal(cardIdentity(records.find(item=>item.id==='iceDragon')).label,'Airborne · Ranged');assert.equal(cardIdentity(records.find(item=>item.id==='priest')).facts[1].value,'30 gold');for(const item of records){assert.equal(item.edition,STANDARD_EDITION);assert.equal(item.edition.limited,false);assert.ok(!Object.hasOwn(item,'rarity'));assert.ok(!Object.hasOwn(item,'expiresAt'));}const plans=discoveryPlans(records,createArmorySnapshot(new PlayerProfile()));assert.equal(plans.length,4);for(const plan of plans)assert.equal(plan.total,plan.missing.reduce((sum,item)=>sum+item.price,0));
});
test('1,000 synthetic cards keep wishlist/catalog/cart page counts and DOM bounded',async t=>{
 const ui=await loadGameUI(t),root=ui.document.createElement('div'),p=new PlayerProfile();p.gold=100000;const fixture=Array.from({length:1000},(_,i)=>({id:'scale-'+i,name:'Test-only card '+i,kind:'skill',department:'bow',role:'bow',category:'arrows',price:1,reloadSeconds:2,traits:[]}));const view=createArmoryCatalogUI({root,records:fixture,getSnapshot:()=>createArmorySnapshot(p),onPurchase:()=>false,onArrange:()=>{}});view.refresh();root.querySelector('#shopCatalogTab').click();for(let page=0;page<5;page++){for(const item of view.model.query(createArmorySnapshot(p)).items){root.querySelector('#save-'+item.id).click();root.querySelector('#cart-'+item.id).click();}root.querySelector('#shopNext').click();}assert.equal(view.state.wishlistIds.length,60);assert.equal(view.state.cartIds.length,50);root.querySelector('#shopWishlistTab').click();assert.equal(view.diagnostics.resultCount,60);assert.equal(root.querySelector('#shopGrid').querySelectorAll('article').length,12);root.querySelector('#shopCartOpen').click();assert.equal(root.querySelector('#shopCartView').querySelectorAll('.market-cart-line').length,12);root.querySelector('#shopCartNext').click();assert.equal(root.querySelector('#shopCartView').querySelectorAll('.market-cart-line').length,12);assert.ok(root.querySelectorAll('button,input,select,option,span,div,section,p,article,aside,nav,form,label,h3,h4,ul,li,table,thead,tbody,tr,th,td,small,strong,b').length<950);view.dispose();
});

test('a spending limit covers card prices while actual gold independently covers the source boundary',()=>{
 const snapshot=createArmorySnapshot(new PlayerProfile());snapshot.gold=20000;assert.ok(budgetPicks(records,snapshot,1000).some(item=>item.id==='fireArrow'));snapshot.gold=1000;assert.ok(!budgetPicks(records,snapshot,1000).some(item=>item.id==='fireArrow'));snapshot.gold=1001;assert.ok(budgetPicks(records,snapshot,1000).some(item=>item.id==='fireArrow'));
});
test('stale checkout handlers cannot charge a newly active campaign even before refresh',async t=>{
 const ui=await loadGameUI(t),root=ui.document.createElement('div'),first=new PlayerProfile('one'),second=new PlayerProfile('two');first.gold=second.gold=10000;let current=first,calls=0;const view=createArmoryCatalogUI({root,records,getSnapshot:()=>createArmorySnapshot(current),getSessionKey:()=>current,onPurchase:()=>false,onCheckout:()=>{calls++;return {ok:false};},onArrange:()=>{}});view.refresh();root.querySelector('#shopCatalogTab').click();root.querySelector('#cart-fireArrow').click();root.querySelector('#shopCartOpen').click();const stale=root.querySelector('#shopCheckout');current=second;stale.click();assert.equal(calls,0);assert.equal(second.gold,10000);assert.equal(view.state.cartIds.length,0);current=first;view.refresh();root.querySelector('#shopCatalogTab').click();root.querySelector('#cart-iceArrow').click();root.querySelector('#shopCartOpen').click();stale.click();assert.equal(calls,0);assert.equal(view.state.cartIds.length,1);view.dispose();
});

test('the owned starting arrow can be saved and found in the wishlist without being sold',async t=>{
 const ui=await market(t);ui.click('shopCollectionTab');ui.click('save-arrow');ui.click('shopWishlistTab');assert.equal(ui.get('shopWishlistCount').textContent,'1');assert.equal(ui.get('shopGrid').querySelectorAll('article').length,1);assert.ok(ui.get('inspect-arrow'));assert.ok(!ui.document.querySelector('#cart-arrow'));ui.click('inspect-arrow');assert.match(ui.get('shopDetails').textContent,/Starting ability/);
});
test('elemental collection discloses cancellation rather than inventing a stacking bonus',()=>{const plan=ARMORY_PLANS.find(plan=>plan.id==='frost-and-fire');assert.match(plan.tradeoff,/fire and ice.*cancel/);assert.match(plan.tradeoff,/no combo bonus/);});

test('cart inspect and back restore the exact Wishlist or Collection query context',async t=>{
 const ui=await market(t);ui.click('shopCatalogTab');ui.click('save-fireArrow');ui.click('cart-fireArrow');ui.click('shopWishlistTab');ui.click('shopCartOpen');ui.click('cart-inspect-fireArrow');ui.click('shopCloseDetails');ui.click('shopCartBack');assert.equal(ui.get('shopWishlistTab').getAttribute('aria-pressed'),'true');assert.equal(ui.get('shopContext').textContent,'YOUR WISHLIST');assert.equal(ui.get('shopGrid').querySelectorAll('article').length,1);ui.click('shopCollectionTab');search(ui,'basic');ui.click('shopCartOpen');ui.click('cart-inspect-fireArrow');ui.key('keydown','Escape');ui.key('keydown','Escape');assert.equal(ui.get('shopContext').textContent,'YOUR COLLECTION');assert.equal(ui.get('shopSearch').value,'basic');assert.equal(ui.get('shopGrid').querySelectorAll('article').length,1);
});
test('compare inspect and back preserve Wishlist context as well as its selected card',async t=>{
 const ui=await market(t);ui.click('shopCatalogTab');ui.click('save-fireArrow');ui.click('save-iceArrow');ui.click('compare-fireArrow');ui.click('compare-iceArrow');ui.click('shopWishlistTab');ui.click('shopCompareOpen');ui.click('comparison-inspect-fireArrow');ui.key('keydown','Escape');assert.equal(ui.visible('shopCompareView'),true);ui.click('shopCompareBack');assert.equal(ui.get('shopContext').textContent,'YOUR WISHLIST');assert.equal(ui.get('shopGrid').querySelectorAll('article').length,2);
});

test('global lobby checkout funds owned cards before Start, then blocks purchasing during a preserved live battle',async t=>{
 const ui=await loadGameUI(t,{search:'?mode=test'});ui.click('introTesting');ui.click('testGoldLarge');ui.click('closeTesting');
 const b=ui.battle,p=b.profile,gold=p.gold;ui.click('introArmory');ui.click('shopCatalogTab');ui.click('cart-fireArrow');ui.click('cart-iceArrow');ui.click('shopCartOpen');assert.equal(ui.get('shopCheckout').disabled,false);ui.click('shopCheckout');
 assert.equal(p.gold,gold-SKILLS.fireArrow.price-SKILLS.iceArrow.price);assert.equal(b.tick,0);assert.equal(b.summary,null);assert.ok(p.owned.has('fireArrow')&&p.owned.has('iceArrow'));
 ui.click('receipt-equip-fireArrow');ui.click('shop-slot-2');ui.click('shopEquipConfirm');assert.equal(b.hotbar.bars[0][2]?.id,'fireArrow');ui.click('closeShop');ui.click('start');ui.frames();ui.click('battlePause');ui.click('pauseLobby');ui.click('introArmory');ui.click('shopCatalogTab');ui.click('cart-pierceArrow');ui.click('shopCartOpen');const before=p.gold;
 assert.equal(ui.get('shopCheckout').disabled,true);assert.match(ui.get('shopCartMessage').textContent,/Finish this battle/);ui.click('shopCheckout');assert.equal(p.gold,before);assert.equal(p.owned.has('pierceArrow'),false);
});
