import test from 'node:test';import assert from 'node:assert/strict';
import {loadGameUI} from './helpers/game-ui-harness.mjs';
import {ArmoryCatalog,createArmorySnapshot} from '../site/dist/armory-catalog-model.mjs';
import {buildArmoryRecords,ARMORY_DEPARTMENTS} from '../site/dist/armory-catalog-data.mjs';
import {SKILLS,PlayerProfile} from '../site/dist/engine/progression.mjs';import {COMPANIONS} from '../site/dist/engine/recruitment.mjs';
const change=(ui,id,value)=>{const el=ui.get(id);el.value=value;el.focus();ui.dispatch(el,'change');};
const search=(ui,value)=>{const el=ui.get('shopSearch');el.value=value;el.focus();ui.dispatch(el,'input');ui.dispatch(ui.get('shopSearchForm'),'submit');};
const tab=(ui,value)=>ui.get('shopDetailDrawer').querySelector(`[data-detail-tab="${value}"]`).click();
const department=(ui,id)=>change(ui,'shopDepartmentCompact',id);
async function armory(t,{gold=20000,unlock=false}={}){const ui=await loadGameUI(t,{search:'?mode=test'});ui.click('introTesting');if(unlock)ui.click('testUnlock');ui.click('testVictory');ui.frames(105);ui.battle.profile.gold=gold;ui.click('endingShop');return ui;}

// Castle slice adds free, already-owned Classic plus Highwatch as the only new purchasable card.
test('Discover exposes real departments and useful pathways, then remembers the returning catalog',async t=>{
 const ui=await armory(t);assert.equal(ui.visible('shopDiscover'),true);assert.equal(ui.visible('shopBrowseView'),false);assert.equal(ui.get('shopDiscover').querySelectorAll('[data-discover-department]').length,4);assert.match(ui.get('shopDiscover').textContent,/12 cards/);assert.match(ui.get('shopDiscover').textContent,/1 cards/);
 ui.get('shopDiscover').querySelector('[data-discover-department="army"]').click();assert.equal(ui.visible('shopBrowseView'),true);assert.equal(ui.get('shopDepartmentCompact').value,'army');assert.equal(ui.get('shopGrid').querySelectorAll('article').length,12);search(ui,'dragon');change(ui,'shopSort','name');ui.click('closeShop');ui.click('endingShop');assert.equal(ui.visible('shopDiscover'),false);assert.equal(ui.get('shopSearch').value,'dragon');assert.equal(ui.get('shopSort').value,'name');
 ui.click('shopDiscoverTab');ui.click('shopResumeBrowse');assert.equal(ui.get('shopSearch').value,'dragon');assert.equal(ui.get('shopDepartmentCompact').value,'army');
});
test('departments change relevant facets; empty results and reset remain within the chosen department',async t=>{
 const ui=await armory(t);ui.click('shopCatalogTab');department(ui,'army');assert.equal(ui.visible('shopRoleField'),true);assert.equal(ui.visible('shopDeliveryField'),false);change(ui,'shopRole','support');assert.equal(ui.get('shopGrid').querySelectorAll('article').length,1);assert.ok(ui.get('inspect-priest'));search(ui,'zzzz');assert.equal(ui.get('shopGrid').querySelectorAll('article').length,0);ui.click('shopEmptyReset');assert.equal(ui.get('shopDepartmentCompact').value,'army');assert.equal(ui.get('shopRole').value,'all');assert.equal(ui.get('shopGrid').querySelectorAll('article').length,12);
 department(ui,'bow');assert.equal(ui.visible('shopRoleField'),false);assert.equal(ui.visible('shopDeliveryField'),true);change(ui,'shopCategoryCompact','waves');assert.equal(ui.get('shopGrid').querySelectorAll('article').length,4);department(ui,'companions');assert.equal(ui.visible('shopTraitField'),false);assert.equal(ui.get('shopGrid').querySelectorAll('article').length,1);
});
test('Collection includes the starting arrow without selling it and preserves independent browse state',async t=>{
 const ui=await armory(t);ui.click('shopCatalogTab');assert.ok(!ui.document.querySelector('#buy-arrow'));search(ui,'ice');change(ui,'shopSort','price-desc');ui.click('shopCollectionTab');assert.equal(ui.get('shopGrid').querySelectorAll('article').length,2);assert.ok(ui.get('inspect-classic'));assert.ok(ui.get('inspect-arrow'));ui.click('inspect-arrow');assert.match(ui.get('shopDetails').textContent,/Starting ability/);tab(ui,'stats');assert.match(ui.get('shopDetails').textContent,/Base direct hit/);ui.click('shopCloseDetails');ui.click('shopCatalogTab');assert.equal(ui.get('shopSearch').value,'ice');assert.equal(ui.get('shopSort').value,'price-desc');assert.ok(!ui.document.querySelector('#buy-arrow'));
});
test('comparison is capped at two, keeps pins through filtering, compares live ranks and restores browse state',async t=>{
 const ui=await armory(t);ui.click('shopCatalogTab');ui.click('compare-fireArrow');ui.click('compare-iceArrow');ui.click('compare-pierceArrow');assert.match(ui.get('shopStatus').textContent,/Two cards/);assert.equal(ui.get('shopCompareCount').textContent,'2/2');search(ui,'fire');change(ui,'shopSort','name');const before=ui.get('shopResultCount').textContent;ui.click('shopCompareOpen');assert.equal(ui.visible('shopCompareView'),true);assert.match(ui.get('shopCompareView').textContent,/Fire Arrow/);assert.match(ui.get('shopCompareView').textContent,/Ice Arrow/);assert.match(ui.get('shopCompareView').textContent,/Base direct hit/);const gold=ui.battle.profile.gold;change(ui,'shopCompareRank','10');assert.equal(ui.document.activeElement,ui.get('shopCompareRank'));assert.match(ui.get('shopCompareView').textContent,/150 damage/);assert.equal(ui.battle.profile.gold,gold);ui.click('shopCompareBack');assert.equal(ui.get('shopSearch').value,'fire');assert.equal(ui.get('shopSort').value,'name');assert.equal(ui.get('shopResultCount').textContent,before);ui.click('shopCompareOpen');ui.click('shopCatalogTab');assert.equal(ui.get('shopSearch').value,'fire');
});
test('buying under Available opens inline equipment, previews a safe swap and applies only once',async t=>{
 const ui=await armory(t,{gold:1001});ui.click('shopCatalogTab');change(ui,'shopOwnership','available');ui.click('buy-fireArrow');const p=ui.battle.profile,fire=p.skills.find(skill=>skill.id==='fireArrow'),arrow=p.skills.find(skill=>skill.id==='arrow');assert.equal(p.gold,1);assert.equal(ui.visible('shopDetailDrawer'),true);assert.match(ui.get('shopDetails').textContent,/Place in your loadout/);assert.equal(fire.binding,1);ui.click('shop-slot-0');assert.match(ui.get('shopEquipPreview').textContent,/swap places/);assert.equal(fire.binding,1);const confirm=ui.get('shopEquipConfirm');confirm.click();confirm.click();assert.equal(fire.binding,0);assert.equal(arrow.binding,1);assert.equal(p.gold,1);assert.equal(new Set(p.skills.filter(s=>s.binding>=0).map(s=>s.binding)).size,2);assert.match(ui.get('shopStatus').textContent,/Fire Arrow/);ui.click('shopCloseDetails');assert.equal(ui.get('shopOwnership').value,'available');assert.equal(ui.get('shopGrid').querySelectorAll('article').length,0);
});
test('reserve replacement, cancel, full editor round-trip and stale placement guard preserve bindings',async t=>{
 const ui=await armory(t,{unlock:true});ui.click('shopCollectionTab');search(ui,'fire arrow');ui.click('buy-fireArrow');const p=ui.battle.profile,fire=p.skills.find(s=>s.id==='fireArrow'),arrow=p.skills.find(s=>s.id==='arrow'),start=fire.binding;
 ui.click('shop-slot-0');ui.click('shopEquipCancel');assert.equal(fire.binding,start);ui.click('shopReserve');assert.match(ui.get('shopEquipPreview').textContent,/move to reserve/);assert.equal(fire.binding,start);ui.click('shopEquipConfirm');assert.equal(fire.binding,-1);ui.click('shop-slot-0');assert.match(ui.get('shopEquipPreview').textContent,/Basic Arrow will move to reserve/);ui.click('shopEquipConfirm');assert.equal(fire.binding,0);assert.equal(arrow.binding,-1);
 ui.click('shop-slot-2');const before=fire.binding;p.skills.find(s=>s.binding===2).binding=29;ui.click('shopEquipConfirm');assert.equal(fire.binding,before);assert.match(ui.get('shopStatus').textContent,/loadout changed/);
 ui.click('shopOpenFullLoadout');assert.equal(ui.visible('skillsPanel'),true);assert.equal(ui.get('closeSkills').textContent,'Back to deck');ui.click('closeSkills');assert.equal(ui.visible('shopPanel'),true);assert.equal(ui.visible('shopDetailDrawer'),true);assert.equal(ui.get('shopSearch').value,'fire arrow');
});
test('rank preview is explicit and cannot spend gold, rank a skill or reset cooldown',async t=>{
 const ui=await armory(t,{unlock:true});ui.click('shopCollectionTab');search(ui,'fire arrow');ui.click('inspect-fireArrow');tab(ui,'stats');const p=ui.battle.profile,s=p.skills.find(x=>x.id==='fireArrow'),before={rank:s.rank,xp:s.xp,cooldown:s.cooldown,gold:p.gold};change(ui,'shopPreviewRank','10');assert.equal(ui.document.activeElement,ui.get('shopPreviewRank'));assert.match(ui.get('shopDetails').textContent,/Preview only/);assert.match(ui.get('shopDetails').textContent,/150 damage/);assert.deepEqual({rank:s.rank,xp:s.xp,cooldown:s.cooldown,gold:p.gold},before);
 ui.click('shopCloseDetails');search(ui,'thunder');ui.click('inspect-thunderArrow');tab(ui,'stats');change(ui,'shopPreviewRank','10');assert.match(ui.get('shopDetails').textContent,/does not pass skill rank/);assert.match(ui.get('shopDetails').textContent,/70 damage/);
});
test('army automation and companion assignment use their real separate state',async t=>{
 const ui=await armory(t,{unlock:true});ui.click('shopCollectionTab');search(ui,'priest');ui.click('buy-priest');const priest=ui.battle.profile.skills.find(s=>s.id==='priest');ui.get('shopAutoSummon').checked=true;ui.dispatch(ui.get('shopAutoSummon'),'change');assert.equal(priest.autocast,true);ui.get('shopAutoSummon').checked=false;ui.dispatch(ui.get('shopAutoSummon'),'change');assert.equal(priest.autocast,false);
 ui.click('shopCloseDetails');search(ui,'gorath');ui.click('buy-gorath');assert.ok(ui.get('shopCompanionEquip'));assert.match(ui.get('shopDetails').textContent,/150 gold each time you summon/);assert.ok(!ui.document.querySelector('#shop-slot-0'));ui.click('shopCompanionEquip');assert.equal(ui.battle.profile.companionId,null);ui.click('shopCompanionEquip');assert.equal(ui.battle.profile.companionId,'gorath');assert.ok(!ui.battle.profile.skills.some(s=>s.id==='gorath'));tab(ui,'stats');assert.match(ui.get('shopDetails').textContent,/Hero rank 1/);change(ui,'shopPreviewRank','5');assert.match(ui.get('shopDetails').textContent,/Hero rank 5/);assert.equal(ui.battle.profile.rank,1);
});
test('Escape unwinds details and comparison before leaving; repeated open/back never grows the DOM',async t=>{
 const ui=await armory(t);ui.click('shopCatalogTab');search(ui,'fire');const sizes=[];for(let i=0;i<25;i++){ui.click('inspect-fireArrow');assert.equal(ui.visible('shopDetailDrawer'),true);ui.key('keydown','Escape');assert.equal(ui.visible('shopDetailDrawer'),false);assert.equal(ui.visible('shopPanel'),true);assert.equal(ui.get('shopSearch').value,'fire');sizes.push(ui.get('armoryCatalogHost').querySelectorAll('div,section,aside,article,button,input,select,span,p').length);}assert.equal(new Set(sizes).size,1);ui.click('compare-fireArrow');ui.click('compare-fireWave');ui.click('shopCompareOpen');ui.key('keydown','Escape');assert.equal(ui.visible('shopCompareView'),false);assert.equal(ui.visible('shopPanel'),true);ui.key('keydown','Escape');assert.equal(ui.visible('shopPanel'),false);
});
test('department identity and collection filters scale independently of a small hardcoded type list',()=>{
 const entries=buildArmoryRecords(SKILLS,COMPANIONS,{}),p=new PlayerProfile(),snapshot=createArmorySnapshot(p);const catalog=new ArmoryCatalog(entries);catalog.setView({collection:true});assert.deepEqual(catalog.query(snapshot).items.map(x=>x.id),['arrow','classic']);catalog.setView({status:'reserve'});assert.equal(catalog.query(snapshot).total,0);p.skills[0].binding=-1;assert.equal(catalog.query(createArmorySnapshot(p)).total,1);
 const future=new ArmoryCatalog([{id:'fixture-future',kind:'skill',department:'private-fixture-type',category:'arrows',name:'Fixture',description:'Test-only extensibility',price:1,traits:[]}]);future.setView({department:'private-fixture-type'});assert.equal(future.query(snapshot).total,1);assert.equal(ARMORY_DEPARTMENTS.length,4);assert.ok(!entries.some(x=>x.id==='fixture-future'));
});

test('explicit Discover pathways discard stale query/ownership while Continue preserves them',async t=>{
 const ui=await armory(t);ui.click('shopCatalogTab');search(ui,'fire');change(ui,'shopOwnership','owned');ui.click('shopDiscoverTab');ui.get('shopDiscover').querySelector('[data-discover-department="companions"]').click();assert.equal(ui.get('shopSearch').value,'');assert.equal(ui.get('shopOwnership').value,'all');assert.equal(ui.get('shopGrid').querySelectorAll('article').length,1);ui.click('shopDiscoverTab');ui.click('shopAffordableShelf');assert.equal(ui.get('shopDepartmentCompact').value,'all');assert.equal(ui.get('shopSearch').value,'');assert.equal(ui.get('shopOwnership').value,'available');assert.equal(ui.get('shopResultCount').textContent,'1–12 of 26 cards');
});
test('search indexes real department and role metadata and type changes restore visible focus',async t=>{
 const ui=await armory(t);ui.click('shopCatalogTab');for(const [query,count]of [['support',1],['frontline',5],['ranged',5]]){search(ui,query);assert.equal(ui.get('shopGrid').querySelectorAll('article').length,count,query);}search(ui,'fire');ui.click('inspect-fireArrow');department(ui,'army');assert.equal(ui.visible('shopDetailDrawer'),false);assert.equal(ui.document.activeElement,ui.get('shopSearch'));
});

test('primary Deck tabs replace nested return chains while preserving catalog filters',async t=>{
 const ui=await armory(t);ui.click('shopCatalogTab');search(ui,'ice');const result=ui.get('shopResultCount').textContent;ui.click('shopLoadout');assert.equal(ui.get('closeSkills').textContent,'Back to deck');const tick=ui.battle.tick,gold=ui.battle.profile.gold;
 ui.get('skillsPanel').querySelector('[data-menu-route="settings"]').click();ui.click('openAim');ui.key('keydown','Escape');assert.equal(ui.visible('settingsPanel'),true);ui.get('settingsPanel').querySelector('[data-menu-route="deck"]').click();ui.click('shopBuildTab');assert.equal(ui.get('closeSkills').textContent,'Back to results');ui.click('openQueue');ui.click('closeQueue');assert.equal(ui.visible('skillsPanel'),true);ui.click('closeSkills');assert.equal(ui.visible('shopPanel'),false);ui.click('endingShop');assert.equal(ui.get('shopSearch').value,'ice');assert.equal(ui.get('shopResultCount').textContent,result);assert.equal(ui.battle.tick,tick);assert.equal(ui.battle.profile.gold,gold);
});
test('Begin next battle from armory full editor skips the return hop and clears the old origin',async t=>{
 const ui=await armory(t),previous=ui.battle;ui.click('shopLoadout');assert.equal(ui.get('loadoutContinue').textContent,'Begin battle 2');ui.click('loadoutContinue');assert.notEqual(ui.battle,previous);assert.equal(ui.battle.level,2);assert.equal(ui.battle.paused,false);assert.equal(ui.visible('shopPanel'),false);assert.equal(ui.visible('skillsPanel'),false);assert.equal(ui.visible('ending'),false);ui.click('battlePause');ui.click('pauseSkills');assert.equal(ui.get('closeSkills').textContent,'Back to Pause');ui.click('closeSkills');assert.equal(ui.visible('pauseOverlay'),true);assert.equal(ui.visible('shopPanel'),false);
});
test('new setup and profile selection clear an armory-origin editor before later loadouts',async t=>{
 const ui=await armory(t);ui.click('shopLoadout');ui.click('openTesting');ui.get('testLevel').value='3';ui.click('testLevelApply');assert.equal(ui.battle.level,3);ui.click('introLoadout');assert.equal(ui.get('closeSkills').textContent,'Back to lobby');ui.click('closeSkills');assert.equal(ui.visible('shopPanel'),false);
 ui.click('introTesting');ui.click('testVictory');ui.frames(105);ui.click('endingShop');ui.click('shopLoadout');ui.get('skillsPanel').querySelector('[data-menu-route="profiles"]').click();ui.get('newProfileName').value='FreshOrigin';ui.click('createProfile');assert.equal(ui.battle.profile.name,'FreshOrigin');ui.click('introLoadout');assert.equal(ui.get('closeSkills').textContent,'Back to lobby');ui.click('closeSkills');assert.equal(ui.visible('shopPanel'),false);
 ui.click('start');ui.click('battlePause');ui.click('battleRestart');ui.click('confirmRestart');ui.click('battlePause');ui.click('pauseSkills');assert.equal(ui.get('closeSkills').textContent,'Back to Pause');ui.click('closeSkills');assert.equal(ui.visible('shopPanel'),false);
});
