import test from 'node:test';import assert from 'node:assert/strict';
import {ArmyRoster,ARMY_PAGE_SIZE,armySnapshot,armyRecruitState,armyBinding,recruitFromArmy} from '../site/dist/army-command-model.mjs';
import {buildArmoryRecords} from '../site/dist/armory-catalog-data.mjs';
import {CampaignBattle} from '../site/dist/engine/first-battle.mjs';
import {PlayerProfile,SKILLS} from '../site/dist/engine/progression.mjs';
import {COMPANIONS} from '../site/dist/engine/recruitment.mjs';
function fixture(id='grunt',level=1){const profile=new PlayerProfile(),skill=profile.addSkill(id);profile.gold=1000;skill.cooldown=0;skill.autocast=false;const battle=new CampaignBattle({profile,level});battle.paused=true;return {profile,skill,battle,started:true,active:true};}
const balances=s=>[s.profile.gold,s.battle.friendlyQueue.population,s.battle.friendlyQueue.queue.length,s.skill.cooldown,s.battle.stats.goldSpent,s.battle.tick];
test('Army squad command is the normal paid summon with no elapsed time, bow or Auto changes',()=>{const s=fixture(),before=balances(s),active=s.battle.activeSkill,bar=s.battle.hotbar.bar,glow=s.battle.hotbar.glow;assert.equal(recruitFromArmy(s.skill,s),true);assert.deepEqual(balances(s),[before[0]-20,before[1]-4,4,660,before[4]+20,before[5]]);assert.equal(s.skill.autocast,false);assert.equal(s.battle.activeSkill,active);assert.equal(s.battle.hotbar.bar,bar);assert.equal(s.battle.hotbar.glow,glow);assert.equal(recruitFromArmy(s.skill,s),false);assert.equal(s.profile.gold,before[0]-20);});
test('Army commands revalidate current battle, ownership, binding, lifecycle and menu pause',()=>{for(const mutate of [s=>s.started=false,s=>s.battle.outcome='victory',s=>s.battle.summary={outcome:'victory'},s=>s.profile.owned.delete(s.skill.id),s=>s.profile.skills.splice(s.profile.skills.indexOf(s.skill),1),s=>s.skill.binding=-1,s=>s.skill.binding=29,s=>s.battle.hotbar.bars[0][s.skill.binding]=null,s=>s.battle.profile=new PlayerProfile(),s=>s.active=false,s=>s.battle.paused=false]){const s=fixture();mutate(s);const before=balances(s);assert.equal(recruitFromArmy(s.skill,s),false);assert.deepEqual(balances(s),before);}});
test('Recruit readiness names exact gold, reserve, reload and threshold blockers',()=>{const s=fixture();s.skill.cooldown=660;assert.equal(armyRecruitState(s.skill,s).code,'cooldown');s.skill.cooldown=0;s.profile.gold=19;assert.match(armyRecruitState(s.skill,s).detail,/20 gold/);s.profile.gold=20;s.battle.friendlyQueue.population=3;assert.equal(armyRecruitState(s.skill,s).code,'reserve');s.battle.friendlyQueue.population=4;s.battle.friendlyQueue.queue=Array(15).fill({type:'grunt',cost:1});assert.equal(armyRecruitState(s.skill,s).code,'queue');s.battle.friendlyQueue.queue.pop();assert.equal(recruitFromArmy(s.skill,s),true);assert.equal(s.battle.friendlyQueue.queue.length,18);assert.equal(s.profile.gold,0);assert.equal(s.battle.friendlyQueue.population,0);});
test('A full field allows a paid squad to wait without bypassing its cap',()=>{const s=fixture();while(s.battle.regularArmyCount<s.battle.friendlyQueue.cap)s.battle.createUnit('grunt',{team:'good'});assert.match(armyRecruitState(s.skill,s).detail,/field is full/);const count=s.battle.regularArmyCount;assert.equal(recruitFromArmy(s.skill,s),true);assert.equal(s.battle.regularArmyCount,count);assert.equal(s.battle.friendlyQueue.queue.length,4);assert.equal(s.battle.friendlyQueue.step(count),null);});
test('All twelve contracts display authoritative squad economics without companion mixing',()=>{const records=buildArmoryRecords(SKILLS,COMPANIONS,{}),model=new ArmyRoster(records);assert.equal(model.records.length,12);assert.equal(model.byId.has('gorath'),false);for(const item of model.records){const s=fixture(item.id);const before=balances(s);assert.equal(recruitFromArmy(s.skill,s),true);assert.equal(s.profile.gold,before[0]-SKILLS[item.id].summon.cost);assert.equal(s.battle.friendlyQueue.population,before[1]-item.squad.reserve);assert.equal(s.battle.friendlyQueue.queue.length,item.squad.size);assert.equal(s.skill.rank,0);assert.equal(s.skill.cooldown,SKILLS[item.id].cooldown);}});
test('Muster partitions occupied regular slots and reads the actual stage cap',()=>{const s=fixture('grunt',21),b=s.battle;b.goodTeam=[b.hero,{type:'grunt',hp:1,x:10},{type:'archer',hp:2,x:10,garrisonBuilding:{}},{type:'fire_demon',hp:3,x:-50},{type:'dragon_scout_ice',hp:0,x:50},{type:'gorath',hp:4,isCompanion:true,x:10}];const result=armySnapshot(b);assert.deepEqual(result.counts,{field:1,garrison:1,arriving:1,clearing:1});assert.equal(result.occupied,4);assert.equal(result.living,3);assert.equal(result.cap,b.friendlyQueue.cap);assert.equal(result.cap,18);assert.ok(result.groups.some(row=>row.id==='fireDemon'));assert.ok(result.groups.some(row=>row.id==='iceDragon'));assert.ok(!result.groups.some(row=>row.id==='gorath'));});
test('Queue cancellation refunds only its exact unit reserve cost and retains paid cooldown and gold',()=>{const s=fixture('fireDragon');recruitFromArmy(s.skill,s);const gold=s.profile.gold,cooldown=s.skill.cooldown,pop=s.battle.friendlyQueue.population;s.battle.friendlyQueue.cancel(0);assert.equal(s.battle.friendlyQueue.population,pop+3);assert.equal(s.profile.gold,gold);assert.equal(s.skill.cooldown,cooldown);});
test('Army roster remains paginated and type-filtered across hundreds of future records',()=>{const records=Array.from({length:503},(_,i)=>({id:'unit'+i,name:'Unit '+String(i).padStart(3,'0'),department:'army',role:i%2?'ranged':'frontline',traits:i%3?['ground']:['fire'],description:'Recorded unit',squad:{size:1,gold:20,reserve:1}})),model=new ArmyRoster(records),profile={skills:records.map(item=>({id:item.id,binding:-1,autocast:false})),owned:new Set(records.map(item=>item.id)),gold:100};const state={profile,battle:{profile,friendlyQueue:{queue:[]},hotbar:{bars:[[]]},summary:null,outcome:null},started:false};let seen=new Set();for(let page=0;page<42;page++){model.setView({page});const result=model.query(state);assert.ok(result.items.length<=ARMY_PAGE_SIZE);result.items.forEach(row=>seen.add(row.item.id));}assert.equal(seen.size,503);model.setView({role:'ranged',query:'fire'});let result=model.query(state);assert.equal(result.total,84);assert.ok(result.items.every(row=>row.item.role==='ranged'&&row.item.traits.includes('fire')));model.setView({page:9999});result=model.query(state);assert.equal(result.page,result.pageCount-1);model.setView({query:'not present'});assert.equal(model.query(state).total,0);assert.equal(model.query(state).page,0);});
test('Binding labels distinguish unassigned contract from reserve recruit pool',()=>{assert.equal(armyBinding({binding:-1}),'Not on an action bar');assert.equal(armyBinding({binding:9}),'Bar 1 · key 0');assert.equal(armyBinding({binding:29}),'Bar 3 · key 0');});
