import test from 'node:test';import assert from 'node:assert/strict';
import {CampaignBattle} from '../site/dist/engine/first-battle.mjs';
import {PlayerProfile,serializeProfile,summonSquad} from '../site/dist/engine/progression.mjs';
import {seededRandom} from '../site/dist/engine/combat.mjs';
import {FriendlyReinforcements} from '../site/dist/engine/campaign.mjs';
import {battleFieldLimits} from '../site/dist/engine/battle-director.mjs';
import {createArmyOrdersUI,drawArmyOrderMarker} from '../site/dist/army-orders-ui.mjs';
const fresh=()=>new CampaignBattle({profile:new PlayerProfile(),random:seededRandom(83)});
const place=(u,x)=>{u.x=x;u.y=u.world.elevationAt(x);u.vx=0;u.actionDuration=0;return u;};
for(const type of ['grunt','tallGrunt','mount','fireDemon','iceDemon'])test(`Rally settles ${type} at fixed line without oscillation`,()=>{
 const b=fresh(),u=place(b.createUnit(type,{team:'good'}),500);b.setArmyOrder('rally');const anchor=b.armyOrder.anchorX;b.hero.x=1100;
 for(let i=0;i<500;i++)u.step();assert.equal(b.armyOrder.anchorX,anchor);assert.ok(Math.abs(u.x-anchor)<=24,`${u.x}`);assert.equal(u.actionMode,'block');assert.equal(u.vx,0);
 place(u,anchor+150);for(let i=0;i<700;i++)u.step();assert.ok(Math.abs(u.x-anchor)<=24,`${u.x}`);assert.equal(u.actionMode,'block');
 b.setArmyOrder('advance');for(let i=0;i<200;i++)u.step();assert.ok(u.x>anchor+24);
});
test('order leaves gold, reserve, cooldowns, rank, stats and queued tickets alone',()=>{const b=fresh(),before=serializeProfile(b.profile),stats=JSON.stringify(b.stats),reserve=b.friendlyQueue.population;b.friendlyQueue.queue.push({type:'grunt',cost:1});const tickets=[...b.friendlyQueue.queue];b.setArmyOrder('rally');b.setArmyOrder('advance');assert.equal(serializeProfile(b.profile),before);assert.equal(JSON.stringify(b.stats),stats);assert.equal(b.friendlyQueue.population,reserve);assert.deepEqual(b.friendlyQueue.queue,tickets);});
test('invalid and out of bounds positions never create invalid rally coordinates',()=>{for(const x of [-1000,10000]){const b=fresh();b.hero.x=x;assert.equal(b.setArmyOrder('rally'),true);assert.ok(b.armyOrder.anchorX>=450&&b.armyOrder.anchorX<=1650);assert.ok(Number.isFinite(b.elevationAt(b.armyOrder.anchorX)));}for(const x of [NaN,Infinity,-Infinity]){const b=fresh();b.hero.x=x;assert.equal(b.setArmyOrder('rally'),false);assert.deepEqual(b.armyOrder,{mode:'advance',anchorX:null,affected:0});}});
test('repeated Rally is idempotent and does not move anchor after hero movement',()=>{const b=fresh();b.setArmyOrder('rally');const x=b.armyOrder.anchorX;b.hero.x=1200;b.setArmyOrder('rally');assert.equal(b.armyOrder.anchorX,x);assert.equal(b.setArmyOrder('anything'),false);});
test('flag carriers return home even under Rally',()=>{for(const flag of ['holdingEnemyFlag','holdingFriendFlag']){const b=fresh(),u=place(b.createUnit('grunt',{team:'good'}),900);u[flag]=true;b.setArmyOrder('rally');u.chooseNextAction();assert.equal(u.lastAction,'retreat');assert.equal(b.armyOrder.affected,0);}});
test('home-flag emergency bypasses Rally for recovery',()=>{const b=fresh(),u=place(b.createUnit('grunt',{team:'good'}),600);b.setArmyOrder('rally');b.ownFlag.status=0;b.ownFlag.x=500;u.chooseNextAction();assert.equal(u.lastAction,'retreat');assert.equal(b.armyOrders.frontlineAction(u),null);});
test('nearby engagement overrides line and active attacks are not cancelled by order changes',()=>{const b=fresh(),u=place(b.createUnit('mount',{team:'good'}),600),enemy=place(b.createUnit('grunt'),610);u.runner=1;b.setArmyOrder('rally');u.chooseNextAction();assert.equal(u.actionMode,'attack');assert.ok(u.attacking.includes(enemy));const timer=u.actionDuration;b.setArmyOrder('advance');assert.equal(u.actionDuration,timer);});
test('Rally preserves stun/death actions',()=>{const b=fresh(),u=place(b.createUnit('grunt',{team:'good'}),600);u.transition('daze');const timer=u.actionDuration;b.setArmyOrder('rally');assert.equal(u.actionMode,'daze');assert.equal(u.actionDuration,timer);u.takeDamage(u.hp);u.chooseNextAction();assert.equal(u.actionMode,'die');});
test('archer fires in normal range and only holds a distant pursuit',()=>{const b=fresh(),u=place(b.createUnit('archer',{team:'good'}),550),e=place(b.createUnit('grunt'),1900);b.setArmyOrder('rally');u.inShotRange=()=>true;u.chooseNextAction();assert.equal(u.actionMode,'load_arrow');u.inShotRange=()=>false;u.chooseNextAction();assert.equal(u.lastAction,'retreat');place(u,500);u.chooseNextAction();assert.equal(u.lastAction,'block');});
test('wounded and poisoned ally support remains normal during Rally',()=>{for(const poisoned of [false,true]){const b=fresh(),u=place(b.createUnit('priest',{team:'good'}),600),friend=place(b.createUnit('grunt',{team:'good'}),650);b.setArmyOrder('rally');u.healCooldown=-1;if(poisoned)friend.effects.effects.push({kind:'poison'});else friend.hp-=20;u.chooseNextAction();assert.equal(u.actionMode,poisoned?'purge':'heal');assert.equal(u.healTarget,friend);}});
test('flyers, siege, enemies and Gorath are never direct rally actors',()=>{const b=fresh();b.setArmyOrder('rally');for(const type of ['air','fireDragon','iceDragon','poisonDragon','trebuchet']){const u=b.createUnit(type,{team:'good'});assert.equal(b.armyOrders.frontlineAction(u),null);}const enemy=b.createUnit('grunt');assert.equal(b.armyOrders.frontlineAction(enemy),null);const boss=b.createUnit('gorath',{team:'good',companion:true});assert.equal(b.armyOrders.frontlineAction(boss),null);});
test('keep fall releases line before cleanup; no new Rally after supply cutoff',()=>{const events=[],b=new CampaignBattle({onEvent:e=>events.push(e)});b.createUnit('grunt');b.setArmyOrder('rally');b.badCastle.takeDamage(b.badCastle.hp);assert.equal(b.armyOrder.mode,'advance');assert.equal(b.setArmyOrder('rally'),false);assert.equal(b.enemies.remaining,0);assert.equal(b.outcome,null);assert.ok(events.some(e=>e.type==='army-order'&&e.mode==='advance'));});
test('pause preserves orders without advancing, result/reset makes a new battle Advance',()=>{const b=fresh();b.setArmyOrder('rally');b.paused=true;const before=b.armyOrder;for(let i=0;i<100;i++)b.step();assert.equal(b.tick,0);assert.deepEqual(b.armyOrder,before);b.paused=false;b.step();assert.equal(b.armyOrder.mode,'rally');b.finishOutcome('defeat');assert.equal(b.armyOrder.mode,'advance');assert.equal(b.setArmyOrder('rally'),false);assert.equal(fresh().armyOrder.mode,'advance');});
test('Advance paths have exact deterministic simulation parity with no orders controller',()=>{function run(controller){const b=fresh();for(const type of ['grunt','mount','archer','priest','trebuchet','fireDemon','air'])b.createUnit(type,{team:'good'});if(!controller)b.armyOrders=null;for(let i=0;i<1400&&!b.outcome;i++)b.step();return JSON.stringify({tick:b.tick,outcome:b.outcome,profile:serializeProfile(b.profile),stats:b.stats,good:b.goodTeam.map(u=>[u.type,u.x,u.y,u.hp,u.actionMode,u.actionDuration]),bad:b.badTeam.map(u=>[u.type,u.x,u.y,u.hp,u.actionMode,u.actionDuration]),director:b.enemies.index});}assert.equal(run(true),run(false));});
test('14/16/18 ally slots retain existing enemy caps',()=>{for(let l=1;l<=30;l++)assert.deepEqual(battleFieldLimits(l),l<7?{friendly:14,enemy:20}:l<13?{friendly:16,enemy:22}:{friendly:18,enemy:24});});
test('entry cadence is exactly20ticks with normal resource and cap semantics',()=>{const q=new FriendlyReinforcements({population:20});assert.equal(q.enqueueSquad({type:'grunt',cost:1},4),true);assert.equal(q.population,16);let spawns=[];for(let t=0;t<70;t++)if(q.step(0))spawns.push(t);assert.deepEqual(spawns,[0,20,40,60]);q.enqueue({type:'grunt',cost:1});for(let i=0;i<100;i++)assert.equal(q.step(q.cap),null);assert.equal(q.queue.length,1);assert.equal(q.cancel(0).cost,1);assert.equal(q.population,16);});
test('marker uses finite world position and draws only while rally active',()=>{const b=fresh(),calls=[],ctx=new Proxy({},{get:(_,p)=> (...args)=>calls.push([p,args]),set:()=>true});assert.equal(drawArmyOrderMarker(ctx,b),false);b.setArmyOrder('rally');assert.equal(drawArmyOrderMarker(ctx,b),true);assert.ok(calls.some(([method,args])=>method==='fillText'&&args[0]==='RALLY'));});
function uiFixture(){const b=fresh(),state={battle:b,active:true,started:true,readOnly:false},buttons=['advance','rally'].map(mode=>({mode,attributes:{},getAttribute(){return mode;},setAttribute(k,v){this.attributes[k]=v;},addEventListener(_,f){this.click=f;}})),status={},root={set innerHTML(x){this.html=x;},querySelectorAll:()=>buttons,querySelector:()=>status};const ui=createArmyOrdersUI({root,getState:()=>state});ui.render();return {b,state,buttons,status,ui};}
test('UI native buttons issue paused orders with immediate selected/status feedback',()=>{const {b,buttons,status,ui}=uiFixture();b.paused=true;buttons[1].click();assert.equal(b.armyOrder.mode,'rally');assert.equal(buttons[1].attributes['aria-pressed'],'true');assert.match(status.textContent,/resumes/);buttons[0].click();assert.equal(b.armyOrder.mode,'advance');});
test('UI rejects preparation/read-only/stale-session requests',()=>{for(const kind of ['started','readOnly','stale']){const {b,state,buttons}=uiFixture();if(kind==='started')state.started=false;if(kind==='readOnly')state.readOnly=true;if(kind==='stale')state.battle=fresh();buttons[1].click();assert.equal(b.armyOrder.mode,'advance');assert.equal(state.battle.armyOrder.mode,'advance');}});

test('Rally waiting never permanently changes a cavalry or flag-runner role',()=>{const b=fresh(),u=place(b.createUnit('mount',{team:'good'}),600);assert.equal(u.runner,1);b.setArmyOrder('rally');u.chooseNextAction();assert.equal(u.actionMode,'block');assert.equal(u.runner,1);b.setArmyOrder('advance');assert.equal(u.runner,1);});
