import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {loadGameUI} from './helpers/game-ui-harness.mjs';
const text=ui=>ui.get('battleReportText').value;
const open=ui=>ui.click(ui.battle.paused?'pauseBattleReport':'introBattleReport');
const start=ui=>{ui.click('introBattleReport');ui.click('renderProfileStart');ui.click('closeBattleReport');ui.click('start');ui.frames(2);};
function switchTo(ui,id){ui.document.querySelector(`[data-hub-destination="${id}"]`).click();ui.click('start');if(ui.visible('switchSessionConfirm'))ui.click('confirmSessionSwitch');ui.frames();}

test('profiler is off by default; report remains frozen; arming waits for actual live callback',async t=>{const ui=await loadGameUI(t);ui.click('introBattleReport');assert.match(text(ui),/RENDERING SAMPLE · LOCAL ONLY\nState: idle/);assert.equal(ui.get('renderProfileStop').disabled,true);ui.click('renderProfileStart');assert.match(text(ui),/State: armed/);assert.equal(ui.get('renderProfileStart').disabled,true);ui.frames(3);assert.equal(ui.battle.tick,0);ui.click('battleReportRefresh');assert.match(text(ui),/State: armed/);ui.click('closeBattleReport');ui.click('start');ui.frames(4);ui.click('battlePause');open(ui);assert.match(text(ui),/State: recording/);assert.match(text(ui),/Animation callback intervals: n=3/);assert.match(text(ui),/Simulation tick callback CPU: n=4/);assert.match(text(ui),/accepted; 0 unmatched/);assert.equal(ui.get('battleReportRecording').checked,false);});
test('Testing report back and focus paths still work; label explicitly distinguishes controlled fixture',async t=>{const ui=await loadGameUI(t,{search:'?mode=test'});ui.click('introTesting');ui.click('testBattleReport');ui.get('renderProfileKind').value='controlled-fixture';ui.click('renderProfileStart');assert.match(text(ui),/Controlled fixture \(operator-labelled\) \| assisted field: yes/);ui.get('closeBattleReport').focus();ui.key('keydown','Tab',{shiftKey:true});assert.equal(ui.document.activeElement,ui.get('battleReportText'));ui.key('keydown','Escape');assert.equal(ui.visible('testingPanel'),true);ui.click('closeTesting');assert.equal(ui.visible('intro'),true);});
test('clear cancels armed or running sample without touching event recording or engine facts',async t=>{const ui=await loadGameUI(t);ui.click('introBattleReport');ui.get('battleReportRecording').checked=true;ui.dispatch(ui.get('battleReportRecording'),'change');ui.battle.emit({type:'shot',skill:'arrow'});ui.click('renderProfileStart');const tick=ui.battle.tick,hp=ui.battle.hero.hp;ui.click('renderProfileClear');assert.match(text(ui),/State: idle/);assert.match(text(ui),/0 shot/);assert.equal(ui.get('battleReportRecording').checked,true);assert.equal(ui.battle.tick,tick);assert.equal(ui.battle.hero.hp,hp);ui.click('renderProfileStart');ui.click('renderProfileStop');assert.match(text(ui),/State: complete · stopped/);assert.match(text(ui),/Window: 0 \/ 30000/);});
test('manual stop is a partial sample, reopening preserves it and rearm replaces it',async t=>{const ui=await loadGameUI(t);start(ui);ui.click('battlePause');open(ui);ui.click('renderProfileStop');assert.match(text(ui),/complete · stopped/);const before=text(ui);ui.click('closeBattleReport');assert.equal(ui.battle.paused,true);open(ui);assert.equal(text(ui),before);ui.click('renderProfileStart');assert.match(text(ui),/State: armed/);assert.match(text(ui),/Animation callback intervals: n=0/);assert.equal(ui.battle.paused,true);});
test('hidden time ends fixed window with no manufactured or late render samples',async t=>{const ui=await loadGameUI(t);start(ui);ui.document.hidden=true;ui.dispatch(ui.document,'visibilitychange');ui.frames(1000);ui.document.hidden=false;ui.dispatch(ui.document,'visibilitychange');open(ui);assert.match(text(ui),/State: complete · window-complete/);assert.match(text(ui),/Window: 30000 \/ 30000/);assert.match(text(ui),/Animation callback intervals: n=1/);assert.match(text(ui),/Canvas render-submission intervals: n=1/);assert.equal(ui.battle.paused,true);});
test('pause/resume creates a gap, keeps fixed deadline, and never samples menu repaint as gameplay',async t=>{const ui=await loadGameUI(t);start(ui);ui.click('battlePause');ui.frames(5);open(ui);ui.click('battleReportRefresh');assert.match(text(ui),/Animation callback intervals: n=1/);ui.click('closeBattleReport');ui.click('resumeGame');ui.frames(2);ui.click('battlePause');open(ui);assert.match(text(ui),/Animation callback intervals: n=2/);assert.match(text(ui),/Canvas render-submission intervals: n=2/);assert.match(text(ui),/paused [1-9]/);});
test('battle replacement/session switch resets profiling and cannot resurrect a prior sample',async t=>{const ui=await loadGameUI(t);start(ui);ui.click('battlePause');ui.click('battleRestart');ui.click('confirmRestart');ui.frames(2);ui.click('battlePause');open(ui);assert.match(text(ui),/State: idle/);ui.click('renderProfileStart');ui.click('closeBattleReport');ui.click('pauseLobby');switchTo(ui,'training');ui.click('introBattleReport');assert.match(text(ui),/State: idle/);ui.click('closeBattleReport');switchTo(ui,'campaign');ui.click('introBattleReport');assert.match(text(ui),/State: idle/);});
test('supplied harness pointer events cannot masquerade as native input samples',async t=>{const ui=await loadGameUI(t);start(ui);const point=ui.battle.hero.launchPosition;ui.pointer('pointerdown',71,point);ui.pointer('pointerup',71,point);ui.frames(2);ui.click('battlePause');open(ui);assert.match(text(ui),/Input events: 0 accepted/);assert.match(text(ui),/2 untrusted\/synthetic ignored/);assert.match(text(ui),/Accepted canvas pointer handler → next render submission: n=0; p50 unavailable/);});
test('a controlled trusted-event harness proves hook wiring only, no physical latency evidence',async t=>{const ui=await loadGameUI(t);ui.click('introBattleReport');ui.get('renderProfileKind').value='controlled-fixture';ui.click('renderProfileStart');ui.click('closeBattleReport');ui.click('start');ui.frames(2);const point=ui.battle.hero.launchPosition,canvas=ui.get('battlefield');ui.dispatch(canvas,'pointerdown',{pointerId:77,clientX:point.x,clientY:point.y,isTrusted:true});ui.dispatch(canvas,'pointerup',{pointerId:77,clientX:point.x,clientY:point.y,isTrusted:true});ui.frames(2);ui.click('battlePause');open(ui);assert.match(text(ui),/Input events: 2 accepted/);assert.match(text(ui),/Accepted canvas pointer handler → next render submission: n=2/);assert.match(text(ui),/Controlled fixture/);});
test('copy includes displayed sample only after action and never trusts textarea edits',async t=>{const ui=await loadGameUI(t),copied=[];ui.window.navigator.clipboard={writeText:async t=>copied.push(t)};start(ui);assert.equal(copied.length,0);ui.click('battlePause');open(ui);ui.click('renderProfileStop');const expected=text(ui);ui.get('battleReportText').value='PRIVATE INPUT';await ui.click('battleReportCopy').completed;assert.deepEqual(copied,[expected]);assert.match(copied[0],/RENDERING SAMPLE/);});
test('integration keeps profiler inside report utility, no network/storage/engine writes or permanent HUD',async()=>{const html=await readFile(new URL('../site/dist/battle.html',import.meta.url),'utf8'),ui=await readFile(new URL('../site/dist/battle-render-profiler-ui.mjs',import.meta.url),'utf8');assert.ok(html.indexOf('id="renderProfileStart"')>html.indexOf('id="battleReportPanel"'));assert.ok(html.indexOf('id="renderProfileStart"')<html.indexOf('id="testingPanel"'));assert.doesNotMatch(ui,/fetch\s*\(|sendBeacon|localStorage|sessionStorage|setTimeout|setInterval|dispatchEvent|innerHTML/);});
