import test from 'node:test';import assert from 'node:assert/strict';
import {BattleDirector,battleFieldLimits,observeBattlefield} from '../site/dist/engine/battle-director.mjs';
import {CampaignBattle} from '../site/dist/engine/first-battle.mjs';
import {PlayerProfile,serializeProfile,restoreProfile} from '../site/dist/engine/progression.mjs';
import {seededRandom} from '../site/dist/engine/combat.mjs';
import {campaignRoster} from '../site/dist/engine/levels.mjs';
import {WaveBudget} from '../site/dist/engine/campaign.mjs';
import {FLAG_STATUS as F} from '../site/dist/engine/flag-troop.mjs';
const state=changes=>({onScreen:0,allies:0,enemyAlive:0,enemyStrength:0,enemyWounded:0,enemyFront:0,allyBreach:0,enemyFlagThreatened:false,castleFallen:false,...changes});
const fresh=(level=13,difficulty='medium',onEvent=()=>{})=>{const profile=new PlayerProfile();profile.difficulty=difficulty;return new CampaignBattle({level,profile,random:seededRandom(131),onEvent});};
const director=(roster,options={})=>new BattleDirector({roster,wave:new WaveBudget({random:()=>0}),...options});
const count=xs=>xs.reduce((a,x)=>(a[x]=(a[x]??0)+1,a),{});

test('balanced field caps increase only at campaign milestones',()=>{for(let l=1;l<=30;l++)assert.deepEqual(battleFieldLimits(l),l<7?{friendly:10,enemy:20}:l<13?{friendly:12,enemy:22}:{friendly:14,enemy:24});});
test('snapshot contains only battlefield facts, excludes hidden player planning',()=>{const b=fresh();b.input=new Proxy({},{get(){throw Error('input read');}});b.activeSkill=new Proxy({},{get(){throw Error('skill read');}});b.profile=new Proxy({},{get(){throw Error('profile read');}});assert.deepEqual(Object.keys(observeBattlefield(b)).sort(),['allies','allyBreach','castleFallen','enemyAlive','enemyApproaching','enemyElites','enemyFlagThreatened','enemyFront','enemyStrength','enemyWounded','onScreen'].sort());});
test('field snapshot uses true dragon/demon/boss threat aliases',()=>{const b=fresh(30);for(const kind of ['fireDragon','iceDragon','poisonDragon','fireDemon','iceDemon','gorath'])b.createUnit(kind);assert.equal(observeBattlefield(b).enemyStrength,18.5);});
test('same seed produces identical finite deterministic role squads',()=>{const run=()=>{const b=fresh(),out=[];for(let i=0;i<1200;i++){b.step();if(b.enemies.index!==out.length)out.push(...b.enemies.roster.slice(out.length,b.enemies.index));}return {out,index:b.enemies.index,phase:b.enemies.phase,types:b.badTeam.map(u=>u.type)};};assert.deepEqual(run(),run());});
test('opening avoids automatic cavalry or special-unit rushes',()=>{const d=director(['mount','fireDragon',...Array(8).fill('grunt'),'archer','priest','trebuchet']);d.plan(state());assert.deepEqual(d.pending,['grunt','grunt','archer','grunt']);});
test('roles react to flags, breached keep and visibly wounded allies',()=>{const d=director(['grunt','mount','priest','archer','tallGrunt','trebuchet']);d.squads=1;assert.equal(d.chooseRole(state({enemyFlagThreatened:true})),'rescue');assert.equal(d.chooseRole(state({allyBreach:2})),'defense');assert.equal(d.chooseRole(state({enemyWounded:3})),'recovery');assert.equal(d.chooseRole(state()),'support');});
test('small squads choose only available finite types and at most one heavy special',()=>{const d=director(['fireDragon','iceDragon','fireDemon','trebuchet','priest','grunt','mount','archer']);d.squads=3;d.plan(state({allies:14}));assert.ok(d.pending.length<=4);assert.ok(d.pending.includes('fireDragon'));assert.equal(d.pending.filter(t=>['fireDragon','iceDragon','fireDemon','trebuchet'].includes(t)).length,1);for(const x of d.pending)assert.ok(d.roster.includes(x));});
test('all30 level rosters conserve counts and fully exhaust without empty wave delays',()=>{for(let level=1;level<=30;level++)for(const difficulty of ['easy','medium','hard','insane']){const roster=campaignRoster(level,seededRandom(131)),d=director(roster,{level,difficulty}),spawns=[];let tick=0,last=0,maxGap=0;for(;tick<50000&&d.remaining;tick++){const t=d.step(state());if(t){spawns.push(t);maxGap=Math.max(maxGap,tick-last);last=tick;}}assert.equal(d.remaining,0,`${level}/${difficulty}`);assert.deepEqual(count(spawns),count(roster));assert.ok(maxGap<=d.regroupTicks+d.assemblyTicks+2,`${level}/${difficulty}: ${maxGap}`);assert.equal(d.index,roster.length);}});
test('pressure stalls further reserves rather than piling onto the player home',()=>{const d=director(Array(30).fill('grunt'));for(let i=0;i<500;i++)assert.equal(d.step(state({onScreen:4,enemyStrength:4,enemyFront:4})),null);assert.equal(d.index,0);assert.equal(d.phase,'holding');});
test('both slot cap and planned squad cap hold during pressure changes',()=>{const d=director(Array(60).fill('grunt'));d.plan(state({allies:14}));for(let i=0;i<1000;i++)assert.equal(d.step(state({onScreen:d.cap,allies:14})),null);assert.equal(d.index,0);let spawns=0;for(let i=0;i<300;i++){if(d.step(state({onScreen:d.cap-1+spawns,allies:14})))spawns++;}assert.equal(spawns,1);});
test('Easy has smaller desired force and longer recovery, not stronger hidden stats',()=>{const easy=director(['grunt'],{difficulty:'easy'}),medium=director(['grunt']);assert.ok(easy.targetStrength(state({allies:10}))<medium.targetStrength(state({allies:10})));assert.ok(easy.regroupTicks>medium.regroupTicks);});
test('castle fall cuts regular reserves at once and never gives kill rewards',()=>{const b=fresh(),before=serializeProfile(b.profile),stats={...b.stats},total=b.enemies.remaining;b.badCastle.takeDamage(b.badCastle.hp);assert.equal(b.enemies.remaining,0);assert.equal(b.enemies.withdrawn,total);assert.equal(b.outcome,'victory');assert.deepEqual(b.stats,stats);const p=JSON.parse(before),after=JSON.parse(serializeProfile(b.profile));assert.equal(after.gold,p.gold);assert.equal(after.xp,p.xp);assert.deepEqual(after.skills,p.skills);});
test('withdrawal is idempotent, keeps full roster accounting and does not spawn canceled reserves',()=>{const d=director(['grunt','archer','gorath','mount']);const before=count(d.roster);assert.deepEqual(d.closeReserves(),{withdrawn:3,bosses:1});assert.equal(d.closeReserves(),null);assert.equal(d.step(state()),'gorath');assert.equal(d.remaining,0);assert.deepEqual(count(d.roster),before);for(let i=0;i<2000;i++)assert.equal(d.step(state()),null);assert.equal(d.spawned,1);});
test('pending final boss is dispatched first simulation tick, with no wave wait',()=>{const b=fresh(30);b.badCastle.takeDamage(b.badCastle.hp);assert.equal(b.outcome,null);assert.equal(b.enemies.remaining,1);assert.equal(b.enemies.phase,'last-stand');b.step();assert.equal(b.enemies.remaining,0);assert.equal(b.badTeam.length,1);assert.equal(b.badTeam[0].type,'gorath');assert.ok(b.badTeam[0].x>=0&&b.badTeam[0].x<b.width);assert.ok(Number.isFinite(b.badTeam[0].y));assert.ok(b.badTeam[0].hitbox.x+b.badTeam[0].hitbox.width<=b.width);assert.equal(b.outcome,null);});
test('existing boss and flag carrier survive reserve closure unchanged',()=>{const b=fresh(30),boss=b.createUnit('gorath'),carrier=b.createUnit('grunt');carrier.x=1500;carrier.holdingEnemyFlag=true;b.ownFlag.status=F.HELD_BY_ENEMY;b.ownFlag.holder=carrier;const hp=boss.hp;b.badCastle.takeDamage(b.badCastle.hp);assert.ok(b.badTeam.includes(boss));assert.ok(b.badTeam.includes(carrier));assert.equal(boss.hp,hp);assert.equal(b.ownFlag.holder,carrier);assert.equal(b.outcome,null);});
test('castle fall does not automatically beat living garrison defenders',()=>{const b=fresh(),archer=b.createUnit('archer');archer.x=b.badCastle.x;archer.garrisonBuilding=b.badCastle;b.badCastle.addOccupant(archer);b.badCastle.takeDamage(b.badCastle.hp);assert.equal(b.outcome,null);b.step();assert.equal(archer.garrisonBuilding,null);assert.ok(b.badTeam.includes(archer));assert.equal(b.outcome,null);});
test('normal flag victory remains immediate despite every reserve and surviving boss',()=>{const b=fresh(30);b.createUnit('gorath');const reserves=b.enemies.remaining;b.enemyFlag.status=F.CAPTURED;b.ownFlag.status=F.AT_BASE;b.checkOutcome();assert.equal(b.outcome,'victory');assert.equal(b.enemies.remaining,reserves);assert.ok(b.badTeam[0].hp>0);});
test('ordinary defeat precedence remains when hero dies or flag is captured',()=>{for(const mode of ['hero','flag']){const b=fresh();if(mode==='hero')b.hero.takeDamage(1e9);else{b.ownFlag.status=F.CAPTURED;b.checkOutcome();}assert.equal(b.outcome,'defeat');}});
test('dominating post-collapse cleanup ends within normal two-second death lifecycle',()=>{for(const difficulty of ['easy','medium'])for(const level of [1,7,13,20,30]){const b=fresh(level,difficulty);for(let i=0;i<330;i++){for(const u of b.badTeam)if(u.hp>0)u.takeDamage(1e9);b.step();}b.badCastle.takeDamage(b.badCastle.hp);const collapse=b.tick;while(!b.outcome&&b.tick-collapse<100){for(const u of b.badTeam)if(u.hp>0)u.takeDamage(1e9);b.step();}assert.equal(b.outcome,'victory',`${level}/${difficulty}`);assert.ok(b.tick-collapse<=71);}});
test('no automatic victory while a legitimate enemy remains even after long final stand',()=>{const b=fresh(),u=b.createUnit('grunt');u.step=()=>{};b.badCastle.takeDamage(b.badCastle.hp);for(let i=0;i<1000;i++)b.step();assert.equal(b.outcome,null);assert.equal(b.badTeam.length,1);assert.equal(b.enemies.remaining,0);assert.match(b.enemies.status(observeBattlefield(b)),/1 approaching/);});
test('pause freezes director, options preserve pending countdown, restart and save start fresh',()=>{const b=fresh();for(let i=0;i<30;i++)b.step();const before=JSON.stringify({tick:b.tick,index:b.enemies.index,pending:b.enemies.pending,timer:b.enemies.timer,phase:b.enemies.phase});b.paused=true;for(let i=0;i<400;i++)b.step();assert.equal(JSON.stringify({tick:b.tick,index:b.enemies.index,pending:b.enemies.pending,timer:b.enemies.timer,phase:b.enemies.phase}),before);const timer=b.enemies.timer;b.applyOptions({difficulty:'easy'});assert.equal(b.enemies.timer,timer);b.badCastle.takeDamage(b.badCastle.hp);const restored=new CampaignBattle({profile:restoreProfile(serializeProfile(b.profile)),level:13,random:seededRandom(131)});assert.equal(restored.enemies.withdrawn,0);assert.equal(restored.enemies.index,0);assert.equal(restored.enemies.phase,'muster');assert.equal(restored.friendlyQueue.cap,14);});

test('Easy holds a second high-resistance elite in reserve until the first falls',()=>{const d=director(['fireDragon','iceDragon'],{difficulty:'easy'});d.squads=3;assert.equal(d.plan(state({enemyElites:1,enemyStrength:2.5,allies:14})),false);assert.equal(d.remaining,2);assert.equal(d.plan(state({enemyElites:0,allies:14})),true);assert.equal(d.pending.filter(x=>x.includes('Dragon')).length,1);});

test('withdrawn reserve count cannot inflate ordinary victory bonuses or XP',()=>{const run=count=>{const b=fresh();b.enemies.roster=Array(count).fill('grunt');b.badCastle.takeDamage(b.badCastle.hp);while(!b.summary)b.step();return {summary:b.summary,gold:b.profile.gold,xp:b.profile.xp,skills:b.profile.skills.map(s=>[s.rank,s.xp])};};assert.deepEqual(run(0),run(300));});
test('a capped final field waits only for real slots and never drops a boss',()=>{const b=fresh(30);for(let i=0;i<b.enemies.cap;i++)b.createUnit('grunt');b.badCastle.takeDamage(b.badCastle.hp);b.step();assert.equal(b.enemies.remaining,1);assert.equal(b.badTeam.filter(u=>u.type==='gorath').length,0);for(const u of b.badTeam)u.takeDamage(1e9);const start=b.tick;while(b.enemies.remaining&&b.tick-start<100)b.step();assert.equal(b.enemies.remaining,0);assert.equal(b.badTeam.filter(u=>u.type==='gorath').length,1);assert.ok(b.tick-start<=72);assert.equal(b.outcome,null);});

test('switching to Easy defers a planned second elite without consuming reserve',()=>{const d=director(['fireDragon','grunt']);d.pending=['fireDragon','grunt'];d.timer=0;d.setDifficulty('easy');assert.equal(d.step(state({enemyElites:1,enemyStrength:6,allies:14})),null);assert.equal(d.remaining,2);assert.equal(d.index,0);assert.equal(d.pending.length,0);for(let i=0;i<100;i++)d.step(state({enemyElites:0}));assert.ok(d.index>0);});
