import test from 'node:test';import assert from 'node:assert/strict';
import {loadGameUI} from './helpers/game-ui-harness.mjs';
import {CAUSEWAY_BRIEF,causewayFeedbackState,drawCausewayGround} from '../site/dist/causeway-presentation.mjs';
import {SkirmishBattle} from '../site/dist/skirmish-battle.mjs';
const search='?mode=skirmish&sk=SK1:16:oaks:scout:causeway';
test('preparation, HUD and Pause describe exact cumulative objective without advancing ticks',async t=>{const ui=await loadGameUI(t,{search});assert.match(ui.get('skirmishPreview').textContent,/30 cumulative seconds/);ui.click('skirmishPrepare');ui.frames(3);assert.equal(ui.battle.tick,0);assert.equal(ui.get('hallOrderObjective').textContent,CAUSEWAY_BRIEF.goal);assert.match(ui.get('hallOrderAdvice').textContent,/Frontline Center/);assert.equal(ui.get('combatBattleTitle').textContent,'Causeway · 0.0/30s');assert.match(ui.get('viewStatus').textContent,/Causeway/);assert.equal(ui.visible('batteryObjectiveBrief'),true);assert.match(ui.get('batteryObjectiveBrief').textContent,/Garrisoned troops, aircraft, siege/);});
test('real post-tick stranded receipt reaches result and retry supplies without false capture prose',async t=>{const ui=await loadGameUI(t,{search});ui.click('skirmishPrepare');ui.click('start');ui.frames(2);const b=ui.battle;b.friendlyQueue.population=0;b.ownFlag.status=0;b.ownFlag.x=1300;ui.frames(120);assert.equal(b.summary.outcome,'defeat');assert.deepEqual(b.causewayDefeatCauses,['unrecoverable-home-flag']);assert.equal(ui.get('endingTitle').textContent,'Causeway lost');assert.match(ui.get('endingText').textContent,/flag is stranded/);assert.doesNotMatch(ui.get('endingText').textContent,/flag was captured|hero fell|basic shots/);ui.click('replay');ui.frames();assert.notEqual(ui.battle,b);assert.equal(ui.battle.tick,0);assert.equal(ui.battle.friendlyQueue.population,70);assert.equal(ui.battle.profile.gold,1200);assert.equal(ui.battle.objectiveProgress.ticks,0);});
test('ordinary practice replacement clears only Causeway presentation',async t=>{const ui=await loadGameUI(t,{search});ui.click('skirmishPrepare');ui.frames();ui.click('introWorkshop');ui.get('skirmishCode').value='SK1:16:oaks:scout:vanguard';ui.click('skirmishLoadCode');ui.click('skirmishPrepare');ui.frames();assert.equal(ui.battle.causewayObjective,undefined);assert.equal(ui.visible('batteryObjectiveBrief'),false);assert.doesNotMatch(ui.get('combatBattleTitle').textContent,/Causeway/);});
test('ground marker uses exact endpoints and terrain, restoring canvas state without DOM interaction',()=>{const b=new SkirmishBattle({descriptor:{version:1,seed:42,biome:'oaks',threat:'scout',doctrine:'causeway'}}),calls=[],ctx=new Proxy({}, {get:(o,k)=>k in o?o[k]:(...args)=>calls.push([k,...args]),set:(o,k,v)=>(o[k]=v,true)});assert.equal(drawCausewayGround(ctx,b,.5),true);assert.equal(calls[0][0],'save');assert.equal(calls.at(-1)[0],'restore');assert.ok(calls.some(c=>c[0]==='moveTo'&&c[1]===990&&c[2]===b.elevationAt(990)));assert.ok(calls.some(c=>c[0]==='lineTo'&&c[1]===1110&&c[2]===b.elevationAt(1110)));assert.equal(drawCausewayGround(ctx,b,NaN),false);assert.equal(causewayFeedbackState({}),null);});

test("Causeway preparation warns about the actual Basic Arrow ground-friendly-fire tradeoff",()=>{assert.match(CAUSEWAY_BRIEF.advice,/Basic arrows can hit friendly ground troops/);assert.doesNotMatch(CAUSEWAY_BRIEF.advice,/all arrows are enemy-only|friendly units are immune/);});
