/** Independent review regressions. All scenarios here are controlled engine/UI
 * fixtures, not native/manual balance or an earned completion proof. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {CampaignBattle} from '../site/dist/engine/first-battle.mjs';
import {SkirmishBattle} from '../site/dist/skirmish-battle.mjs';
import {FLAG_STATUS as FS} from '../site/dist/engine/flag-troop.mjs';
import {flagRecoveryOptions} from '../site/dist/engine/flag-recovery-options.mjs';
import {causewayFeedbackState} from '../site/dist/causeway-presentation.mjs';
import {rallyObjectiveAvailable} from '../site/dist/engine/army-orders.mjs';
import {troopStats} from '../site/dist/engine/combat.mjs';
import {loadGameUI} from './helpers/game-ui-harness.mjs';
const descriptor=(threat='scout',biome='oaks',seed=42)=>({version:1,seed,biome,threat,doctrine:'causeway'});
const make=(onEvent=()=>{})=>new SkirmishBattle({descriptor:descriptor(),onEvent});
const ground=b=>{b.ownFlag.status=FS.GROUNDED;b.ownFlag.x=1400;b.ownFlag.y=b.elevationAt(1400);b.ownFlag.holder=null;b.friendlyQueue.population=0;return b;};
const clearField=b=>{for(const u of [...b.badTeam])u.destroy();};
const holdFixture=(b,n=989)=>{clearField(b);b.enemies.closeReserves();b.hero.leaveGarrison();b.hero.x=1050;b.hero.y=b.elevationAt(1050);for(let i=0;i<n;i++)b.step();};
for(const [name,mutate] of [
 ['NaN x',b=>b.ownFlag.x=NaN],['infinite y',b=>b.ownFlag.y=Infinity],
 ['left of reachable world',b=>b.ownFlag.x=-1],['right of reachable world',b=>b.ownFlag.x=b.width+1],
 ['grounded but held by a dying actor',b=>{const u=b.badTeam[0];u.hp=0;b.ownFlag.holder=u;}],
 ['unrecognized flag object',b=>b.ownFlag={...b.ownFlag}],
])test(`recovery proof fails open for ${name}`,()=>{const b=ground(make());mutate(b);assert.equal(flagRecoveryOptions(b).state,'unknown');b.step();assert.equal(b.outcome,null);});
for(const field of ['testing','protectedTesting'])test(`${field} fixture cannot auto-settle exhausted recovery`,()=>{const b=ground(make());b[field]=true;assert.equal(flagRecoveryOptions(b).state,'unknown');b.step();assert.equal(b.outcome,null);});
test('unknown world producer remains live until a delayed real recovery squad appears',()=>{const b=ground(make());let remaining=10;const producer={step(){if(--remaining===0){b.createUnit('grunt',{team:'good',rank:2});b.objects.remove(producer);}}};b.addObject(producer);assert.equal(flagRecoveryOptions(b).state,'unknown');for(let n=0;n<10;n++){b.step();assert.equal(b.outcome,null);}assert.equal(flagRecoveryOptions(b).reason,'living-recoverer');});
test('unknown dead actor cannot be assumed incapable of later recovery or spawning',()=>{const b=ground(make());b.addObject({isFighter:true,hp:0,dead:true,step(){}});assert.equal(flagRecoveryOptions(b).state,'unknown');b.step();assert.equal(b.outcome,null);});
test('unknown structure/queue behavior invalidates the no-producer/refund proof',()=>{for(const mutate of [b=>b.goodCastle.step=()=>{},b=>b.friendlyQueue.cancel=()=>({cost:50}),b=>b.friendlyQueue.step=()=>null]){const b=ground(make());mutate(b);assert.equal(flagRecoveryOptions(b).state,'unknown');}});
test('contract bound state reads actual hotbar membership, including other bars',()=>{const b=ground(make()),s=b.profile.skills.find(s=>s.id==='grunt');assert.equal(flagRecoveryOptions(b).options.find(o=>o.id==='grunt').bound,true);s.binding=-1;b.refreshHotbar();assert.equal(flagRecoveryOptions(b).options.find(o=>o.id==='grunt').bound,false);s.binding=29;b.refreshHotbar();assert.equal(flagRecoveryOptions(b).options.find(o=>o.id==='grunt').bound,true);});
test('ordinary late keyboard summon is prepaid before the exhausted-reserve check',()=>{const b=ground(make()),s=b.profile.skills.find(s=>s.id==='grunt');b.friendlyQueue.population=4;b.hotbar.bar=Math.floor(s.binding/10);b.input.digits=[s.binding%10];b.step();assert.equal(b.friendlyQueue.population,0);assert.equal(b.profile.gold,1180);assert.equal(b.friendlyQueue.queue.length,4);assert.equal(b.outcome,null);assert.equal(flagRecoveryOptions(b).reason,'recovery-arriving');});
test('low gold alone never proves loss while reserve can fund a currently owned contract',()=>{for(const mutate of [()=>{},b=>clearField(b),b=>{clearField(b);b.enemies.closeReserves();},b=>{clearField(b);b.enemies.closeReserves();b.badCastle.destroy();for(const t of b.structures.filter(t=>t.type==='tower'))t.destroy();}]){const b=ground(make());b.friendlyQueue.population=4;b.profile.gold=0;mutate(b);assert.equal(flagRecoveryOptions(b).state,'possible');b.step();assert.equal(b.outcome,null);}});
test('normal paid arrivals can restore a dropped home flag through actual troop AI',()=>{const b=ground(make()),s=b.profile.skills.find(s=>s.id==='grunt');clearField(b);b.enemies.closeReserves();b.ownFlag.x=700;b.ownFlag.y=b.elevationAt(700);b.friendlyQueue.population=4;b.hotbar.bar=Math.floor(s.binding/10);b.input.digits=[s.binding%10];b.step();b.input.digits=[];for(let i=0;i<10000&&b.ownFlag.status!==FS.AT_BASE;i++)b.step();assert.equal(b.outcome,null);assert.equal(b.ownFlag.status,FS.AT_BASE);assert.equal(b.friendlyQueue.population,0);assert.equal(b.profile.gold,1180);});
test('exhausted receipt is immutable, stable and exactly once after normal post-tick assessment',()=>{const events=[],b=ground(make(e=>events.push(e)));b.step();assert.equal(b.outcome,'defeat');assert.deepEqual(b.causewayDefeatCauses,['unrecoverable-home-flag']);assert.ok(Object.isFrozen(b.causewayDefeatCauses));assert.throws(()=>{b.causewayDefeatCauses=[];});b.ownFlag.status=FS.CAPTURED;b.hero.hp=0;b.goodCastle.hp=0;for(let n=0;n<110;n++)b.step();assert.equal(b.profile.defeats,1);assert.equal(events.filter(e=>e.type==='outcome').length,1);assert.equal(events.filter(e=>e.type==='summary').length,1);assert.match(causewayFeedbackState(b).reason,/stranded/);assert.doesNotMatch(causewayFeedbackState(b).reason,/captured|hero fell|keep fell/);});
for(const reverse of [false,true])test(`whole-tick mandatory losses win over final occupation, callback order reversed=${reverse}`,()=>{const b=make();holdFixture(b);const actions=[()=>b.hero.takeDamage(b.hero.hp),()=>{b.ownFlag.status=FS.CAPTURED;b.checkOutcome();},()=>b.goodCastle.takeDamage(b.goodCastle.hp)];if(reverse)actions.reverse();b.addObject({step(){for(const act of actions)act();}});b.step();assert.equal(b.outcome,'defeat');assert.equal(b.objectiveProgress.ticks,989);assert.deepEqual(b.causewayDefeatCauses,['hero','flag','keep']);});
test('spell-phase loss also beats final occupation and captures all simultaneous causes',()=>{const b=make();holdFixture(b);b.spells.push({step(){b.hero.takeDamage(b.hero.hp);b.goodCastle.takeDamage(b.goodCastle.hp);b.ownFlag.status=FS.CAPTURED;}});b.step();assert.equal(b.outcome,'defeat');assert.equal(b.objectiveProgress.ticks,989);assert.deepEqual(b.causewayDefeatCauses,['hero','flag','keep']);});
test('securing emits one truthful withdrawal count without touching deployed actors',()=>{const events=[],b=make(e=>events.push(e));b.hero.leaveGarrison();b.hero.x=1050;b.hero.y=b.elevationAt(1050);for(const u of b.badTeam){u.x=1600;u.y=b.elevationAt(1600);}b.setArmyOrder('rally','center','frontline');b.setArmyOrder('rally','rear','support');for(let n=0;n<989;n++){b.tick++;b.causewayObjective.afterTick();}const deployed=b.badTeam.map(u=>[u,u.hp]),reserve=b.enemies.remaining;b.step();assert.equal(b.objectiveProgress.secured,true);assert.equal(b.armyOrder.mode,'advance');assert.equal(b.enemies.remaining,0);assert.equal(b.enemies.withdrawn,reserve);assert.deepEqual(b.badTeam.map(u=>[u,u.hp]),deployed);const secured=events.filter(e=>e.type==='causeway-secured');assert.equal(secured.length,1);assert.equal(secured[0].withdrawn,reserve);assert.equal(events.filter(e=>e.type==='enemy-reserves-withdrawn').length,0);for(let n=0;n<5;n++)b.step();assert.equal(events.filter(e=>e.type==='causeway-secured').length,1);assert.equal(b.enemies.spawned+b.enemies.remaining+b.enemies.withdrawn,b.enemies.roster.length);});
test('early destroyed keep allows both companies until secured, then forbids Rally while cleanup remains',()=>{const b=make();b.setArmyOrder('rally','center','frontline');b.setArmyOrder('rally','rear','support');b.badCastle.takeDamage(b.badCastle.hp);assert.equal(b.armyOrder.mode,'split');assert.equal(rallyObjectiveAvailable(b),true);assert.equal(b.setArmyOrder('rally','forward','support'),true);b.hero.leaveGarrison();b.hero.x=1050;b.hero.y=b.elevationAt(1050);for(const u of b.badTeam){u.x=1600;u.y=b.elevationAt(1600);}for(let n=0;n<989;n++){b.tick++;b.causewayObjective.afterTick();}b.step();assert.equal(b.outcome,null);assert.equal(b.objectiveProgress.secured,true);assert.equal(b.armyOrder.mode,'advance');assert.equal(rallyObjectiveAvailable(b),false);assert.equal(b.setArmyOrder('rally','center','all'),false);});
for(const threat of ['scout','standard','veteran'])test(`${threat} opening preserves real constructor stats/prototypes and all finite tickets`,()=>{for(const biome of ['oaks','lowlands','pines','wasteland'])for(const seed of [1,42,4294967295]){const b=new SkirmishBattle({descriptor:descriptor(threat,biome,seed)});assert.equal(b.enemies.spawned,5);assert.equal(b.enemies.withdrawn,0);assert.equal(b.enemies.spawned+b.enemies.remaining,b.enemies.roster.length);assert.equal(b.enemies.roster.includes('gorath'),false);assert.equal(b.friendlyQueue.cap,threat==='veteran'?16:14);assert.equal(b.enemies.cap,threat==='veteran'?22:20);for(const u of b.badTeam){const stats=troopStats(u.type,{level:b.level,difficulty:b.profile.difficulty});assert.equal(u.hp,stats.maxHp);assert.equal(u.damage,stats.damage);assert.equal(u.speed,stats.speed);assert.equal(Object.getPrototypeOf(u),b.unitFactories[u.type].prototype);assert.equal(u.actionDuration,0);assert.ok(Number.isFinite(u.x)&&Number.isFinite(u.y));}}});

test('live and paused controls retain Rally after early keep loss, then disable it for secured cleanup',async t=>{
 const ui=await loadGameUI(t,{search:'?mode=skirmish&sk=SK1:16:oaks:scout:causeway'});ui.click('skirmishPrepare');ui.click('start');ui.frames();const b=ui.battle;b.badCastle.takeDamage(b.badCastle.hp);ui.frames();
 const live=ui.get('liveRallyPosition').querySelector('select');assert.equal(live.disabled,false);ui.dispatch(live,'pointerdown');live.value='center';ui.dispatch(live,'change');assert.equal(b.armyOrder.mode,'rally');assert.equal(b.armyOrder.position,'center');
 ui.click('battlePause');ui.click('openQueue');assert.equal(b.paused,true);const company=ui.get('armyOrders').querySelector('.army-company-select');company.value='support';ui.dispatch(company,'change');const rear=ui.get('armyOrders').querySelector('[data-rally-position="rear"]');assert.equal(rear.disabled,false);rear.click();assert.equal(b.armyOrder.mode,'split');assert.equal(b.armyOrder.groups.support.position,'rear');ui.click('closeQueue');ui.click('resumeGame');
 b.hero.leaveGarrison();b.hero.x=1050;b.hero.y=b.elevationAt(1050);for(const u of b.badTeam){u.x=1600;u.y=b.elevationAt(1600);}for(let n=0;n<989;n++){b.tick++;b.causewayObjective.afterTick();}ui.frames();assert.equal(b.objectiveProgress.secured,true);assert.equal(b.outcome,null);assert.equal(b.armyOrder.mode,'advance');assert.equal(live.disabled,true);assert.equal(ui.get('liveArmyOrder').disabled,true);const before=b.armyOrder;live.value='forward';ui.dispatch(live,'change');assert.deepEqual(b.armyOrder,before);
 ui.click('battlePause');ui.click('openQueue');assert.equal(rear.disabled,true);rear.click();assert.equal(b.armyOrder.mode,'advance');assert.match(ui.get('armyOrders').querySelector('.army-order-status').textContent,/line is released/);
});

test('unknown director, companion or skill producer behavior defers terminal proof',()=>{for(const mutate of [b=>b.enemies.step=()=>null,b=>b.companions.step=()=>{},b=>b.profile.skills[0].step=()=>{},b=>b.profile.skills[0].use=()=>true]){const b=ground(make());mutate(b);assert.equal(flagRecoveryOptions(b).state,'unknown');b.step();assert.equal(b.outcome,null);}});

for(const [name,mutate,expected] of [
 ['prepaid arrival',b=>b.friendlyQueue.queue.push({type:'grunt',cost:1}),/recovery squad is arriving/],
 ['unbound owned contract',b=>{b.friendlyQueue.population=4;for(const s of b.profile.skills.filter(s=>['grunt','mount'].includes(s.id)))s.binding=-1;b.refreshHotbar();},/Equip Grunt in Loadout/],
 ['cooling equipped contract',b=>{b.friendlyQueue.population=4;for(const s of b.profile.skills.filter(s=>['grunt','mount'].includes(s.id)))s.cooldown=198;},/Wait for Grunt to reload/],
 ['refundable nonrecoverer',b=>{b.friendlyQueue.population=1;b.friendlyQueue.queue.push({type:'fireDragon',cost:3});},/refund up to 3 reserve/],
 ['gold deficit',b=>{b.friendlyQueue.population=4;b.profile.gold=7;},/Need 13 more gold for a Grunt/],
])test(`existing objective brief explains ${name} without changing resources or cooldowns`,()=>{const b=ground(make());mutate(b);const before=JSON.stringify([b.tick,b.friendlyQueue,b.profile.skills,b.profile.gold]);const f=causewayFeedbackState(b);assert.match(f.brief,expected);assert.equal(f.status,'Recover home flag');for(let i=0;i<30;i++)causewayFeedbackState(b);assert.equal(JSON.stringify([b.tick,b.friendlyQueue,b.profile.skills,b.profile.gold]),before);});
test('keep-withdrawal copy states Causeway completion rules and preserves ordinary doctrine copy',async t=>{for(const doctrine of ['causeway','vanguard']){const ui=await loadGameUI(t,{search:`?mode=skirmish&sk=SK1:16:oaks:scout:${doctrine}`});ui.click('skirmishPrepare');ui.click('start');ui.frames();ui.battle.createUnit('grunt');ui.battle.badCastle.takeDamage(ui.battle.badCastle.hp);const text=ui.get('battleStatus').textContent;if(doctrine==='causeway'){assert.match(text,/Secure the causeway, clear the deployed army and restore your home flag/);assert.doesNotMatch(text,/capture their flag/);}else assert.match(text,/Defeat the remaining army or capture their flag/);}});

test('a displaced home flag takes display priority after secured progress is latched',()=>{const b=make();b.hero.leaveGarrison();b.hero.x=1050;b.hero.y=b.elevationAt(1050);for(const u of b.badTeam){u.x=1600;u.y=b.elevationAt(1600);}for(let n=0;n<990;n++){b.tick++;b.causewayObjective.afterTick();}assert.equal(b.objectiveProgress.phase,'cleanup');b.ownFlag.status=FS.GROUNDED;b.ownFlag.x=1400;b.ownFlag.y=b.elevationAt(1400);assert.equal(b.objectiveProgress.phase,'recover-flag');assert.equal(b.objectiveProgress.secured,true);assert.equal(b.objectiveProgress.ticks,990);assert.equal(causewayFeedbackState(b).status,'Recover home flag');assert.match(causewayFeedbackState(b).brief,/Recruit Grunt/);});

test('guidance requires refund when the only currently affordable recovery contract needs it',()=>{const b=ground(make());b.profile.addSkill('tallGrunt');b.refreshHotbar();b.friendlyQueue.population=3;b.profile.gold=20;b.friendlyQueue.queue.push({type:'archer',cost:1});assert.match(causewayFeedbackState(b).brief,/Cancel queued units in Army to refund up to 1 reserve/);});

test('registered Causeway direct-destroy keep extends Rally only until occupation completes',()=>{const b=make();b.setArmyOrder('rally','center','all');b.badCastle.destroy();assert.ok(b.badCastle.hp>0);assert.equal(b.badCastle.destroyed,true);assert.equal(rallyObjectiveAvailable(b),true);b.hero.leaveGarrison();b.hero.x=1050;b.hero.y=b.elevationAt(1050);for(const u of b.badTeam){u.x=1600;u.y=b.elevationAt(1600);}for(let n=0;n<989;n++){b.tick++;b.causewayObjective.afterTick();}b.step();assert.equal(b.objectiveProgress.secured,true);assert.equal(b.outcome,null);assert.ok(b.badTeam.length>0);assert.equal(rallyObjectiveAvailable(b),false);assert.equal(b.setArmyOrder('rally','center'),false);assert.equal(b.armyOrder.mode,'advance');});
test('ordinary HP-only keep behavior survives, and forged Causeway metadata grants no exception',()=>{const b=new CampaignBattle();b.createUnit('grunt');b.causewayObjective={needsOccupation:true};b.badCastle.destroy();assert.equal(b.badCastle.destroyed,true);assert.ok(b.badCastle.hp>0);assert.equal(rallyObjectiveAvailable(b),true);assert.equal(b.setArmyOrder('rally','center'),true);b.badCastle.hp=0;assert.equal(rallyObjectiveAvailable(b),false);assert.equal(b.setArmyOrder('rally','center'),false);});
test('live toggle, live selector and paused controls share the engine finite-hero guard',async t=>{const ui=await loadGameUI(t,{search:'?mode=skirmish&sk=SK1:16:oaks:scout:causeway'});ui.click('skirmishPrepare');ui.click('start');ui.frames();const b=ui.battle;b.hero.x=NaN;ui.frames();assert.equal(b.setArmyOrder('rally','center'),false);assert.equal(ui.get('liveArmyOrder').disabled,true);const live=ui.get('liveRallyPosition').querySelector('select');assert.equal(live.disabled,true);live.value='center';ui.dispatch(live,'change');assert.equal(b.armyOrder.mode,'advance');ui.click('battlePause');ui.click('openQueue');const buttons=ui.get('armyOrders').querySelectorAll('[data-rally-position]');assert.ok(buttons.every(button=>button.disabled));for(const button of buttons)button.click();assert.equal(b.armyOrder.mode,'advance');});
