import test from 'node:test';import assert from 'node:assert/strict';
import {CampaignProfiles} from '../site/dist/engine/profile-manager.mjs';import {CampaignBattle} from '../site/dist/engine/first-battle.mjs';
import {createLocalCampaignStore,snapshotCampaign,checkpointSlotKey} from '../site/dist/local-campaign-store.mjs';
import {MemoryStorage,TestLocks} from './helpers/local-storage.mjs';
const fixture=()=>{const profiles=new CampaignProfiles({defaultName:'Older tab'});return snapshotCampaign({profiles,battle:new CampaignBattle({profile:profiles.active})});};
const setup=async()=>{const storage=new MemoryStorage(),store=createLocalCampaignStore({storage,locks:new TestLocks(),now:()=>1,id:()=>'test'}),payload=fixture();const first=await store.write(1,payload);return {storage,store,payload,first};};
for(const schema of ['castledecks-local-checkpoint-2','castledecks-local-checkpoint-99','castledecks-local-checkpoint-999999999999999999999999999'])test(`older reader preserves and blocks ${schema} beside valid older recovery bank`,async()=>{const {storage,store,payload,first}=await setup(),future={...JSON.parse(first.expected[0]),schema,revision:2,payload:{...payload,unknownFutureField:{keep:true}}};storage.setItem(checkpointSlotKey(1,'b'),JSON.stringify(future));const before=[...storage.data],read=store.read(1);assert.equal(read.status,'newer');assert.equal(read.latest,null);assert.equal(read.previous,null);assert.deepEqual(read.newer,['b']);assert.match(read.message,/newer game version.*Reload.*Both checkpoint copies.*Export/);assert.equal((await store.write(1,payload,{expected:read.raw})).code,'newer-version');assert.equal((await store.write(1,payload,{expected:first.expected})).code,'newer-version');assert.equal((await store.write(1,payload)).code,'newer-version');assert.equal((await store.remove(1,{expected:read.raw,confirmed:true})).code,'newer-version');assert.deepEqual([...storage.data],before);});
test('future bank blocks even when it is older revision, incomplete payload or only one bank',async()=>{const {storage,store,payload}=await setup();storage.setItem(checkpointSlotKey(1,'a'),'{"schema":"castledecks-local-checkpoint-2"}');const before=[...storage.data];assert.equal(store.read(1).status,'newer');assert.equal((await store.write(1,payload,{expected:store.read(1).raw})).code,'newer-version');assert.deepEqual([...storage.data],before);});
test('ordinary corruption still offers valid previous recovery and another slot remains writable',async()=>{const {storage,store,payload,first}=await setup();storage.setItem(checkpointSlotKey(1,'b'),'{broken');assert.equal(store.read(1).status,'recovered');assert.ok(store.read(1).latest);storage.setItem(checkpointSlotKey(1,'b'),'{"schema":"castledecks-local-checkpoint-2"}');assert.equal((await store.write(2,payload)).ok,true);assert.equal(store.read(1).status,'newer');assert.equal(store.read(2).latest.schema,'castledecks-local-checkpoint-1');});
