import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {createUploadJournal,UPLOAD_JOURNAL_KEY} from '../site/dist/cloud-upload-journal.mjs';import {createCloudAccountModel} from '../site/dist/cloud-account-model.mjs';import {createCloudGameBridge} from '../site/dist/cloud-game-bridge.mjs';import {mountCloudAccountPanel} from '../site/dist/cloud-account-panel.mjs';import {createGameSaveCodecs} from '../site/dist/cloud-save-codecs.mjs';
import {parseLocalCheckpoint} from '../site/dist/local-campaign-store.mjs';import {restoreExpeditions} from '../site/dist/expedition-model.mjs';import {parseDeckCode} from '../site/dist/deck-presets-model.mjs';
const docs=Object.fromEntries(['decks','crownroad','wayfarer'].map(kind=>[kind,readFileSync(new URL(`./cloud-fixtures/${kind}.json`,import.meta.url),'utf8')]));
const validate=createGameSaveCodecs({parseLocalCheckpoint,restoreExpeditions,parseDeckCode}).validate;
const memory=()=>{const values=new Map();return {getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,String(value)),removeItem:key=>values.delete(key),values};};
const deferred=()=>{let resolve;const promise=new Promise(r=>{resolve=r;});return {promise,resolve};};
const note=()=>({schema:'castledecks-cloud-upload-1',accountID:'a',kind:'decks',slot:1,expectedRevision:1,document:docs.decks,createdAt:1});
const record=(kind='decks',revision=2)=>({kind,slot:1,revision,updatedAt:1,trust:'client-reported',document:docs[kind]});
function harness({enabled=true,storage=memory(),pending=null}={}){
 const profile={},host={profiles:{active:profile},battle:{summary:null},destination:'campaign',temporarySession:false,loadGeneration:0,localReviewIntent:0,started:false};let captures={...docs};const restores=[];
 const bridge=createCloudGameBridge({getState:()=>host,captureDocument:kind=>captures[kind],validateDocument:validate,reviewCrownroad:(document,parsed)=>{restores.push(['crownroad',document,parsed]);return {staged:true};},replaceWayfarer:(document,parsed)=>restores.push(['wayfarer',document,parsed]),reviewDecks:(document,parsed)=>{restores.push(['decks',document,parsed]);return {staged:true};}});
 const journal=createUploadJournal({storage,validateDocument:validate});if(pending)journal.save(pending);
 const remote={account:'a',save:null,slots:[],upload:null,downloads:0,uploads:0};
 const client={async account(){if(!remote.account){const e=new Error('sign-in-required');e.status=401;throw e;}return {id:remote.account,expiresAt:1900000000};},async list(){return remote.slots;},async download(){remote.downloads++;return typeof remote.save==='function'?remote.save():remote.save;},async upload(kind,slot,document,expected){remote.uploads++;if(remote.upload)return remote.upload();remote.save={...record(kind,expected+1),slot,document};return remote.save;},async login(){return 'https://accounts.google.com/o/oauth2/v2/auth?state=synthetic';},async logout(){remote.account=null;}};
 const model=createCloudAccountModel({client,bridge,journal,enabled,now:()=>1});return {model,client,bridge,journal,storage,host,remote,restores,captures};
}
test('disabled model and panel make no requests or visible controls',async()=>{const h=harness({enabled:false});h.client.account=()=>{throw new Error('must not request')};await h.model.refresh();assert.equal(h.model.snapshot().phase,'disabled');const root=new Element('section');mountCloudAccountPanel({root,document,model:h.model,enabled:false});assert.equal(root.hidden,true);assert.equal(root.children.length,0);});
test('journal round-trip contains no credentials and survives reconstruction',()=>{const s=memory(),j=createUploadJournal({storage:s,validateDocument:validate});j.save(note());assert.deepEqual(createUploadJournal({storage:s,validateDocument:validate}).read().pending,note());assert.deepEqual(Object.keys(JSON.parse(s.getItem(UPLOAD_JOURNAL_KEY))),Object.keys(note()));j.clear(note());assert.equal(s.getItem(UPLOAD_JOURNAL_KEY),null);});
test('future/unreadable journal is retained and blocks uploads',async()=>{for(const raw of ['{','{"schema":"future"}']){const s=memory();s.setItem(UPLOAD_JOURNAL_KEY,raw);const h=harness({storage:s});assert.equal(h.model.snapshot().blocked,true);await assert.rejects(h.model.prepareUpload('decks',1));assert.equal(s.getItem(UPLOAD_JOURNAL_KEY),raw);assert.equal(h.remote.uploads,0);}});
test('quota/readback failure prevents dispatch',async()=>{const s=memory();s.setItem=()=>{throw new Error('quota')};const h=harness({storage:s});await h.model.prepareUpload('decks',1);await h.model.confirm();assert.equal(h.remote.uploads,0);assert.equal(h.model.snapshot().phase,'error');});
test('review and confirmation upload captured bytes exactly once',async()=>{const h=harness();await h.model.prepareUpload('decks',1);assert.equal(h.remote.uploads,0);assert.equal(h.model.snapshot().review.expectedRevision,0);await h.model.confirm();assert.equal(h.remote.uploads,1);assert.equal(h.model.snapshot().pending,null);assert.equal(h.storage.getItem(UPLOAD_JOURNAL_KEY),null);});
test('uncertain write retains journal and never retries',async()=>{const h=harness();h.remote.upload=async()=>{const e=new Error('write-unverified');e.uncertain=true;throw e;};await h.model.prepareUpload('decks',1);await h.model.confirm();assert.equal(h.model.snapshot().phase,'uncertain');assert.ok(h.journal.read().pending);await h.model.reconcile();assert.equal(h.remote.uploads,1);assert.ok(h.model.snapshot().pending);await assert.rejects(h.model.prepareUpload('decks',2));});
test('definitive conflict clears only its own journal',async()=>{const h=harness();h.remote.upload=async()=>{const e=new Error('revision-conflict');e.status=409;throw e;};await h.model.prepareUpload('decks',1);await h.model.confirm();assert.equal(h.model.snapshot().pending,null);assert.equal(h.journal.read().pending,null);});
test('journal-clear failure after committed upload stays uncertain',async()=>{const h=harness();h.storage.removeItem=()=>{throw new Error('storage blocked')};await h.model.prepareUpload('decks',1);await h.model.confirm();assert.equal(h.remote.uploads,1);assert.equal(h.model.snapshot().phase,'uncertain');assert.ok(h.model.snapshot().pending);});
for(const key of ['loadGeneration','localReviewIntent','temporarySession','profile','document'])test(`newer ${key} prevents delayed cloud restore`,async()=>{const h=harness();h.remote.save=record();await h.model.prepareRestore('decks',1);const held=deferred();h.remote.save=()=>held.promise;const pending=h.model.confirm();await Promise.resolve();if(key==='temporarySession')h.host.temporarySession=true;else if(key==='profile')h.host.profiles.active={};else if(key==='document')h.captures.decks=docs.decks.replace('Synthetic QA','Changed QA');else h.host[key]++;held.resolve(record());await pending;assert.equal(h.restores.length,0);});
test('transient practice enter/return invalidates old work through monotonic host intent',async()=>{const h=harness();h.remote.save=record();await h.model.prepareRestore('decks',1);h.host.temporarySession=true;h.host.loadGeneration++;h.host.temporarySession=false;h.host.loadGeneration++;await h.model.confirm();assert.equal(h.restores.length,0);});
test('temporary sessions and live unsettled fields block upload and restore',async()=>{const h=harness();h.host.temporarySession=true;assert.deepEqual(h.bridge.kinds(),[]);await assert.rejects(h.model.prepareUpload('decks',1));await assert.rejects(h.model.prepareRestore('decks',1));h.host.temporarySession=false;h.host.started=true;assert.deepEqual(h.bridge.kinds(),[]);assert.equal(h.remote.uploads,0);});
test('Crownroad and deck restore stage native review without replacement',async()=>{for(const kind of ['crownroad','decks']){const h=harness();h.remote.save=record(kind);await h.model.prepareRestore(kind,1);assert.equal(h.restores.length,0);await h.model.confirm();assert.equal(h.restores[0][0],kind);assert.match(h.model.snapshot().message,/staged import review/);}});
test('Wayfarer preview truthfully names immediate replacement effect',async()=>{const h=harness();h.host.destination='expedition';h.remote.save=record('wayfarer');await h.model.prepareRestore('wayfarer',1);assert.match(h.model.snapshot().message,/Replace the current charter session/);assert.equal(h.restores.length,0);await h.model.confirm();assert.equal(h.restores[0][0],'wayfarer');assert.match(h.model.snapshot().message,/was replaced/);});
test('changed remote revision invalidates restore confirmation',async()=>{const h=harness();h.remote.save=record();await h.model.prepareRestore('decks',1);h.remote.save=record('decks',3);await h.model.confirm();assert.equal(h.restores.length,0);assert.match(h.model.snapshot().message,/cloud slot changed/);});
test('account A uncertain, B metadata, A unchanged, A verified clears stale slots immediately',async()=>{const h=harness({pending:note()});h.remote.account='b';h.remote.slots=[{...record('decks'),slot:2}];await h.model.refresh();assert.equal(h.model.snapshot().slots[0].slot,2);h.remote.account='a';h.remote.save=record('decks',1);await h.model.reconcile();assert.deepEqual(h.model.snapshot().slots,[]);assert.ok(h.model.snapshot().pending);h.remote.save=record('decks',2);await h.model.reconcile();assert.deepEqual(h.model.snapshot().slots.map(x=>x.slot),[1]);assert.equal(h.model.snapshot().pending,null);});
test('pending upload survives sign-out and reauthentication without retry',async()=>{const h=harness({pending:note()});h.remote.account='b';await h.model.reconcile();await h.model.logout();assert.equal(h.model.snapshot().account,null);assert.ok(h.model.snapshot().pending);await h.model.login();assert.ok(h.model.snapshot().loginURL);h.remote.account='a';h.remote.save=record();await h.model.reconcile();assert.equal(h.model.snapshot().pending,null);assert.equal(h.remote.uploads,0);});
test('leave during dispatched upload retains recovery even after success',async()=>{const h=harness();const held=deferred();h.remote.upload=()=>held.promise;await h.model.prepareUpload('decks',1);const pending=h.model.confirm();await Promise.resolve();h.model.leave();held.resolve(record('decks',1));await pending;assert.ok(h.model.snapshot().pending);assert.equal(h.model.snapshot().loginURL,'');});
class Element{constructor(tag){this.tagName=tag;this.children=[];this.value='';this.hidden=false;this.className='';this.attrs={};}append(...children){this.children.push(...children);}replaceChildren(...children){this.children=[...children];}setAttribute(key,value){this.attrs[key]=value;}removeAttribute(key){delete this.attrs[key];if(key==='href')delete this.href;}find(text){return this.children.flatMap(child=>[child,...child.children]).find(x=>x.textContent===text);}}
const document={createElement:tag=>new Element(tag)};
test('expired session plus pending note exposes sign-in in real panel module',async()=>{const h=harness({pending:note()});h.remote.account=null;const root=new Element('section');mountCloudAccountPanel({root,document,model:h.model,enabled:true});await h.model.refresh();assert.equal(h.model.snapshot().phase,'uncertain');assert.equal(root.find('Prepare Google sign-in').hidden,false);await h.model.login();const link=root.find('Open Google in a separate tab');assert.equal(link.target,'_blank');assert.equal(link.rel,'noopener noreferrer');assert.equal(link.hidden,false);h.model.leave();assert.equal(link.hidden,true);assert.equal(link.href,undefined);});
test('Decks selection survives destination change while option list refreshes',async()=>{const h=harness();const root=new Element('section');mountCloudAccountPanel({root,document,model:h.model,enabled:true});const kind=root.children.find(x=>x.tagName==='select');kind.value='decks';h.host.destination='expedition';await h.model.refresh();assert.equal(kind.value,'decks');assert.deepEqual(kind.children.map(x=>x.value),['wayfarer','decks']);h.host.destination='campaign';await h.model.refresh();assert.deepEqual(kind.children.map(x=>x.value),['crownroad','decks']);});
test('preparing another login clears previous one-shot link immediately',async()=>{const h=harness();await h.model.login();const held=deferred();h.client.login=()=>held.promise;const pending=h.model.login();assert.equal(h.model.snapshot().loginURL,'');held.resolve('https://accounts.google.com/o/oauth2/v2/auth?state=new');await pending;assert.match(h.model.snapshot().loginURL,/state=new/);});
