import {readFileSync} from 'node:fs';
import test from 'node:test';import assert from 'node:assert/strict';
import {loadGameUI,deferredFile} from './helpers/game-ui-harness.mjs';
import {CampaignProfiles} from '../site/dist/engine/profile-manager.mjs';
import {serializeProfile,PlayerProfile} from '../site/dist/engine/progression.mjs';
import {CampaignBattle} from '../site/dist/engine/first-battle.mjs';
import {snapshotCampaign,parseLocalCheckpoint,createLocalCampaignStore} from '../site/dist/local-campaign-store.mjs';
import {createProfileDecks,captureDeck,exportDeckCode} from '../site/dist/deck-presets-model.mjs';
import {ExpeditionProfiles} from '../site/dist/expedition-model.mjs';
import {TestLocks} from './helpers/local-storage.mjs';
class Storage{data=new Map();getItem(k){return this.data.get(k)??null;}setItem(k,v){this.data.set(k,String(v));}removeItem(k){this.data.delete(k);}}
function checkpoint(name='Cloud second') {const a=new PlayerProfile('Cloud first'),b=new PlayerProfile(name);b.gold=4321;b.highestLevel=4;b.cheated=true;const profiles=new CampaignProfiles({profiles:[a,b]});profiles.select(1);const decks=createProfileDecks();decks.set(b,[captureDeck(b,'Cloud bow')]);const payload=snapshotCampaign({profiles,battle:new CampaignBattle({profile:b,level:4}),deckPresets:decks.snapshot(profiles)});return JSON.stringify({schema:'castledecks-local-checkpoint-3',revision:3,writtenAt:123,transaction:'test',reason:'ready',payload});}
const response=(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{'content-type':'application/json'}});
function server(document=checkpoint()){let identity='account-A',revision=1,hold=null,downloads=0,uncertain=false;const requests=[];return {requests,uncertainUpload(){uncertain=true;},get downloads(){return downloads;},setIdentity(v){identity=v;},holdDownload(){let resolve;const promise=new Promise(r=>resolve=r);hold={promise,resolve};return hold;},async fetch(path,options){requests.push({path,options});if(path==='/api/health')return response({accountsEnabled:true});if(path==='/api/account'&&!identity)return response({},401);if(path==='/api/account')return response({id:identity,csrfToken:'x'.repeat(43),expiresAt:Date.now()+100000});if(path==='/api/saves')return response({saves:[]});if(path==='/api/auth/google/start')return response({url:'https://accounts.google.com/o/oauth2/v2/auth?state=synthetic'});if(path==='/api/auth/logout')return new Response(null,{status:204});if(path.startsWith('/api/saves/')){const [kind,slot]=path.split('/').slice(-2);if(options.method==='PUT'){document=JSON.parse(options.body).document;revision++;if(uncertain){uncertain=false;return response({},502);}}else{downloads++;if(hold){const pending=hold;hold=null;await pending.promise;}}return response({kind,slot:Number(slot),revision,updatedAt:123,trust:'client-reported',document});}throw new Error(path);}};}
async function mounted(t,{document,search='',storage=new Storage(),backend=server(document)}={}){const ui=await loadGameUI(t,{search,storage,accounts:true,fetch:backend.fetch.bind(backend)});ui.click('introSave');await ui.settle();ui.click('cloud-refresh');await ui.settle();return {ui,backend,storage};}
async function preview(ui,kind='crownroad'){ui.get('cloud-kind').value=kind;ui.click('cloud-restore');await ui.settle();assert.equal(ui.get('cloud-confirm').hidden,false,ui.get('cloud-status').textContent);}

test('off by default makes zero account requests and keeps guest campaign usable',async t=>{let calls=0;const ui=await loadGameUI(t,{storage:new Storage(),fetch:()=>{calls++;throw Error();}});ui.click('introSave');await ui.settle();assert.equal(calls,0);assert.equal(ui.get('cloudAccounts').hidden,true);assert.equal(ui.get('openCloudAccounts').hidden,true);ui.click('showSaveCode');assert.ok(ui.get('saveCode').value);});
test('missing backend does not interrupt guest save or start',async t=>{const ui=await loadGameUI(t,{storage:new Storage(),accounts:true,fetch:async()=>new Response('static',{status:404})});ui.click('introSave');await ui.settle();assert.equal(ui.get('cloudAccounts').hidden,false);assert.match(ui.get('cloud-status').textContent,/unavailable.*local play still work/);assert.equal(ui.get('cloud-retry').hidden,false);ui.click('showSaveCode');assert.ok(ui.get('saveCode').value);ui.click('closeSave');ui.click('start');assert.equal(ui.visible('intro'),false);});
test('cloud full checkpoint requires native confirmation and preserves selection, provenance, decks and existing slot',async t=>{const {ui,storage}=await mounted(t),store=createLocalCampaignStore({storage,locks:new TestLocks()}),before=store.read(1).raw,original=ui.battle;await preview(ui);ui.click('cloud-confirm');await ui.settle();assert.equal(ui.battle,original);assert.equal(ui.visible('localConfirm'),true);ui.click('localConfirmAccept');await ui.settle();assert.equal(ui.battle.profile.name,'Cloud second');assert.equal(ui.battle.profile.cheated,true);assert.equal(ui.battle.profile.gold,4321);const restored=store.read(2).latest;assert.equal(restored.payload.activeIndex,1);assert.deepEqual(restored.payload.deckPresets,parseLocalCheckpoint(checkpoint()).payload.deckPresets);assert.deepEqual(store.read(1).raw,before);});
test('cancel and session-only cloud checkpoint leave local slots intact',async t=>{const {ui,storage}=await mounted(t),before=[...storage.data],original=ui.battle;await preview(ui);ui.click('cloud-confirm');await ui.settle();ui.click('localConfirmCancel');assert.equal(ui.battle,original);await preview(ui);ui.click('cloud-confirm');await ui.settle();ui.click('localImportSession');await ui.settle();assert.equal(ui.battle.profile.name,'Cloud second');assert.deepEqual([...storage.data],before);});
test('new local code intent wins over held cloud confirmation',async t=>{const {ui,backend}=await mounted(t);await preview(ui);const hold=backend.holdDownload();ui.click('cloud-confirm');await ui.settle();ui.get('loadCode').value=new CampaignProfiles({defaultName:'New local choice'}).exportBundle();ui.click('importCode');await ui.settle();hold.resolve();await ui.settle();assert.match(ui.get('localConfirmText').textContent,/New local choice/);assert.doesNotMatch(ui.get('localConfirmText').textContent,/Cloud second/);ui.click('localConfirmAccept');await ui.settle();assert.equal(ui.battle.profile.name,'New local choice');});
test('new local file intent wins even before its file contents arrive',async t=>{const {ui,backend}=await mounted(t);await preview(ui);const hold=backend.holdDownload();ui.click('cloud-confirm');await ui.settle();const file=deferredFile(),loading=ui.load(file.file);hold.resolve();await ui.settle();assert.equal(ui.visible('localConfirm'),false);file.resolve(new CampaignProfiles({defaultName:'File choice'}).exportBundle());await loading;assert.match(ui.get('localConfirmText').textContent,/File choice/);});
test('new local-slot choice wins over held cloud confirmation',async t=>{const {ui,backend}=await mounted(t);await preview(ui);const hold=backend.holdDownload();ui.click('cloud-confirm');await ui.settle();ui.click('localNewVault');hold.resolve();await ui.settle();assert.match(ui.get('localConfirmText').textContent,/Start a new campaign/);});
test('close cancels delayed restore and reopening never stages the old choice',async t=>{const {ui,backend}=await mounted(t);await preview(ui);const original=ui.battle,hold=backend.holdDownload();ui.click('cloud-confirm');await ui.settle();ui.click('closeSave');hold.resolve();await ui.settle();ui.click('introSave');await ui.settle();assert.equal(ui.battle,original);assert.equal(ui.visible('localConfirm'),false);assert.equal(ui.get('cloud-confirm').hidden,true);});
test('changed account during confirmation cannot stage a restore',async t=>{const {ui,backend}=await mounted(t);await preview(ui);backend.setIdentity('account-B');ui.click('cloud-confirm');await ui.settle();assert.equal(ui.visible('localConfirm'),false);assert.match(ui.get('cloud-status').textContent,/account changed/);});
test('upload is explicit and uses full current checkpoint without local mutation',async t=>{const {ui,backend,storage}=await mounted(t),before=[...storage.data];ui.click('cloud-upload');await ui.settle();assert.equal(backend.requests.some(x=>x.options.method==='PUT'),false);ui.click('cloud-confirm');await ui.settle();const put=backend.requests.find(x=>x.options.method==='PUT');assert.ok(put);const doc=JSON.parse(put.options.body).document;assert.equal(parseLocalCheckpoint(doc).manager.active.name,'Castledecks');assert.deepEqual([...storage.data],before);});
test('deck restore stages native add review and never equips or unlocks',async t=>{const p=new PlayerProfile('Deck'),document=exportDeckCode([captureDeck(p,'Imported cloud bow')]),{ui}=await mounted(t,{document}),before=serializeProfile(ui.battle.profile);await preview(ui,'decks');ui.click('cloud-confirm');await ui.settle();assert.equal(ui.visible('deckConfirm'),true);assert.equal(ui.visible('skillsPanel'),true);assert.equal(serializeProfile(ui.battle.profile),before);ui.click('deckConfirmAccept');await ui.settle();assert.equal(serializeProfile(ui.battle.profile),before);assert.match(ui.get('deckList').textContent,/Imported cloud bow/);});
test('Wayfarer restore states immediate replacement and keeps Crownroad local saves',async t=>{const profiles=new ExpeditionProfiles(),storage=new Storage(),{ui}=await mounted(t,{document:profiles.exportBundle(),search:'?mode=expedition',storage}),before=[...storage.data],original=ui.battle;await preview(ui,'wayfarer');assert.equal(ui.get('cloud-confirm').textContent,'Replace this charter session');assert.equal(ui.battle,original);ui.click('cloud-confirm');await ui.settle();assert.notEqual(ui.battle,original);assert.equal(ui.battle.profile.name,profiles.active.name);assert.deepEqual([...storage.data],before);});
test('trial entry and return without an animation frame invalidate pending cloud restore',async t=>{const {ui,backend}=await mounted(t);await preview(ui);const hold=backend.holdDownload();ui.click('cloud-confirm');await ui.settle();const original=ui.battle;ui.click('closeSave');ui.click('introArmory');ui.click('shopCatalogTab');ui.get('shopSearch').value='Grunt';ui.dispatch(ui.get('shopSearch'),'input');ui.dispatch(ui.get('shopSearchForm'),'submit');ui.click('inspect-grunt');ui.click('shopTryCard');assert.notEqual(ui.battle,original);ui.click('introSettings');assert.equal(ui.get('openCloudAccounts').hidden,true);ui.click('closeSettings');ui.click('introArmory');hold.resolve();await ui.settle();ui.frames();assert.equal(ui.visible('localConfirm'),false);assert.equal(ui.battle,original);});
test('active campaign field disables cloud actions even when paused in Saves',async t=>{const {ui}=await mounted(t);ui.click('closeSave');ui.click('start');ui.frames(3);ui.click('battlePause');ui.click('saveGame');await ui.settle();assert.equal(ui.get('cloud-upload').disabled,true);assert.equal(ui.get('cloud-restore').disabled,true);});
test('Settings entry opens the same Saves workspace and preserves local chooser',async t=>{const backend=server(),ui=await loadGameUI(t,{search:'?continue=1',storage:new Storage(),accounts:true,fetch:backend.fetch.bind(backend)});ui.click('introSettings');ui.click('openCloudAccounts');await ui.settle();assert.equal(ui.visible('savePanel'),true);assert.equal(ui.get('cloudAccounts').hidden,false);assert.ok(ui.get('localNewVault'));});
test('unknown upload remains recoverable through expired session and new-tab reauthentication',async t=>{const {ui,backend,storage}=await mounted(t);ui.click('cloud-upload');await ui.settle();backend.uncertainUpload();ui.click('cloud-confirm');await ui.settle();assert.match(ui.get('cloud-status').textContent,/may have committed/);const note=storage.getItem('castledecks:cloud:pending-upload:v1');assert.ok(note);backend.setIdentity(null);ui.click('cloud-reconcile');await ui.settle();assert.equal(ui.get('cloud-login').hidden,false);assert.equal(ui.get('cloud-upload').disabled,true);ui.click('cloud-login');await ui.settle();assert.equal(ui.get('cloud-link').target,'_blank');assert.equal(ui.get('cloud-link').rel,'noopener noreferrer');assert.equal(ui.get('cloud-link').hidden,false);assert.equal(storage.getItem('castledecks:cloud:pending-upload:v1'),note);backend.setIdentity('account-A');ui.click('cloud-reconcile');await ui.settle();assert.match(ui.get('cloud-status').textContent,/matches/);assert.equal(storage.getItem('castledecks:cloud:pending-upload:v1'),null);assert.equal(backend.requests.filter(r=>r.options.method==='PUT').length,1);});
test('full local slots allow cloud session-only import without overwriting a slot',async t=>{const storage=new Storage(),store=createLocalCampaignStore({storage,locks:new TestLocks()}),parsed=parseLocalCheckpoint(checkpoint('Kept'));for(let slot=1;slot<=3;slot++)await store.write(slot,parsed.payload);const before=[...storage.data],{ui}=await mounted(t,{storage});await preview(ui);ui.click('cloud-confirm');await ui.settle();assert.equal(ui.get('localConfirmAccept').disabled,true);ui.click('localImportSession');await ui.settle();assert.equal(ui.battle.profile.name,'Cloud second');assert.deepEqual([...storage.data],before);});

test('direct local Saves entry mounts optional controls without creating a campaign',async t=>{const storage=new Storage(),backend=server(),ui=await loadGameUI(t,{search:'?open=local-saves',storage,accounts:true,fetch:backend.fetch.bind(backend)});await ui.settle();assert.equal(ui.visible('savePanel'),true);assert.equal(ui.get('cloudAccounts').hidden,false);assert.equal(ui.visible('localHubChoices'),true);assert.equal(storage.data.size,0);ui.click('showSaveCode');assert.ok(ui.get('saveCode').value);});

test('dormant root and Settings entry stay hidden against shared button display rules',()=>{const css=readFileSync(new URL('../site/dist/cloud-account.css',import.meta.url),'utf8');assert.match(css,/#cloudAccounts\[hidden\],#openCloudAccounts\[hidden\]\{display:none!important\}/);});
