import test from 'node:test';
import assert from 'node:assert/strict';
import {loadGameUI} from './helpers/game-ui-harness.mjs';
import {MemoryStorage,settle} from './helpers/local-storage.mjs';
import {exportDeckCode,parseDeckCode,captureDeck} from '../site/dist/deck-presets-model.mjs';
import {CONTROL_STORAGE_KEY,DEFAULT_CONTROL_BINDINGS} from '../site/dist/control-bindings.mjs';
const empty=(name='No bow')=>({name,slots:Array(30).fill(null),companion:null});
const save=(ui,name)=>{ui.get('deckNewName').value=name;ui.dispatch(ui.get('deckSaveForm'),'submit');};
const books=ui=>{ui.click('deckShowExport');return parseDeckCode(ui.get('deckExportCode').value);};
const prepare=(ui,d)=>{ui.get('deckImportCode').value=exportDeckCode([d]);ui.click('deckImportPrepare');ui.click('deckConfirmAccept');};
const switchTo=(ui,id)=>{ui.get('hubDestinations').querySelector(`[data-hub-destination="${id}"]`).click();ui.click('start');if(ui.visible('switchSessionConfirm'))ui.click('confirmSessionSwitch');ui.frames();};
const open=ui=>{ui.click(ui.visible('intro')?'introLoadout':'pauseSkills');ui.click('openDeckPresets');};
const close=ui=>{ui.click('closeDeckPresets');ui.click('closeSkills');};
const checkpointBytes=storage=>[...storage.data].filter(([key])=>key.startsWith('castledecks:campaign:checkpoint:'));
const snapshot=b=>JSON.stringify({tick:b.tick,profile:b.profile,stats:b.stats,queue:b.friendlyQueue.queue,units:[...b.goodTeam,...b.badTeam].map(u=>[u.type,u.x,u.y,u.hp]),shots:b.projectiles.map(p=>[p.kind,p.x,p.y,p.vx,p.vy]),outcome:b.outcome,summary:b.summary});

test('guided bowless deck clears pending shots and free recovery restores a real training hit at zero gold',async t=>{
 const storage=new MemoryStorage(),ui=await loadGameUI(t,{search:'?mode=test&guide=1',storage});ui.click('start');ui.frames();const b=ui.battle,p=b.profile,arrow=p.skills.find(s=>s.id==='arrow');ui.click('battlePause');open(ui);prepare(ui,empty());p.gold=0;b.queuePlayerShot({canFire:true,vx:10,vy:-2},arrow);b.shooter.intentSkill=arrow;b.queuedSelection=0;ui.click('deckApply');assert.equal(b.activeSkill,null);assert.equal(b.hotbar.active,null);assert.equal(b.playerShots.length,0);assert.equal(b.queuedSelection,null);assert.equal(b.shooter.intentSkill,undefined);assert.match(ui.get('deckStorageNote').textContent,/this drill.*fresh profile.*deck code/);close(ui);ui.click('resumeGame');ui.frames();ui.click('trainingAssist');ui.frames(5);assert.equal(b.stats.shotsFired,0);assert.equal(b.guidedTraining.complete,false);assert.match(ui.get('combatSkillName').textContent,/No bow equipped/);ui.click('battlePause');open(ui);const tick=b.tick,skills=[...p.skills];ui.click('deckRecoverArrow');assert.equal(b.tick,tick);assert.equal(p.gold,0);assert.equal(p.skills[0],skills[0]);assert.equal(b.activeSkill,arrow);assert.equal(arrow.binding,0);assert.equal(books(ui)[0].slots.every(id=>id===null),true);close(ui);ui.click('resumeGame');ui.frames();ui.click('trainingAssist');ui.frames(200);assert.equal(b.guidedTraining.complete,true);assert.equal(p.victories,0);assert.equal(p.defeats,0);await settle();assert.deepEqual(checkpointBytes(storage),[]);
});

test('guided, sandbox and campaign deck libraries follow profile identity through session returns and fresh drills',async t=>{
 const storage=new MemoryStorage(),ui=await loadGameUI(t,{search:'?mode=test',storage}),sandbox=ui.battle;open(ui);save(ui,'Same title');const sandboxCode=books(ui);close(ui);const sandboxBefore=snapshot(sandbox);ui.click('introGuidedTraining');const guide=ui.battle;open(ui);assert.match(ui.get('deckCount').textContent,/0 \/ 12/);save(ui,'Same title');prepare(ui,empty('Guide only'));ui.click('deckApply');const guideCode=books(ui);close(ui);ui.click('start');ui.frames();ui.click('battlePause');ui.click('pauseLobby');const paused=snapshot(guide);switchTo(ui,'campaign');const campaign=ui.battle;open(ui);assert.match(ui.get('deckCount').textContent,/0 \/ 12/);save(ui,'Campaign only');close(ui);await settle();const campaignBytes=checkpointBytes(storage);switchTo(ui,'training');assert.equal(ui.battle,guide);assert.equal(snapshot(guide),paused);open(ui);assert.deepEqual(books(ui),guideCode);close(ui);ui.click('start');ui.frames();ui.click('trainingSkip');ui.frames();const second=ui.battle;assert.notEqual(second.profile,guide.profile);assert.equal(second.profile.name,guide.profile.name);ui.click('battlePause');open(ui);assert.match(ui.get('deckCount').textContent,/0 \/ 12/);close(ui);ui.click('pauseExitTraining');ui.frames();assert.equal(ui.battle,sandbox);assert.equal(snapshot(sandbox),sandboxBefore);open(ui);assert.deepEqual(books(ui),sandboxCode);close(ui);await settle();assert.deepEqual(checkpointBytes(storage),campaignBytes);switchTo(ui,'campaign');assert.equal(ui.battle,campaign);open(ui);assert.deepEqual(books(ui).map(d=>d.name),['Campaign only']);
});

test('guided restart creates a fresh supplied profile without adopting the prior named library',async t=>{
 const ui=await loadGameUI(t,{search:'?mode=test&guide=1'});open(ui);save(ui,'Old drill');prepare(ui,empty());ui.click('deckApply');const old=ui.battle.profile,code=books(ui);close(ui);ui.click('start');ui.frames();ui.click('trainingRestart');ui.frames();assert.notEqual(ui.battle.profile,old);assert.equal(ui.battle.profile.name,old.name);assert.equal(ui.battle.activeSkill.id,'arrow');ui.click('battlePause');open(ui);assert.match(ui.get('deckCount').textContent,/0 \/ 12/);ui.get('deckImportCode').value=exportDeckCode(code);ui.click('deckImportPrepare');assert.match(ui.get('deckConfirmText').textContent,/Add 2 decks/);ui.click('deckConfirmAccept');assert.equal(books(ui).length,2);assert.equal(ui.battle.activeSkill.id,'arrow');
});

test('remapped companion labels appear in deck comparison while text entry never triggers live actions',async t=>{
 const storage=new MemoryStorage();storage.data.set(CONTROL_STORAGE_KEY,JSON.stringify({version:1,bindings:{...DEFAULT_CONTROL_BINDINGS,companion:'h',arc:'j',pause:'o'}}));const ui=await loadGameUI(t,{search:'?mode=test&guide=1',storage});ui.click('start');ui.frames();ui.key('keydown','o');assert.equal(ui.battle.paused,true);open(ui);const d=captureDeck(ui.battle.profile,'Keep bow');d.companion=null;prepare(ui,d);assert.match(ui.get('deckChanges').textContent,/separate H slot/);assert.doesNotMatch(ui.get('deckChanges').textContent,/separate G slot/);const b=ui.battle,tick=b.tick,angle=b.shooter.angleMode;ui.get('deckNewName').focus();for(const key of ['h','j','o','1'])ui.key('keydown',key);assert.equal(b.companions.unit,null);assert.equal(b.shooter.angleMode,angle);assert.equal(b.tick,tick);assert.equal(b.paused,true);assert.doesNotMatch(ui.get('deckExportCode').value,/previousBar|nextBar|bindings/);close(ui);ui.click('resumeGame');ui.key('keydown','g');assert.equal(b.companions.unit,null);ui.key('keydown','h');assert.ok(b.companions.unit);ui.key('keydown','j');assert.notEqual(b.shooter.angleMode,angle);
});

test('campaign invitation returns to exact campaign state and library after guided bowless edits',async t=>{
 const storage=new MemoryStorage(),ui=await loadGameUI(t,{storage}),campaign=ui.battle;open(ui);save(ui,'Crownroad');close(ui);await settle();const bytes=checkpointBytes(storage),before=snapshot(campaign);ui.click('introGuidedTraining');open(ui);save(ui,'Drill');prepare(ui,empty());ui.click('deckApply');close(ui);ui.click('introExitTraining');ui.frames();assert.equal(ui.battle,campaign);assert.equal(snapshot(campaign),before);await settle();assert.deepEqual(checkpointBytes(storage),bytes);open(ui);assert.deepEqual(books(ui).map(d=>d.name),['Crownroad']);
});
