import test from 'node:test';import assert from 'node:assert/strict';
import {loadGameUI} from './helpers/game-ui-harness.mjs';
import {MemoryStorage,TestLocks,settle} from './helpers/local-storage.mjs';
import {createLocalCampaignStore} from '../site/dist/local-campaign-store.mjs';
import {PlayerProfile} from '../site/dist/engine/progression.mjs';
import {captureDeck,exportDeckCode,parseDeckCode} from '../site/dist/deck-presets-model.mjs';
const submit=(ui,id)=>ui.dispatch(ui.get(id),'submit');
const save=(ui,name)=>{ui.get('deckNewName').value=name;submit(ui,'deckSaveForm');};
const choose=(ui,index)=>ui.get('deckList').querySelector(`[data-deck-index="${index}"]`).click();
const exportAll=ui=>{ui.click('deckShowExport');return parseDeckCode(ui.get('deckExportCode').value);};
async function editor(t,options={}){const ui=await loadGameUI(t,options);ui.click('introLoadout');ui.click('openDeckPresets');return ui;}
const importDecks=(ui,decks)=>{ui.get('deckImportCode').value=exportDeckCode(decks);ui.click('deckImportPrepare');};
const deckWith=(name,id)=>{const p=new PlayerProfile();if(id&&id!=='arrow')p.addSkill(id);return captureDeck(p,name);};

test('save captures arrangement, rename and duplicate are explicit with no equipment edits',async t=>{const ui=await editor(t),p=ui.battle.profile,before=JSON.stringify(p);save(ui,'Castle guard');assert.match(ui.get('deckCount').textContent,/1 \/ 12/);assert.equal(exportAll(ui)[0].name,'Castle guard');ui.get('deckRename').value='Shield line';submit(ui,'deckRenameForm');assert.equal(exportAll(ui)[0].name,'Shield line');ui.click('deckDuplicate');assert.deepEqual(exportAll(ui).map(d=>d.name),['Shield line','Shield line (2)']);assert.equal(JSON.stringify(p),before);assert.equal(ui.battle.tick,0);});
test('all12 slots are bounded and duplicate/name collisions keep existing decks',async t=>{const ui=await editor(t);for(let i=0;i<12;i++)save(ui,`Deck ${i}`);assert.match(ui.get('deckCount').textContent,/12 \/ 12/);assert.equal(ui.get('deckSaveCurrent').disabled,true);assert.equal(ui.get('deckDuplicate').disabled,true);save(ui,'Overflow');assert.match(ui.get('deckStatus').textContent,/at most 12/);assert.equal(exportAll(ui).length,12);ui.get('deckRename').value='Deck 0';submit(ui,'deckRenameForm');assert.match(ui.get('deckStatus').textContent,/unique/);assert.equal(exportAll(ui)[11].name,'Deck 11');});
test('compare shows every key and returning card; apply preserves live objects, queue and timers',async t=>{const ui=await loadGameUI(t,{search:'?mode=test'});ui.click('introTesting');ui.click('testUnlock');ui.click('closeTesting');ui.click('start');ui.click('battlePause');ui.click('pauseSkills');ui.click('openDeckPresets');const b=ui.battle,p=b.profile,skills=[...p.skills];save(ui,'Full arsenal');const d=captureDeck(p,'A single arrow');d.slots.fill(null);d.slots[29]='arrow';d.companion=null;importDecks(ui,[d]);ui.click('deckConfirmAccept');assert.match(ui.get('deckSummary').textContent,/Applying replaces all three bars/);assert.match(ui.get('deckReturns').textContent,/Fire Arrow/);assert.match(ui.get('deckChanges').textContent,/Bar 3, key 0/);const gold=p.gold,tick=b.tick;const states=p.skills.map(s=>({...s})),projectiles=b.projectiles,queue=b.friendlyQueue.queue,pending=b.playerShots;ui.click('deckApply');assert.equal(p.skills[0].binding,29);assert.ok(p.skills.slice(1).every(s=>s.binding===-1));assert.equal(b.projectiles,projectiles);assert.equal(b.friendlyQueue.queue,queue);assert.equal(b.playerShots,pending);assert.equal(b.tick,tick);assert.equal(p.gold,gold);for(let i=0;i<skills.length;i++){assert.equal(p.skills[i],skills[i]);for(const key of Object.keys(states[i]).filter(k=>k!=='binding'))assert.deepEqual(p.skills[i][key],states[i][key]);}assert.equal(ui.get('deckApply').disabled,true);ui.click('closeDeckPresets');assert.equal(ui.visible('skillsPanel'),true);assert.match(ui.get('skillsResources').textContent,/1\/30 equipped/);ui.document.querySelector('[data-loadout-bar="2"]').click();assert.match(ui.get('assign-29').getAttribute('aria-label'),/Basic Arrow/);});
test('import review shows missing cards, grants nothing and blocks atomic apply',async t=>{const ui=await editor(t),p=ui.battle.profile,before=JSON.stringify(p);const d=deckWith('Expensive','fireArrow');d.companion='gorath';importDecks(ui,[d]);assert.match(ui.get('deckCount').textContent,/0 \/ 12/);assert.match(ui.get('deckConfirmText').textContent,/Missing cards: Fire Arrow, Gorath/);ui.click('deckConfirmAccept');assert.match(ui.get('deckMissing').textContent,/Nothing is bought or partially applied/);assert.equal(ui.get('deckApply').disabled,true);ui.get('deckApply').onclick();assert.equal(JSON.stringify(p),before);assert.equal(exportAll(ui).length,1);});
test('import cancels without changes and collision acceptance never overwrites',async t=>{const ui=await editor(t);save(ui,'One');importDecks(ui,[deckWith('One','fireArrow')]);assert.match(ui.get('deckConfirmText').textContent,/One \(2\)/);ui.click('deckConfirmCancel');assert.equal(exportAll(ui).length,1);ui.click('deckImportPrepare');ui.click('deckConfirmAccept');const decks=exportAll(ui);assert.deepEqual(decks.map(d=>d.name),['One','One (2)']);assert.equal(decks[0].slots[1],null);assert.equal(decks[1].slots[1],'fireArrow');ui.click('deckConfirmAccept');assert.equal(exportAll(ui).length,2);});
test('malformed, foreign and oversized codes retain all decks and equipment',async t=>{const ui=await editor(t);save(ui,'Kept');const before=JSON.stringify(ui.battle.profile);for(const text of ['{}','{broken','x'.repeat(32769),'{"schema":"castledecks-deck-presets-1","decks":[],"extra":1}']){ui.get('deckImportCode').value=text;ui.click('deckImportPrepare');assert.equal(ui.visible('deckConfirm'),false);assert.equal(exportAll(ui).length,1);}assert.equal(JSON.stringify(ui.battle.profile),before);});
test('delete requires confirmation and Escape cancels before closing deck view then loadout',async t=>{const ui=await editor(t);save(ui,'Kept');ui.click('deckDelete');assert.equal(ui.visible('deckConfirm'),true);assert.equal(ui.document.activeElement,ui.get('deckConfirmCancel'));ui.key('keydown','Escape');assert.equal(ui.visible('deckConfirm'),false);assert.equal(ui.visible('deckPresets'),true);assert.equal(exportAll(ui).length,1);ui.click('deckDelete');ui.click('deckConfirmAccept');assert.match(ui.get('deckCount').textContent,/0 \/ 12/);assert.equal(ui.battle.profile.skills[0].binding,0);ui.key('keydown','Escape');assert.equal(ui.visible('deckPresets'),false);assert.equal(ui.document.activeElement,ui.get('openDeckPresets'));assert.equal(ui.visible('skillsPanel'),true);ui.key('keydown','Escape');assert.equal(ui.visible('skillsPanel'),false);});
test('profile changes never inherit saved decks; returning profile keeps its own library',async t=>{const ui=await editor(t);save(ui,'Original');ui.click('closeDeckPresets');ui.click('closeSkills');ui.click('introProfiles');ui.get('newProfileName').value='Second';ui.click('createProfile');ui.click('closeProfiles');ui.click('introLoadout');ui.click('openDeckPresets');assert.match(ui.get('deckCount').textContent,/0 \/ 12.*Second/);save(ui,'Other');ui.click('closeDeckPresets');ui.click('closeSkills');ui.click('introProfiles');ui.get('profileSelect').value='0';ui.click('switchProfile');ui.click('closeProfiles');ui.click('introLoadout');ui.click('openDeckPresets');assert.equal(exportAll(ui)[0].name,'Original');});
test('saved decks restore from local v2 checkpoint before setup with campaign export unchanged',async t=>{const storage=new MemoryStorage(),ui=await editor(t,{storage}),store=createLocalCampaignStore({storage,locks:new TestLocks()}),profile=ui.battle.profile;save(ui,'Local deck');await settle();assert.equal(store.read(1).latest.schema,'castledecks-local-checkpoint-2');assert.equal(store.read(1).latest.payload.deckPresets.profiles[0][0].name,'Local deck');ui.click('closeDeckPresets');ui.click('closeSkills');ui.click('introSave');ui.click('showSaveCode');assert.doesNotMatch(ui.get('saveCode').value,/Local deck|deckPresets|castledecks-deck/);ui.get('localSlots').querySelector('[data-local-continue="1"]').click();await settle();ui.click('localConfirmAccept');await settle();assert.notEqual(ui.battle.profile,profile);ui.click('introLoadout');ui.click('openDeckPresets');assert.equal(exportAll(ui)[0].name,'Local deck');});
test('paused deck edits remain session-only until safe checkpoint; no per-frame write',async t=>{const storage=new MemoryStorage(),ui=await loadGameUI(t,{storage}),store=createLocalCampaignStore({storage,locks:new TestLocks()});ui.click('start');await settle();const before=store.read(1).raw;ui.click('battlePause');ui.click('pauseSkills');ui.click('openDeckPresets');save(ui,'Paused change');await settle();assert.deepEqual(store.read(1).raw,before);assert.match(ui.get('deckStorageNote').textContent,/stay in this session until a settled-result checkpoint/);ui.frames(4);await settle();assert.deepEqual(store.read(1).raw,before);assert.equal(exportAll(ui)[0].name,'Paused change');});
test('quota failure keeps old local checkpoint and honest message while code preserves new decks',async t=>{const storage=new MemoryStorage(),ui=await editor(t,{storage}),store=createLocalCampaignStore({storage,locks:new TestLocks()}),before=store.read(1).raw;storage.setItem=()=>{throw Object.assign(new Error(),{name:'QuotaExceededError'});};save(ui,'Only in memory');await settle();assert.deepEqual(store.read(1).raw,before);assert.match(ui.get('deckStorageNote').textContent,/storage is full/);assert.equal(exportAll(ui)[0].name,'Only in memory');});
test('all-empty imported deck can apply safely and keeps every ability owned',async t=>{const ui=await editor(t);importDecks(ui,[{name:'Reserve all',slots:Array(30).fill(null),companion:null}]);ui.click('deckConfirmAccept');assert.match(ui.get('deckReturns').textContent,/Basic Arrow/);ui.click('deckApply');assert.equal(ui.battle.profile.skills[0].binding,-1);assert.equal(ui.battle.profile.owned.has('arrow'),true);ui.click('closeDeckPresets');ui.click('closeSkills');assert.equal(ui.visible('intro'),true);});
test('apply handler revalidates companion-active and paused restrictions at click time',async t=>{const ui=await loadGameUI(t,{search:'?mode=demo&showcase=companions'});ui.click('start');ui.click('battlePause');ui.click('pauseSkills');ui.click('openDeckPresets');const b=ui.battle,p=b.profile;const d=captureDeck(p,'No companion');d.companion=null;d.slots[0]=null;importDecks(ui,[d]);ui.click('deckConfirmAccept');const before=p.skills.map(s=>s.binding);b.companions.unit={id:'active-test'};ui.get('deckApply').onclick();assert.deepEqual(p.skills.map(s=>s.binding),before);assert.equal(p.companionId,'gorath');b.companions.unit=null;b.paused=false;ui.get('deckApply').onclick();assert.deepEqual(p.skills.map(s=>s.binding),before);b.paused=true;ui.get('deckApply').onclick();assert.equal(p.companionId,null);assert.equal(p.skills[0].binding,-1);});
test('editing import after review cancels stale confirmation and never accepts different code',async t=>{const ui=await editor(t);importDecks(ui,[deckWith('First')]);ui.get('deckImportCode').value=exportDeckCode([deckWith('Different')]);ui.click('deckConfirmAccept');assert.match(ui.get('deckCount').textContent,/0 \/ 12/);assert.equal(ui.visible('deckConfirm'),false);ui.click('deckImportPrepare');ui.get('deckImportCode').value='invalid';ui.click('deckImportPrepare');assert.equal(ui.visible('deckConfirm'),false);ui.click('deckConfirmAccept');assert.match(ui.get('deckCount').textContent,/0 \/ 12/);});
test('export code remains current after rename and deletion while visible',async t=>{const ui=await editor(t);save(ui,'First');exportAll(ui);ui.get('deckRename').value='Renamed';submit(ui,'deckRenameForm');assert.equal(parseDeckCode(ui.get('deckExportCode').value)[0].name,'Renamed');ui.click('deckDelete');ui.click('deckConfirmAccept');assert.equal(parseDeckCode(ui.get('deckExportCode').value).length,0);assert.equal(ui.document.activeElement,ui.get('deckNewName'));});
test('deck inspector heading focus survives selection and asynchronous checkpoint repaint',async t=>{const ui=await editor(t,{storage:new MemoryStorage()});save(ui,'First');const row=ui.get('deckList').querySelector('[data-deck-index="0"]');row.focus();row.click();assert.equal(ui.document.activeElement,ui.get('deckTitle'));await settle();assert.equal(ui.document.activeElement,ui.get('deckTitle'));});
test('same-tab practice decks stay isolated and explicitly session-only',async t=>{const storage=new MemoryStorage(),ui=await editor(t,{storage});save(ui,'Campaign deck');await settle();ui.click('closeDeckPresets');ui.click('closeSkills');ui.get('hubDestinations').querySelector('[data-hub-destination="training"]').click();ui.click('start');ui.click('introLoadout');ui.click('openDeckPresets');assert.match(ui.get('deckCount').textContent,/0 \/ 12/);assert.match(ui.get('deckStorageNote').textContent,/Practice decks stay in this session/);save(ui,'Practice deck');ui.click('closeDeckPresets');ui.click('closeSkills');ui.get('hubDestinations').querySelector('[data-hub-destination="campaign"]').click();ui.click('start');ui.click('introLoadout');ui.click('openDeckPresets');assert.deepEqual(exportAll(ui).map(d=>d.name),['Campaign deck']);});

test('Saved decks uses45 shared focus targets and ignores disabled or inert controls',async t=>{
 const ui=await editor(t);ui.get('deckNewName').disabled=true;ui.get('deckImportCode').setAttribute('aria-disabled','true');const transfer=ui.get('deckPresets').querySelector('details');transfer.inert=true;
 const last=ui.get('deckSaveCurrent');last.focus();const forward=ui.dispatch(last,'keydown',{key:'Tab'});assert.equal(forward.event.defaultPrevented,true);assert.equal(ui.document.activeElement,ui.get('closeDeckPresets'));const backward=ui.dispatch(ui.get('closeDeckPresets'),'keydown',{key:'Tab',shiftKey:true});assert.equal(backward.event.defaultPrevented,true);assert.equal(ui.document.activeElement,last);
});
