import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,readdirSync} from 'node:fs';import {createHash} from 'node:crypto';
import {drawElementalFlyer,drawAirFighter} from '../site/dist/flying-unit-art.mjs';
import {drawElementalDragon} from '../site/dist/elemental-feedback.mjs';
import {CampaignBattle} from '../site/dist/engine/first-battle.mjs';
import {COLLISION_REGIONS} from '../site/dist/engine/collision.mjs';
import {createSpecialMotionController} from '../site/dist/special-unit-motion.mjs';
function trace(){const calls=[],states=[],state={globalAlpha:.65,fillStyle:'#000',strokeStyle:'#000',lineWidth:1,lineJoin:'miter',lineCap:'butt'};const ctx=new Proxy(state,{get:(o,k)=>k in o?o[k]:(...args)=>{for(const n of args)if(typeof n==='number')assert.ok(Number.isFinite(n));calls.push({name:k,args,alpha:state.globalAlpha,fill:state.fillStyle,stroke:state.strokeStyle});if(k==='save')states.push({...state});if(k==='restore'){assert.ok(states.length);Object.assign(state,states.pop());}},set:(o,k,v)=>(o[k]=v,true)});return{ctx,calls,states,state};}
for(const kind of ['fire','ice','poison','air'])test(`${kind}: immutable inputs and caller canvas state survive all existing wing poses`,()=>{
 const u=Object.freeze({type:kind==='air'?'air':`dragon_scout_${kind}`,team:'bad',hp:0,maxHp:100,x:900,y:320,animation:Object.freeze({frame:15})});
 for(const lift of [-22,-14,0,14,NaN,Infinity]){const motion=Object.freeze({wingLift:lift}),t=trace(),before={...t.state};assert.equal((kind==='air'?drawAirFighter:drawElementalDragon)(t.ctx,u,motion),true);assert.deepEqual(t.state,before);assert.equal(t.states.length,0);assert.ok(t.calls.length<300,`bounded operation count ${t.calls.length}`);}
});
test('unrecognized or non-flying units are rejected without drawing',()=>{const t=trace();assert.equal(drawAirFighter(t.ctx,{type:'grunt'}),false);assert.equal(drawElementalDragon(t.ctx,{type:'air'}),false);assert.equal(drawElementalFlyer(t.ctx,{type:'grunt'},null,'unknown'),false);assert.equal(t.calls.length,0);});
test('fixed dragon eye/head anchors never bob during flapping or descent',()=>{
 for(const element of ['fire','ice','poison'])for(const wingLift of [-22,-14,0,14]){const t=trace();drawElementalDragon(t.ctx,{type:`dragon_scout_${element}`,team:'bad'},{wingLift});assert.ok(t.calls.some(c=>c.name==='arc'&&c.args[0]===-23&&c.args[1]===0));assert.equal(t.calls.some(c=>['translate','rotate','scale','setTransform'].includes(c.name)),false);}
 const b=COLLISION_REGIONS.enemyFireDragon;assert.ok(-27>=b.headbox[0]&&-12<=b.headbox[1]&&-6>=b.headbox[2]&&9<=b.headbox[3]);assert.ok(-27>=b.hitbox[0]&&26<=b.hitbox[1]&&-13>=b.hitbox[2]&&16<=b.hitbox[3]);
});
test('enemy and ally identity differs by paths, not only palette',()=>{for(const type of ['air','dragon_scout_fire','dragon_scout_ice','dragon_scout_poison']){const a=trace(),b=trace(),render=type==='air'?drawAirFighter:drawElementalDragon;render(a.ctx,{type,team:'good'},{wingLift:0});render(b.ctx,{type,team:'bad'},{wingLift:0});const shape=t=>t.calls.map(c=>[c.name,...c.args]);assert.notDeepEqual(shape(a),shape(b));}});
test('elemental silhouettes differ even without their hues',()=>{const variants=[];for(const type of ['dragon_scout_fire','dragon_scout_ice','dragon_scout_poison']){const t=trace();drawElementalDragon(t.ctx,{type},{wingLift:0});variants.push(JSON.stringify(t.calls.map(c=>[c.name,...c.args])));}assert.equal(new Set(variants).size,3);});
test('decorative wing membrane remains translucent and motion changes only presentation paths',()=>{for(const type of ['air','dragon_scout_fire']){const renderer=type==='air'?drawAirFighter:drawElementalDragon,a=trace(),b=trace();renderer(a.ctx,{type},{wingLift:-22});renderer(b.ctx,{type},{wingLift:14});assert.notDeepEqual(a.calls,b.calls);assert.ok(a.calls.some(c=>c.name==='fill'&&c.alpha<.4*.65));}});
test('new art has no frame-owned objects, raster buffers, async work or random source',()=>{const source=readFileSync(new URL('../site/dist/flying-unit-art.mjs',import.meta.url),'utf8');assert.doesNotMatch(source,/\bnew\s|Math\.random|Date\.|performance\.|requestAnimationFrame|setInterval|setTimeout|createCanvas|drawImage|create(?:Linear|Radial)Gradient|measureText/);assert.doesNotMatch(source,/motion\s*=\s*\{|\.map\(|\.forEach\(|Array\.from/);assert.equal((source.match(/Object\.freeze/g)||[]).length,4);});
test('all engine files and passive special-motion clock match the reviewed exact-budget and damage-attribution49 boundary',()=>{const hash=createHash('sha256');for(const n of readdirSync(new URL('../site/dist/engine/',import.meta.url)).sort())hash.update(n+'\0').update(readFileSync(new URL('../site/dist/engine/'+n,import.meta.url))).update('\0');assert.equal(hash.digest('hex'),'c0b2932fe102a69a6a6f96df9a55bf609cf484859ce440d14dbec151f0415788');assert.equal(createHash('sha256').update(readFileSync(new URL('../site/dist/special-unit-motion.mjs',import.meta.url))).digest('hex'),'65daad07fe9cc349f8a05cdd6eddf65231e7fa6d7ff7da30c093060618faf162');});
test('rendered and unrendered battles preserve random stream, actors, projectiles and collision boxes',()=>{
 function run(render){let seed=357,randomCalls=0;const random=()=>{randomCalls++;seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};const b=new CampaignBattle({level:16,random}),clock=createSpecialMotionController();
  for(const team of ['good','bad'])for(const [i,kind]of ['air','fireDragon','iceDragon','poisonDragon'].entries()){const u=b.createUnit(kind,{team});u.x=550+i*175;u.y=310+(i%2)*60;u.targetX=team==='good'?1600:400;u.targetY=350;u.visible=true;b.updateGeometry(u);}clock.attach(b);
  const noOp=()=>{},ctx=new Proxy({globalAlpha:1},{get:(o,k)=>k in o?o[k]:noOp,set:(o,k,v)=>(o[k]=v,true)});
  for(let tick=0;tick<360;tick++){b.step();clock.observeTick();if(render)for(const u of b.airUnits){const pose=clock.air(u);if(!drawElementalDragon(ctx,u,pose))drawAirFighter(ctx,u,pose);}}
  return{seed,randomCalls,tick:b.tick,stats:b.stats,gold:b.profile.gold,actors:[...b.goodTeam,...b.badTeam].map(u=>[u.type,u.x,u.y,u.hp,u.vx,u.vy,u.actionMode,u.actionDuration,u.hitbox,u.headbox]),projectiles:b.projectiles.map(p=>[p.kind,p.x,p.y,p.vx,p.vy,p.active]),records:b.airUnits.map(u=>({...clock.record(u)}))};}
 assert.deepEqual(run(true),run(false));
});
