import test from 'node:test';
import assert from 'node:assert/strict';
import {CampaignBattle} from '../site/dist/engine/first-battle.mjs';
import {PlayerProfile,summonSquad} from '../site/dist/engine/progression.mjs';
import {createTrainingRun,createTrainingBattleOptions,prepareTrainingBattle,advanceTraining,restartTrainingLesson,trainingCopy,TRAINING_LESSONS} from '../site/dist/guided-training.mjs';
function fixture(index=0){const run=createTrainingRun();run.index=index;let controller;const b=new CampaignBattle({...createTrainingBattleOptions(run),onEvent:e=>controller?.observe(e)});controller=prepareTrainingBattle(b,run);const tick=(n=1)=>{for(let i=0;i<n;i++){b.step();controller.afterTick();}};return {b,controller,run,tick};}
function fire(f,skill='arrow'){f.b.activeSkill=f.b.profile.skills.find(s=>s.id===skill);f.b.hotbar.active=f.b.activeSkill;assert.equal(f.controller.assistedShot(),true);f.tick(360);}

test('training fixtures are fresh, explicitly assisted, deterministic and reject campaign mutation',()=>{const run=createTrainingRun(),a=createTrainingBattleOptions(run),b=createTrainingBattleOptions(run);assert.notEqual(a.profile,b.profile);assert.equal(a.profile.cheated,true);assert.equal(a.profile.victories,0);assert.equal(a.profile.defeats,0);assert.equal(a.profile.skills.every(s=>s.autocast===false),true);assert.throws(()=>prepareTrainingBattle(new CampaignBattle({profile:new PlayerProfile()}),run),/fresh/);const f=fixture();assert.throws(()=>prepareTrainingBattle(f.b,f.run),/fresh/);const p=f.controller.targetPoint();assert.ok(Number.isFinite(p.x)&&Number.isFinite(p.y));assert.equal(f.controller.target.trainingFixture,true);});

test('waiting never succeeds or spawns real waves; actual player hit and HP loss are required',()=>{const f=fixture();f.tick(3000);assert.equal(f.controller.complete,false);assert.equal(f.b.badTeam.length,1);assert.equal(f.b.profile.victories,0);assert.equal(f.b.outcome,null);assert.equal(f.run.completed.size,0);assert.equal(f.controller.target.hp,5000);f.controller.observe({type:'hit',target:f.controller.target,damage:200,projectile:{kind:'hero_arrow',team:'good'}});assert.equal(f.controller.complete,false);fire(f);assert.equal(f.controller.complete,true);assert.ok(f.controller.target.hp<5000);assert.equal(f.run.completed.has('aim'),true);assert.equal(f.b.profile.victories,0);});

test('arc drill needs a high-arc shot hit; switching while the low shot flies cannot relabel it',()=>{const f=fixture(1);assert.equal(f.b.shooter.angleMode,1);f.controller.assistedShot();f.tick();f.b.shooter.angleMode=0;f.tick(400);assert.equal(f.controller.complete,false);fire(f);assert.equal(f.controller.complete,true);});

test('squad drill observes actual reinforcements from the acquired Grunt skill',()=>{const f=fixture(2),grunt=f.b.profile.skills.find(s=>s.id==='grunt');f.controller.observe({type:'spawn',unit:{team:'good',type:'grunt'}});assert.equal(f.controller.complete,false);assert.equal(summonSquad(grunt,f.b.profile,f.b.friendlyQueue,f.b.stats),true);assert.equal(f.controller.complete,false);f.tick(1);assert.equal(f.controller.complete,true);assert.equal(f.b.profile.gold,580);assert.equal(f.b.regularArmyCount,1);assert.equal(f.b.profile.victories,0);});

test('fire dragon drill proves a resisted basic hit and real ice damage, without a long cooldown',()=>{const f=fixture(3);assert.equal(f.controller.target.multipliers.pierce,.1);assert.equal(f.controller.target.multipliers.ice,4);fire(f);assert.equal(f.controller.complete,false);assert.equal(f.controller.stage,'counter');assert.ok(f.controller.snapshot.lastDamage>0);assert.match(trainingCopy(f.controller).instruction,/Basic Arrow dealt/);const resisted=f.controller.snapshot.lastDamage,hp=f.controller.target.hp;fire(f,'iceArrow');assert.equal(f.controller.complete,true);assert.ok(f.controller.target.hp<hp);assert.ok(f.controller.snapshot.lastDamage>resisted);assert.equal(f.b.profile.victories,0);});

test('Gorath drill requires a real summon then actual signature event after windup',()=>{const f=fixture(4);f.controller.observe({type:'companion-signature',unit:{},name:'Earthshatter'});assert.equal(f.controller.complete,false);assert.equal(f.b.companions.act(),true);assert.equal(f.controller.complete,false);assert.equal(f.b.companions.act(),true);f.tick(17);assert.equal(f.controller.complete,false);f.tick();assert.equal(f.controller.complete,true);assert.ok(f.b.spells.some(s=>s.kind==='gorath_shock_wave'));});

test('skip is never completion; restart clears only the current drill and finished runs are bounded',()=>{const f=fixture();assert.equal(advanceTraining(f.run),false);assert.equal(advanceTraining(f.run,{skip:true}),true);assert.equal(f.run.completed.size,0);assert.equal(f.run.skipped.has('aim'),true);f.run.completed.add('arc');restartTrainingLesson(f.run);assert.equal(f.run.completed.has('arc'),false);assert.equal(f.run.skipped.has('aim'),true);while(f.run.index<TRAINING_LESSONS.length)advanceTraining(f.run,{skip:true});assert.equal(advanceTraining(f.run,{skip:true}),false);assert.equal(restartTrainingLesson(f.run),false);assert.equal(f.run.completed.size,0);});

test('paused practice neither accepts assistance nor completes from forged contacts',()=>{const f=fixture();f.b.paused=true;assert.equal(f.controller.assistedShot(),false);f.tick(100);assert.equal(f.b.tick,0);assert.equal(f.controller.complete,false);});
