import test from 'node:test';
import assert from 'node:assert/strict';
import {loadGameUI} from './helpers/game-ui-harness.mjs';
const snap=b=>JSON.stringify({tick:b.tick,profile:b.profile,stats:b.stats,good:b.goodTeam.map(u=>[u.type,u.x,u.y,u.hp]),bad:b.badTeam.map(u=>[u.type,u.x,u.y,u.hp]),queue:b.friendlyQueue.queue,projectiles:b.projectiles.map(p=>[p.kind,p.x,p.y]),arc:b.shooter.angleMode});
function switchTo(ui,id){ui.get('hubDestinations').querySelector(`[data-hub-destination="${id}"]`).click();ui.click('start');if(ui.visible('switchSessionConfirm'))ui.click('confirmSessionSwitch');ui.frames();}
function begin(ui){ui.click('introGuidedTraining');ui.click('start');ui.frames();}

test('first-time invitation is optional, dismissible, and does not modify or start a campaign',async t=>{const ui=await loadGameUI(t),b=ui.battle,before=snap(b);assert.equal(ui.visible('trainingEntry'),true);ui.click('dismissTrainingInvite');assert.equal(ui.visible('trainingEntry'),false);ui.frames(100);assert.equal(snap(b),before);assert.equal(ui.visible('intro'),true);switchTo(ui,'training');assert.equal(ui.visible('trainingEntry'),true);assert.equal(ui.visible('introTesting'),true);});

test('guides preserve and restore exact campaign and playground sessions',async t=>{const ui=await loadGameUI(t),campaign=ui.battle;campaign.profile.gold=345;const before=snap(campaign);begin(ui);assert.notEqual(ui.battle,campaign);assert.equal(ui.battle.profile.name,'Guided practice');assert.equal(ui.battle.profile.cheated,true);assert.equal(ui.visible('trainingCoach'),true);assert.equal(ui.visible('introTesting'),false);assert.equal(ui.get('saveGame').disabled,true);assert.equal(ui.battle.profile.victories,0);ui.click('trainingAssist');ui.frames(200);assert.equal(ui.battle.guidedTraining.complete,true);ui.click('trainingExit');ui.frames();assert.equal(ui.battle,campaign);assert.equal(snap(campaign),before);assert.equal(ui.visible('intro'),true);assert.equal(ui.visible('trainingCoach'),false);assert.equal(ui.get('saveGame').disabled,false);
 switchTo(ui,'training');const sandbox=ui.battle;sandbox.profile.gold=789;const sandboxBefore=snap(sandbox);begin(ui);ui.click('trainingExit');ui.frames();assert.equal(ui.battle,sandbox);assert.equal(snap(sandbox),sandboxBefore);assert.equal(ui.visible('introTesting'),true);ui.click('introTesting');ui.click('testGoldLarge');assert.equal(sandbox.profile.gold,10789);});

test('real controls complete all drills, review Loadout, then return without campaign reward',async t=>{const ui=await loadGameUI(t,{search:'?mode=test'}),sandbox=ui.battle,before=snap(sandbox);begin(ui);const guide=()=>ui.battle.guidedTraining;
 ui.click('trainingNext');ui.frames();assert.equal(guide().run.index,0);ui.click('trainingAssist');ui.frames(200);assert.equal(guide().complete,true);assert.equal(ui.visible('trainingNext'),true);ui.click('trainingNext');ui.frames();assert.equal(guide().run.index,1);
 ui.click('liveArc');ui.frames();ui.click('trainingAssist');ui.frames(400);assert.equal(guide().complete,true);ui.click('trainingNext');ui.frames();assert.equal(guide().run.index,2);
 ui.click('quick-grunt');ui.frames(40);assert.equal(guide().complete,true);ui.click('trainingNext');ui.frames();assert.equal(guide().run.index,3);
 ui.click('trainingAssist');ui.frames(200);assert.equal(guide().stage,'counter');ui.click('quick-iceArrow');ui.click('trainingAssist');ui.frames(200);assert.equal(guide().complete,true);ui.click('trainingNext');ui.frames();assert.equal(guide().run.index,4);
 ui.click('companionAction');ui.frames();ui.click('companionAction');ui.frames(30);assert.equal(guide().complete,true);ui.click('trainingNext');ui.frames();assert.equal(guide().run.index,5);assert.equal(guide().run.completed.size,5);assert.equal(ui.visible('trainingLoadout'),true);assert.equal(ui.battle.profile.victories,0);ui.click('trainingLoadout');assert.equal(ui.visible('skillsPanel'),true);ui.click('closeSkills');ui.frames();assert.equal(guide().run.reviewedLoadout,true);assert.equal(ui.get('trainingExit').textContent,'Finish practice');ui.click('trainingExit');ui.frames();assert.equal(ui.battle,sandbox);assert.equal(snap(sandbox),before);});

test('pause, Escape, window blur, lobby and session switching preserve a drill without false progress',async t=>{const ui=await loadGameUI(t,{search:'?mode=test&guide=1'});assert.equal(ui.visible('intro'),true);assert.match(ui.get('start').textContent,/Start guided/);ui.frames(100);assert.equal(ui.battle.tick,0);ui.click('start');ui.frames();const b=ui.battle,before=snap(b);ui.click('battlePause');ui.frames(20);assert.equal(ui.visible('trainingCoach'),false);assert.equal(snap(b),before);ui.key('keydown','Escape');ui.frames();assert.equal(ui.visible('trainingCoach'),true);ui.dispatch(ui.window,'blur');ui.frames(50);assert.equal(b.paused,true);assert.equal(b.guidedTraining.complete,false);ui.click('pauseLobby');switchTo(ui,'campaign');assert.equal(ui.visible('trainingCoach'),false);switchTo(ui,'training');assert.equal(ui.battle,b);assert.match(ui.get('start').textContent,/Resume guided/);ui.click('start');ui.frames();assert.equal(ui.visible('trainingCoach'),true);ui.click('trainingExit');ui.frames();assert.equal(ui.visible('introTesting'),true);});

test('skip and restart remain explicit, repeatable and do not create rewards',async t=>{const ui=await loadGameUI(t,{search:'?mode=test'});begin(ui);const first=ui.battle;ui.click('trainingRestart');const second=ui.battle;assert.notEqual(first,second);ui.frames();ui.click('trainingRestart');assert.notEqual(ui.battle,second);assert.equal(ui.battle.profile.victories,0);assert.equal(ui.battle.guidedTraining.run.completed.size,0);ui.frames();ui.click('trainingSkip');assert.equal(ui.battle.guidedTraining.run.index,1);assert.equal(ui.battle.guidedTraining.run.skipped.has('aim'),true);assert.equal(ui.battle.guidedTraining.run.completed.size,0);ui.click('battlePause');ui.click('pauseExitTraining');const sandbox=ui.battle;ui.click('pauseExitTraining');assert.equal(ui.battle,sandbox);assert.equal(ui.visible('introTesting'),true);});

test('leaving a drill restores the original playground controls and pending casts exactly',async t=>{const ui=await loadGameUI(t,{search:'?mode=test'});ui.click('introSettings');ui.get('aimMode').value='auto_aim';ui.get('trajectory').value='0';ui.dispatch(ui.get('aimMode'),'change');ui.dispatch(ui.get('trajectory'),'change');ui.get('showAssist').checked=true;ui.dispatch(ui.get('showAssist'),'change');ui.click('openAim');ui.get('battleAngle').value='37';ui.get('battlePower').value='72';ui.dispatch(ui.get('battlePower'),'input');ui.click('applyAim');ui.click('applySettings');ui.click('start');ui.frames(3);ui.click('battlePause');ui.click('pauseLobby');const b=ui.battle,before=snap(b);begin(ui);ui.click('trainingExit');ui.frames();assert.equal(ui.battle,b);assert.equal(snap(b),before);assert.equal(ui.get('battleAngle').value,'37');assert.equal(ui.get('battlePower').value,'72');assert.equal(ui.get('trajectory').value,'0');assert.equal(ui.get('showAssist').checked,true);assert.equal(ui.visible('battleFire'),true);assert.equal(b.shooter.powerPercent,72);});

test('developer forced outcomes and save/profile routes cannot affect a guided drill',async t=>{const ui=await loadGameUI(t,{search:'?mode=test&guide=1'});ui.click('start');ui.frames();const b=ui.battle,gold=b.profile.gold;ui.click('testVictory');ui.click('testDefeat');ui.click('testGoldLarge');ui.click('testUnlock');ui.click('testReady');ui.frames(20);assert.equal(b.outcome,null);assert.equal(b.summary,null);assert.equal(b.profile.victories,0);assert.equal(b.profile.defeats,0);assert.equal(b.profile.gold,gold);assert.equal(b.profile.skills.length,3);ui.click('battlePause');ui.click('pauseSkills');const route=ui.get('skillsPanel').querySelector('[data-menu-route="vault"]');route.click();assert.equal(ui.visible('savePanel'),false);assert.equal(ui.visible('skillsPanel'),true);ui.click('closeSkills');ui.click('pauseExitTraining');assert.equal(ui.visible('introTesting'),true);});

test('drill advancement cannot be repeated by a stale Next action, and changed-arc immediate shots count',async t=>{const ui=await loadGameUI(t,{search:'?mode=test&guide=1'});ui.click('start');ui.frames();ui.click('trainingAssist');ui.frames(200);ui.click('trainingNext');const arc=ui.battle;ui.click('trainingNext');assert.equal(ui.battle,arc);assert.equal(arc.guidedTraining.run.index,1);ui.frames();ui.click('liveArc');ui.click('trainingAssist');ui.frames(400);assert.equal(arc.guidedTraining.complete,true);});


test('stale repeated Skip and Restart clicks cannot act on the next unseen drill',async t=>{const ui=await loadGameUI(t,{search:'?mode=test&guide=1'});ui.click('start');ui.frames();ui.click('trainingSkip');const second=ui.battle;ui.click('trainingSkip');ui.click('trainingRestart');assert.equal(ui.battle,second);assert.equal(second.guidedTraining.run.index,1);ui.frames();ui.click('trainingRestart');const fresh=ui.battle;ui.click('trainingRestart');assert.equal(ui.battle,fresh);ui.frames();ui.click('trainingExit');});

test('ordinary battlefield pointer and existing keyboard shortcuts also complete real drills',async t=>{const ui=await loadGameUI(t,{search:'?mode=test&guide=1'});ui.click('start');ui.frames();const target=ui.battle.guidedTraining.targetPoint();ui.pointer('pointerdown',61,target);ui.pointer('pointerup',61,target);ui.frames(200);assert.equal(ui.battle.guidedTraining.complete,true);ui.click('trainingNext');ui.frames();ui.key('keydown','v');ui.key('keyup','v');ui.click('trainingAssist');ui.frames(400);assert.equal(ui.battle.guidedTraining.complete,true);ui.click('trainingNext');ui.frames();ui.key('keydown','2',{code:'Digit2'});ui.key('keyup','2',{code:'Digit2'});ui.frames(40);assert.equal(ui.battle.guidedTraining.complete,true);ui.click('trainingNext');ui.frames();ui.click('trainingSkip');ui.frames();ui.key('keydown','g');ui.key('keyup','g');ui.frames();ui.key('keydown','g');ui.key('keyup','g');ui.frames(30);assert.equal(ui.battle.guidedTraining.complete,true);});


test('restarting from the finished practice screen returns to the first drill, and cancel is inert',async t=>{const ui=await loadGameUI(t,{search:'?mode=test&guide=1'});ui.click('start');ui.frames();for(let i=0;i<5;i++){ui.click('trainingSkip');ui.frames();}assert.equal(ui.battle.guidedTraining.run.index,5);ui.click('battlePause');const finished=ui.battle;ui.click('battleRestart');ui.click('cancelRestart');assert.equal(ui.battle,finished);ui.click('battleRestart');ui.click('confirmRestart');ui.frames();assert.equal(ui.battle.guidedTraining.run.index,0);assert.equal(ui.battle.guidedTraining.run.completed.size,0);assert.equal(ui.visible('restartConfirm'),false);assert.equal(ui.visible('trainingCoach'),true);});
