/** Controlled real-engine regressions for finite hero damage.
 * Elevated HP in lifetime fixtures avoids death stopping simulation; actual
 * damage/timers/queues are unchanged and test protection is never enabled.
 * BOWMASTER_TEST_DIST can select an isolated candidate; normal suite uses site.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
const dist=process.env.BOWMASTER_TEST_DIST??new URL('../site/dist/',import.meta.url).href;
const {FirstBattle}=await import(new URL('engine/first-battle.mjs',dist));
const {createStatusEffect}=await import(new URL('engine/special-projectiles.mjs',dist));
const {seededRandom}=await import(new URL('engine/combat.mjs',dist));
const {createMidgameDemoBattleOptions,prepareMidgameDemoBattle}=await import(new URL('midgame-demo.mjs',dist));
function fixture({highHp=true,random=()=>.5}={}){const b=new FirstBattle({random});b.enemies.step=()=>null;b.friendlyQueue.step=()=>null;b.hero.leaveGarrison();b.hero.x=1000;b.hero.y=b.elevationAt(1000);if(highHp)b.hero.hp=b.hero.maxHp=100000;return b;}
function run(b,n){for(let i=0;i<n;i++)b.step();}
function shots(b,kind){const source=kind==='trebuchet_ammo'?{type:'trebuchet',team:'good',recruited:true}:b.hero;return b.queueProjectile({kind,source,owner:source,team:'good',rank:2,x:b.hero.x,y:b.hero.y-20,vx:0,vy:0,impactDamage:150});}
function hit(b,kind){const p=shots(b,kind);if(kind==='hero_arrow')p.hit(b.hero);else if(kind==='flak_arrow')p.activate();else p.impact(b.hero);return p;}
function losses(b){const result=[],original=b.hero.takeDamage.bind(b.hero);b.hero.takeDamage=(amount,...args)=>{const hp=b.hero.hp;original(amount,...args);if(hp>b.hero.hp)result.push({tick:b.tick,amount:hp-b.hero.hp});};return result;}
function settled(b,{allowIce=false}={}){assert.ok(b.hero.hp>0);assert.ok(!b.protectedTesting);assert.equal(b.spells.length,0);assert.equal(b.projectiles.length,0);assert.equal(b.reactiveElements.length,0);assert.ok(b.hero.effects.effects.every(e=>allowIce&&e.kind==='ice'));const hp=b.hero.hp;run(b,2000);assert.equal(b.hero.hp,hp,'health must remain stable after every harmful source expired');}
for(const kind of ['hero_arrow','bomb_arrow','flak_arrow','bomb_wave_arrow','fire_wave_arrow','ice_wave_arrow','meteor','meteor_arrow','fire_arrow','ice_arrow','poison_arrow','trebuchet_ammo','comet_arrow'])test(`one ${kind} impact cannot create permanent hero health loss`,()=>{const b=fixture(),trace=losses(b);hit(b,kind);run(b,3000);assert.ok(trace.length>0);assert.ok(trace.at(-1).tick<1000);settled(b);});
test('Comet direct long ice status does not keep dealing damage',()=>{const b=fixture(),trace=losses(b);hit(b,'comet');run(b,3000);assert.equal(trace.length,2);assert.ok(b.hero.effects.effects.some(e=>e.kind==='ice'&&e.duration>90000));settled(b,{allowIce:true});});
test('ordinary allied siege blast is finite without hero protection or raised HP',()=>{const b=fixture({highHp:false}),trace=losses(b);hit(b,'trebuchet_ammo');run(b,500);assert.equal(trace.length,2);assert.equal(b.hero.hp,146);settled(b);});
test('paused poison/impact timers do not tick or restart on resume',()=>{const b=fixture(),trace=losses(b);hit(b,'poison_arrow');run(b,30);const hp=b.hero.hp,tick=b.tick,durations=b.hero.effects.effects.map(e=>e.duration);b.paused=true;run(b,1000);assert.equal(b.tick,tick);assert.equal(b.hero.hp,hp);assert.deepEqual(b.hero.effects.effects.map(e=>e.duration),durations);b.paused=false;run(b,1000);assert.equal(trace.length,16);settled(b);});
test('attached fire expires while hero leaves and reenters the keep',()=>{const b=fixture(),trace=losses(b);b.hero.x=b.goodCastle.x;b.hero.y=b.goodCastle.y;hit(b,'fire_arrow');run(b,10);assert.equal(b.hero.garrisonInto(b.goodCastle),true);run(b,45);b.hero.leaveGarrison();run(b,40);assert.equal(b.hero.garrisonInto(b.goodCastle),true);run(b,500);assert.equal(trace.length,11);settled(b);});
test('four stacked fire statuses and rejected fifth still expire',()=>{const b=fixture(),trace=losses(b);for(let i=0;i<4;i++)assert.equal(b.hero.effects.add(createStatusEffect({kind:'fire',target:b.hero,duration:60+i*5,interval:20,damage:5})).status,'accepted');assert.equal(b.hero.effects.add(createStatusEffect({kind:'fire',target:b.hero,duration:60,damage:5})).status,'full');run(b,500);assert.equal(trace.length,15);assert.deepEqual(b.hero.effects.occupied,[false,false,false,false]);settled(b);});
test('fire/ice cancellation removes the old damage status without a detached timer',()=>{const b=fixture(),trace=losses(b);b.hero.effects.add(createStatusEffect({kind:'fire',target:b.hero,duration:300,damage:5}));run(b,5);assert.equal(b.hero.effects.add(createStatusEffect({kind:'ice',target:b.hero,duration:900})).status,'canceled');run(b,500);assert.equal(trace.length,1);settled(b);});
test('removing a poison shooter leaves finite poison and corpse cleanup cannot restart it',()=>{const b=fixture(),trace=losses(b),enemy=b.createUnit('poisonDragon');enemy.x=1400;enemy.y=b.elevationAt(1400)-180;const p=b.queueProjectile({kind:'poison_arrow',source:enemy,team:'bad',rank:2,x:b.hero.x,y:b.hero.y-20,vx:0,vy:0});p.impact(b.hero);enemy.takeDamage(enemy.hp);run(b,1500);assert.equal(enemy.destroyed,true);assert.equal(b.objects.items.includes(enemy),false);assert.equal(trace.length,16);settled(b);});
test('clearing pending impacts and destroying active fields stops all harm immediately',()=>{const b=fixture();hit(b,'fire_arrow');run(b,30);for(const r of [...b.reactiveElements])r.destroy();for(const e of [...b.hero.effects.effects])b.hero.effects.remove(e);const hp=b.hero.hp;run(b,1000);assert.equal(b.hero.hp,hp);settled(b);});
test('hero terrain/garrison motion has no latent falling damage after a single ordinary hit',()=>{const b=fixture(),trace=losses(b);hit(b,'hero_arrow');run(b,1);b.input.left=true;run(b,1000);b.input.left=false;b.input.right=true;run(b,1000);b.input.right=false;run(b,1000);assert.equal(trace.length,1);assert.ok(Number.isFinite(b.hero.x)&&Number.isFinite(b.hero.y));settled(b);});
test('repeated friendly siege splash stops after the final real blast',()=>{const b=fixture(),trace=losses(b);for(let i=0;i<5;i++){const p=shots(b,'trebuchet_ammo');p.impact(null);run(b,300);}assert.equal(trace.length,5);assert.deepEqual(trace.map(e=>e.tick),[2,302,602,902,1202]);settled(b);});
test('full defeat countdown cannot continue hero damage or a dead actor status',()=>{const b=fixture({highHp:false}),trace=losses(b);hit(b,'poison_arrow');while(!b.outcome&&b.tick<1000)b.step();assert.equal(b.outcome,'defeat');const hp=b.hero.hp,count=trace.length,durations=b.hero.effects.effects.map(e=>e.duration);run(b,300);assert.ok(b.summary);assert.equal(b.hero.hp,hp);assert.equal(trace.length,count);assert.deepEqual(b.hero.effects.effects.map(e=>e.duration),durations);});
test('real demo damage has no silent drain after active combat sources are removed',()=>{const b=new FirstBattle(createMidgameDemoBattleOptions());prepareMidgameDemoBattle(b);b.hero.leaveGarrison();b.hero.x=800;b.hero.y=b.elevationAt(800);const trace=losses(b);while(!trace.length&&b.tick<5000)b.step();assert.ok(trace.length);assert.ok(b.hero.hp>0);b.enemies.step=()=>null;b.friendlyQueue.step=()=>null;for(const unit of [...b.goodTeam,...b.badTeam])if(unit!==b.hero)unit.destroy();for(const p of [...b.projectiles])p.destroy();for(const s of [...b.spells])s.destroy();for(const r of [...b.reactiveElements])r.destroy();for(const e of [...b.hero.effects.effects])b.hero.effects.remove(e);const hp=b.hero.hp;run(b,1500);assert.equal(b.hero.hp,hp);assert.equal(trace.length,1);});
