import test from 'node:test';import assert from 'node:assert/strict';
import {loadGameUI} from './helpers/game-ui-harness.mjs';
import {DEFAULT_SKIRMISH,encodeSkirmishDescriptor} from '../site/dist/skirmish-model.mjs';
import {levyFeedbackState} from '../site/dist/levy-presentation.mjs';
const search='?mode=skirmish&sk='+encodeURIComponent(encodeSkirmishDescriptor({...DEFAULT_SKIRMISH,seed:42,doctrine:'levy'}));
async function ready(t){const ui=await loadGameUI(t,{search});ui.click('skirmishPrepare');ui.click('start');ui.frames(3);ui.click('battlePause');ui.click('pauseQueue');ui.click('armyMusterTab');return ui;}
test('preparation discloses finite schedule and disables call without advancing simulation',async t=>{const ui=await loadGameUI(t,{search});assert.match(ui.get('skirmishPreview').textContent,/45s: Rider counterattack/);ui.click('skirmishPrepare');ui.click('introArmy');ui.click('armyMusterTab');assert.equal(ui.battle.tick,0);assert.equal(ui.visible('armyLevies'),true);assert.equal(ui.get('armyCallLevies').disabled,true);assert.match(ui.get('armyLevyDetail').textContent,/Start the field first/);});
test('actual Army handler commits once in pause and resumes five identified levies',async t=>{const ui=await ready(t),b=ui.battle,tick=b.tick,gold=b.profile.gold,reserve=b.friendlyQueue.population,handler=ui.get('armyCallLevies').onclick;assert.equal(ui.get('armyCallLevies').disabled,false);ui.click('armyCallLevies');handler();ui.frames(10);assert.equal(b.tick,tick);assert.equal(b.auxiliaries.snapshot.pending,5);assert.equal(b.auxiliaries.snapshot.wavesCalled,1);assert.equal(b.profile.gold,gold);assert.equal(b.friendlyQueue.population,reserve);assert.match(ui.get('armyLevyCounts').textContent,/5 arriving/);ui.click('closeQueue');ui.click('resumeGame');ui.frames(105);assert.equal(b.auxiliaries.snapshot.occupied,5);ui.click('battlePause');ui.click('pauseQueue');ui.click('armyMusterTab');assert.match(ui.get('armyLevyRoster').textContent,/L · Wave 1/);assert.match(ui.get('armyLevyCounts').textContent,/Your army 0\/14 · Levies 5\/10/);handler();assert.equal(b.auxiliaries.snapshot.wavesCalled,1);});
test('stale callback cannot spend after replacing the practice attempt',async t=>{const ui=await ready(t),old=ui.battle,handler=ui.get('armyCallLevies').onclick;ui.click('closeQueue');ui.click('pauseWorkshop');ui.click('skirmishPrepare');ui.click('skirmishReplaceAttempt');ui.frames();const next=ui.battle;assert.notEqual(next,old);handler();assert.equal(old.auxiliaries.snapshot.wavesCalled,0);assert.equal(next.auxiliaries.snapshot.wavesCalled,0);});
test('settled read-only and repeated Muster/Contracts navigation preserve finite budget',async t=>{const ui=await ready(t),b=ui.battle;for(let i=0;i<25;i++){ui.click('armyContractsTab');ui.click('armyMusterTab');}assert.equal(b.auxiliaries.snapshot.wavesCalled,0);const handler=ui.get('armyCallLevies').onclick;b.finishOutcome('defeat');handler();assert.equal(b.auxiliaries.snapshot.wavesCalled,0);assert.equal(ui.get('armyCallLevies').disabled,true);});
test('ordinary Army hides all levy-only controls',async t=>{const ui=await loadGameUI(t,{search:'?mode=demo'});ui.click('introArmy');ui.click('armyMusterTab');assert.equal(ui.visible('armyLevies'),false);assert.equal(ui.battle.auxiliaries,undefined);});
test('Hall states actual keep/field/home flag objective and future finite waves',async t=>{const ui=await loadGameUI(t,{search});ui.click('skirmishPrepare');assert.match(ui.get('hallOrderObjective').textContent,/Break the enemy keep/);assert.match(ui.get('hallOrderAdvice').textContent,/four finite waves/);assert.match(ui.get('hallOrderAdvice').textContent,/160s/);});
test('integrated hooks reuse existing progress instruments and pause objective brief',async t=>{const ui=await loadGameUI(t,{search});ui.click('skirmishPrepare');ui.frames();assert.equal(ui.get('combatBattleTitle').textContent,'Levy defense');assert.equal(ui.get('combatEnemyState').textContent,'Break the enemy keep');assert.match(ui.get('viewStatus').textContent,/Levy defense/);assert.match(ui.get('batteryObjectiveBrief').textContent,/Protect your hero, home keep/);assert.equal(ui.visible('batteryObjectiveBrief'),true);});
for(const cause of ['hero','flag','keep'])test(`integrated result explains actual ${cause} defeat`,async t=>{const ui=await loadGameUI(t,{search});ui.click('skirmishPrepare');ui.click('start');ui.frames(3);const b=ui.battle;if(cause==='hero')b.hero.hp=0;else if(cause==='flag')b.ownFlag.status=4;else b.goodCastle.takeDamage(b.goodCastle.hp);ui.frames(2);assert.equal(ui.get('battleStatus').textContent,cause==='hero'?'Your hero fell.':cause==='flag'?'Your home flag was captured.':'Your home keep fell.');ui.frames(108);assert.equal(ui.get('endingTitle').textContent,'Defense lost');assert.match(ui.get('endingText').textContent,cause==='hero'?/Your hero fell/:cause==='flag'?/Your home flag was captured/:/Your home keep fell/);assert.equal(levyFeedbackState(b).status,'Defense lost');});
test('integrated victory and retry restore new identities and ordinary fresh practice kit',async t=>{const ui=await loadGameUI(t,{search});ui.click('skirmishPrepare');const b=ui.battle;b.badCastle.takeDamage(b.badCastle.hp);ui.click('start');ui.frames(110);assert.equal(ui.get('endingTitle').textContent,'Defense won');assert.match(ui.get('endingText').textContent,/Enemy keep broken, field cleared and home flag safe/);ui.click('replay');ui.frames();assert.notEqual(ui.battle,b);assert.equal(ui.battle.auxiliaries.snapshot.wavesLeft,4);assert.equal(ui.battle.profile.gold,1200);assert.equal(ui.get('combatEnemyState').textContent,'Break the enemy keep');});
test('levy keep-fall announcement requires cleanup and home flag, never enemy flag capture',async t=>{const ui=await loadGameUI(t,{search});ui.click('skirmishPrepare');ui.click('start');ui.frames(60);const b=ui.battle;assert.ok(b.badTeam.length>0);b.enemyFlag.status=4;b.badCastle.takeDamage(b.badCastle.hp);assert.match(ui.get('battleStatus').textContent,/Clear the remaining army and restore your home flag\./);assert.doesNotMatch(ui.get('battleStatus').textContent,/capture their flag/);assert.equal(b.outcome,null);assert.equal(b.enemies.remaining,0);});
test('ordinary CTF keep-fall announcement retains its unchanged flag alternative',async t=>{const ui=await loadGameUI(t,{search:'?mode=skirmish'});ui.click('skirmishPrepare');ui.click('start');ui.frames(60);const b=ui.battle;b.badCastle.takeDamage(b.badCastle.hp);assert.match(ui.get('battleStatus').textContent,/Defeat the remaining army or capture their flag\./);assert.equal(b.auxiliaries,undefined);});
for(const cause of ['hero','flag'])test(`ordinary CTF immediate ${cause} outcome wording remains unchanged`,async t=>{const ui=await loadGameUI(t,{search:'?mode=skirmish'});ui.click('skirmishPrepare');ui.click('start');ui.frames(3);const b=ui.battle;if(cause==='hero')b.hero.dead=true;else b.ownFlag.status=4;b.checkOutcome();assert.equal(b.outcome,'defeat');assert.equal(ui.get('battleStatus').textContent,cause==='hero'?'Your hero fell':'The enemy captured your flag');});
test('immediate levy status lists simultaneous authoritative keep and flag losses',async t=>{const ui=await loadGameUI(t,{search});ui.click('skirmishPrepare');ui.click('start');ui.frames(3);const b=ui.battle;b.objects.add({step(){b.goodCastle.hp=0;b.ownFlag.status=4;}});ui.frames(2);assert.equal(b.outcome,'defeat');assert.equal(ui.get('battleStatus').textContent,'Your home flag was captured. Your home keep fell.');assert.deepEqual(b.levyDefeatCauses,['flag','keep']);});
