import test from 'node:test';import assert from 'node:assert/strict';
import {CampaignBattle} from '../site/dist/engine/first-battle.mjs';
import {PlayerProfile} from '../site/dist/engine/progression.mjs';
import {seededRandom} from '../site/dist/engine/combat.mjs';
import {createLiveSkillAdapter} from '../site/dist/live-skill-adapter.mjs';
function fixture(){const p=new PlayerProfile('Adapter audit');p.gold=200;const fire=p.addSkill('fireArrow'),grunt=p.addSkill('grunt'),archer=p.addSkill('archer');fire.binding=1;grunt.binding=10;archer.binding=20;for(const s of p.skills){s.cooldown=0;s.autocast=false;}const battle=new CampaignBattle({profile:p,random:seededRandom(1234)});battle.hotbar.bar=0;battle.hotbar.select(0);battle.activeSkill=battle.hotbar.active;const results=[],adapter=createLiveSkillAdapter(battle,{onSummonResult:r=>results.push(r)});return {battle,adapter,results,arrow:p.skills[0],fire,grunt,archer};}
const aim={canFire:true,vx:20,vy:-10};
const tick=f=>{f.adapter.beforeTick();f.battle.step();f.adapter.afterTick();};
test('immediate bow selection fires the chosen skill in the next normal world tick',()=>{const f=fixture();f.adapter.choose(f.fire);assert.equal(f.battle.tick,0);assert.equal(f.battle.activeSkill,f.fire);f.battle.queuedAim=aim;tick(f);assert.deepEqual(f.battle.projectiles.map(p=>p.kind),['fire_arrow']);assert.equal(f.fire.cooldown,f.fire.maximum-2);});
test('summon identity survives immediate bow selection and later page switching',()=>{const f=fixture();f.adapter.choose(f.grunt);f.adapter.choose(f.fire);f.battle.hotbar.change(1);f.battle.activeSkill=f.battle.hotbar.active;f.battle.hotbar.change(1);f.battle.activeSkill=f.battle.hotbar.active;const visibleBar=f.battle.hotbar.bar,active=f.battle.activeSkill;tick(f);assert.equal(f.results[0].skill,f.grunt);assert.equal(f.results[0].accepted,true);assert.equal(f.battle.friendlyQueue.queue.length,4);assert.equal(f.battle.hotbar.bar,visibleBar);assert.equal(f.battle.activeSkill,active);assert.equal(f.grunt.cooldown,f.grunt.maximum-2);assert.equal(f.archer.cooldown,0);});
test('phase order stays shot, queued summon, held visible-page digits, cooldown; first unit waits until next tick',()=>{const f=fixture();f.adapter.choose(f.grunt);f.adapter.choose(f.fire);f.battle.queuedAim=aim;f.battle.input.digits=[0];tick(f);assert.equal(f.battle.projectiles[0].kind,'fire_arrow');assert.equal(f.battle.activeSkill,f.arrow);assert.equal(f.battle.goodTeam.length,1);assert.equal(f.battle.friendlyQueue.queue.length,4);assert.equal(f.grunt.cooldown,f.grunt.maximum-2);tick(f);assert.equal(f.battle.friendlyQueue.queue.length,4,'normal reinforcement timer, not an invented immediate spawn');});
test('two exact skill intents across bars are processed FIFO, one per normal tick',()=>{const f=fixture();f.adapter.choose(f.grunt);f.adapter.choose(f.archer);tick(f);tick(f);assert.deepEqual(f.results.map(r=>r.skill.id),['grunt','archer']);assert.deepEqual(f.results.map(r=>r.accepted),[true,true]);assert.equal(f.battle.profile.gold,160);assert.equal(f.battle.tick,2);});
test('pause/transition cancellation drops pending summon with no spend',()=>{const f=fixture();f.adapter.choose(f.grunt);f.battle.paused=true;f.adapter.clear();tick(f);assert.equal(f.battle.tick,0);assert.equal(f.battle.profile.gold,200);assert.equal(f.battle.friendlyQueue.queue.length,0);assert.equal(f.results.length,0);});
test('rebinding or removing a pending skill never summons a different slot occupant',()=>{const f=fixture();f.adapter.choose(f.grunt);f.grunt.binding=-1;f.battle.refreshHotbar();tick(f);assert.equal(f.results[0].cancelled,true);assert.equal(f.results[0].skill,f.grunt);assert.equal(f.battle.profile.gold,200);});
test('failed duplicate intent returns actual failure without a second spend',()=>{const f=fixture();f.adapter.choose(f.grunt);f.adapter.choose(f.grunt);tick(f);tick(f);assert.deepEqual(f.results.map(r=>r.accepted),[true,false]);assert.equal(f.battle.profile.gold,180);assert.equal(f.battle.friendlyQueue.queue.length,4);});

test('existing wheel phase still changes the page after queued summon processing',()=>{const f=fixture();f.adapter.choose(f.grunt);f.battle.hotbar.wheelEvent(-1);tick(f);assert.equal(f.results[0].accepted,true);assert.equal(f.battle.hotbar.bar,1);assert.equal(f.battle.activeSkill,f.grunt);});
test('held summon key after queued success cannot overwrite its success report',()=>{const f=fixture();f.battle.hotbar.bar=1;f.battle.hotbar.select(0);f.grunt.cooldown=0;f.battle.profile.gold=200;f.battle.friendlyQueue.queue=[];f.battle.friendlyQueue.population=20;f.adapter.choose(f.grunt);f.battle.input.digits=[0];tick(f);assert.equal(f.results[0].accepted,true);assert.equal(f.battle.profile.gold,180);});
test('refreshHotbar retains installed callbacks and queued identity follows a new resolved slot',()=>{const f=fixture(),hotbar=f.battle.hotbar,changed=hotbar.changed,activate=hotbar.activate;f.adapter.choose(f.grunt);f.grunt.binding=22;f.battle.refreshHotbar();assert.equal(f.battle.hotbar,hotbar);assert.equal(hotbar.changed,changed);assert.equal(hotbar.activate,activate);assert.equal(f.battle.activeSkill,f.archer,'rebuild selection contract remains unchanged');tick(f);assert.equal(f.results[0].skill,f.grunt);assert.equal(f.results[0].accepted,true);assert.equal(f.battle.hotbar.bar,2);assert.equal(f.battle.activeSkill,f.archer);});
test('outcome early return restores display and cancels the in-flight numeric selection without spend',()=>{const f=fixture();f.adapter.choose(f.grunt);const visibleBar=f.battle.hotbar.bar,active=f.battle.activeSkill;f.adapter.beforeTick();f.battle.finishOutcome('defeat');f.battle.step();f.adapter.afterTick();assert.equal(f.results[0].cancelled,true);assert.equal(f.results[0].accepted,false);assert.equal(f.battle.profile.gold,200);assert.equal(f.battle.friendlyQueue.queue.length,0);assert.equal(f.battle.hotbar.bar,visibleBar);assert.equal(f.battle.activeSkill,active);assert.equal(f.battle.queuedSelection,null);});
test('outcome triggered during the live frame still completes the existing raw selection and cooldown phases',()=>{const f=fixture();f.adapter.choose(f.grunt);f.battle.enemies.pending=['grunt'];f.battle.enemies.timer=0;f.battle.onEvent=e=>{if(e.type==='spawn')f.battle.finishOutcome('defeat');};tick(f);assert.equal(f.battle.outcome,'defeat');assert.equal(f.results[0].accepted,true);assert.equal(f.battle.friendlyQueue.queue.length,4);assert.equal(f.grunt.cooldown,f.grunt.maximum-2);});
