import test from 'node:test';import assert from 'node:assert/strict';
import {LoadoutCollection,loadoutPlacementPreview} from '../site/dist/loadout-collection-model.mjs';
import {buildArmoryRecords} from '../site/dist/armory-catalog-data.mjs';
import {SKILLS} from '../site/dist/engine/progression.mjs';import {COMPANIONS} from '../site/dist/engine/recruitment.mjs';
import {loadGameUI} from './helpers/game-ui-harness.mjs';
const records=buildArmoryRecords(SKILLS,COMPANIONS,{});
const input=(ui,id,value)=>{ui.get(id).value=value;ui.get(id).focus();ui.dispatch(ui.get(id),id==='loadoutSearch'?'input':'change');};
const type=(ui,id)=>ui.get('loadoutFilters').querySelector(`[data-loadout-type="${id}"]`).click();
async function editor(t){const ui=await loadGameUI(t,{search:'?mode=test'});ui.click('introTesting');ui.click('testUnlock');ui.click('closeTesting');ui.click('introLoadout');return ui;}

test('a thousand private-fixture cards remain paginated with contextual facets and deterministic sort',()=>{
 const fixtures=Array.from({length:1000},(_,n)=>({id:'fixture-'+n,kind:'skill',name:`Unit ${String(n).padStart(4,'0')}`,description:'Test-only ice ranged card',category:n%2?'army':'arrows',role:n%2?'ranged':'bow',traits:n%3?['ice']:['fire'],reloadSeconds:n%10,price:0}));
 const wrappers=fixtures.map((item,n)=>({skill:{id:item.id,rank:n%11},binding:n<30?n:-1})),model=new LoadoutCollection(fixtures);
 let result=model.query(wrappers);assert.equal(result.total,1000);assert.equal(result.items.length,12);assert.equal(result.pageCount,84);assert.equal(result.equipped,30);assert.equal(result.reserve,970);
 model.setView({page:83});result=model.query(wrappers);assert.equal(result.items.length,4);
 model.setView({type:'army',role:'ranged',trait:'ice',status:'reserve',sort:'rank'});result=model.query(wrappers);assert.ok(result.total>300);assert.ok(result.items.every(x=>x.item.category==='army'&&x.item.traits.includes('ice')&&x.wrapper.binding<0));assert.ok(result.items[0].wrapper.skill.rank>=result.items[11].wrapper.skill.rank);
 model.setView({type:'arrows'});assert.equal(model.view.role,'all');assert.equal(model.view.trait,'all');assert.equal(model.view.page,0);assert.deepEqual(model.query(wrappers).roles,[]);
 model.setView({query:'absent',page:99});assert.equal(model.query(wrappers).total,0);model.reveal('fixture-999',wrappers);assert.ok(model.query(wrappers).items.some(x=>x.item.id==='fixture-999'));
 assert.ok(!records.some(item=>item.id.startsWith('fixture-')));
});
test('collection filters and sort include only owned abilities, never companions or unavailable cards',()=>{
 const model=new LoadoutCollection(records),wrappers=[{skill:{id:'arrow',rank:0},binding:0},{skill:{id:'fireDragon',rank:4},binding:-1},{skill:{id:'priest',rank:2},binding:10}];
 assert.equal(model.query(wrappers).total,3);assert.ok(!model.byId.has('gorath'));model.setView({type:'army',role:'support'});assert.deepEqual(model.query(wrappers).items.map(x=>x.item.id),['priest']);model.setView({type:'arrows'});assert.equal(model.view.role,'all');assert.deepEqual(model.query(wrappers).items.map(x=>x.item.id),['arrow']);model.setView({type:'all',status:'reserve'});assert.deepEqual(model.query(wrappers).items.map(x=>x.item.id),['fireDragon']);
});
test('search/type/role/effect/status and page navigation render at most twelve identifiable cards',async t=>{
 const ui=await editor(t);assert.equal(ui.get('ownedSkillList').querySelectorAll('article').length,12);assert.match(ui.get('inventoryCount').textContent,/1–12 of 25/);ui.click('loadoutNext');assert.match(ui.get('loadoutPageLabel').textContent,/Page 2 of 3/);ui.click('loadoutNext');assert.equal(ui.get('ownedSkillList').querySelectorAll('article').length,1);assert.equal(ui.get('loadoutNext').disabled,true);
 type(ui,'army');assert.equal(ui.visible('loadoutRoleField'),true);input(ui,'loadoutRole','support');assert.equal(ui.get('ownedSkillList').querySelectorAll('article').length,1);assert.ok(ui.get('owned-priest'));type(ui,'arrows');assert.equal(ui.visible('loadoutRoleField'),false);assert.equal(ui.get('loadoutRole').value,'all');input(ui,'loadoutTrait','ice');assert.ok(ui.get('owned-iceArrow'));assert.ok(ui.get('owned-cometArrow'));input(ui,'loadoutSearch','missing');assert.equal(ui.get('ownedSkillList').querySelectorAll('article').length,0);ui.click('loadoutEmptyReset');assert.equal(ui.get('loadoutSearch').value,'');assert.equal(ui.document.activeElement,ui.get('loadoutSearch'));assert.ok(ui.get('owned-arrow'));
});
test('inspection is independent of the armed card, bar, filters, page and direct swap intent',async t=>{
 const ui=await editor(t),p=ui.battle.profile,fire=p.skills.find(s=>s.id==='fireArrow'),arrow=p.skills.find(s=>s.id==='arrow');ui.click('owned-fireArrow');input(ui,'loadoutSearch','ice');ui.document.querySelector('[data-loadout-bar="1"]').click();ui.click('loadout-inspect-iceArrow');assert.equal(ui.visible('loadoutInspector'),true);assert.equal(ui.get('selectedSkillName').textContent,'Ice Arrow');assert.match(ui.get('loadoutInspectorFacts').textContent,/Base direct hit/);assert.equal(ui.get('loadoutSelectionName').textContent,'Fire Arrow');assert.equal(fire.binding,1);ui.key('keydown','Escape');assert.equal(ui.visible('loadoutInspector'),false);assert.equal(ui.visible('skillsPanel'),true);assert.equal(ui.get('loadoutSearch').value,'ice');assert.equal(ui.document.activeElement,ui.get('loadout-inspect-iceArrow'));assert.equal(ui.document.querySelector('[data-loadout-bar="1"]').getAttribute('aria-pressed'),'true');ui.document.querySelector('[data-loadout-bar="0"]').click();ui.get('assign-0').focus();ui.dispatch(ui.get('assign-0'),'focus');assert.match(ui.get('slotInstruction').textContent,/Swap Fire Arrow with Basic Arrow/);ui.click('assign-0');assert.equal(fire.binding,0);assert.equal(arrow.binding,1);assert.equal(ui.get('loadoutSearch').value,'ice');assert.equal(ui.battle.tick,0);
});
test('reserve replacement retains ownership, cooldown and gold; equipped/reserve counts update immediately',async t=>{
 const ui=await editor(t),p=ui.battle.profile,fire=p.skills.find(s=>s.id==='fireArrow'),arrow=p.skills[0];fire.cooldown=41;const gold=p.gold;ui.document.querySelector('[data-loadout-bar="0"]').click();ui.click('owned-fireArrow');ui.click('unbindSkill');input(ui,'loadoutState','reserve');assert.equal(ui.get('ownedSkillList').querySelectorAll('article').length,1);ui.click('owned-fireArrow');ui.get('assign-0').focus();ui.dispatch(ui.get('assign-0'),'focus');assert.match(ui.get('slotInstruction').textContent,/Basic Arrow.*returns to reserve/);ui.click('assign-0');assert.equal(fire.binding,0);assert.equal(arrow.binding,-1);assert.equal(fire.cooldown,41);assert.equal(p.gold,gold);assert.equal(p.owned.size,25);assert.ok(ui.get('owned-arrow'));assert.match(ui.get('skillsResources').textContent,/24\/30 equipped · 1 in reserve/);
});
test('keyboard card activation moves focus to a physical key and Enter placement remains one action',async t=>{
 const ui=await editor(t);ui.document.querySelector('[data-loadout-bar="0"]').click();ui.dispatch(ui.get('owned-fireArrow'),'click',{detail:0});assert.equal(ui.document.activeElement?.id,'assign-0');assert.match(ui.get('assign-9').getAttribute('aria-label'),/key 0/);ui.click('assign-9');assert.equal(ui.battle.profile.skills.find(s=>s.id==='fireArrow').binding,9);assert.equal(ui.battle.tick,0);
});
test('typed collection survives child panels and current rank inspection does not mutate combat',async t=>{
 const ui=await editor(t);type(ui,'army');input(ui,'loadoutSearch','dragon');input(ui,'loadoutSort','name');ui.click('loadout-inspect-fireDragon');const p=ui.battle.profile,skill=p.skills.find(s=>s.id==='fireDragon'),before={rank:skill.rank,cooldown:skill.cooldown,gold:p.gold};assert.match(ui.get('loadoutInspectorNotes').textContent,/enemy-only/);ui.click('loadoutCloseInspector');ui.click('openQueue');ui.click('closeQueue');assert.equal(ui.get('loadoutSearch').value,'dragon');assert.equal(ui.get('loadoutSort').value,'name');assert.equal(ui.get('loadoutFilters').querySelector('[data-loadout-type="army"]').getAttribute('aria-pressed'),'true');assert.deepEqual({rank:skill.rank,cooldown:skill.cooldown,gold:p.gold},before);assert.equal(ui.battle.tick,0);
});
test('companion is kept out of physical keys and its panel names its independent command',async t=>{
 const ui=await editor(t);assert.equal(ui.get('ownedSkillList').querySelectorAll('[data-drag-ability="gorath"]').length,0);assert.match(ui.get('loadoutCompanionSummary').textContent,/Gorath · separate slot · G/);assert.equal(ui.battle.profile.skills.some(s=>s.id==='gorath'),false);assert.match(ui.get('bindingGrid').getAttribute('aria-label'),/Companions use their own slot/);
});

test('unarmed and cancelled editors never expose an ambiguous reserve target',async t=>{const ui=await editor(t),before=ui.battle.profile.skills.map(s=>s.binding);assert.equal(ui.get('unbindSkill').disabled,true);assert.equal(ui.get('loadoutInspectSelected').disabled,true);ui.click('unbindSkill');assert.deepEqual(ui.battle.profile.skills.map(s=>s.binding),before);ui.click('owned-fireArrow');assert.equal(ui.get('unbindSkill').disabled,false);ui.click('cancelBinding');assert.equal(ui.get('unbindSkill').disabled,true);assert.equal(ui.get('loadoutRevealSelected').disabled,true);});
test('reopening identical collection state refreshes wrappers before the next assignment',async t=>{const ui=await editor(t);input(ui,'loadoutSearch','fire arrow');ui.click('closeSkills');ui.click('introLoadout');ui.click('owned-fireArrow');ui.document.querySelector('[data-loadout-bar="0"]').click();ui.click('assign-0');assert.equal(ui.battle.profile.skills.find(s=>s.id==='fireArrow').binding,0);assert.equal(ui.battle.profile.skills.find(s=>s.id==='arrow').binding,1);});
test('companion equip changes refresh the collapsed separate-slot summary',async t=>{const ui=await editor(t);ui.click('equipCompanion');assert.match(ui.get('loadoutCompanionSummary').textContent,/^Companion/);ui.click('equipCompanion');assert.match(ui.get('loadoutCompanionSummary').textContent,/^Gorath/);});

test('empty type in a new campaign recovers to its starting owned card',async t=>{const ui=await loadGameUI(t);ui.click('introLoadout');type(ui,'army');assert.equal(ui.get('ownedSkillList').querySelectorAll('article').length,0);assert.equal(ui.get('loadoutClearFilters').disabled,false);ui.click('loadoutEmptyReset');assert.ok(ui.get('owned-arrow'));assert.equal(ui.get('loadoutFilters').querySelector('[data-loadout-type="all"]').getAttribute('aria-pressed'),'true');});
