import test from 'node:test';import assert from 'node:assert/strict';
import {loadGameUI} from './helpers/game-ui-harness.mjs';
const tab=(ui,n)=>ui.document.querySelector(`[data-loadout-bar="${n}"]`).click();
function unlock(ui){ui.click('introTesting');ui.click('testGoldLarge');ui.click('testUnlock');ui.click('closeTesting');}
test('preparation loadout assigns a physical slot without starting until Begin',async t=>{const ui=await loadGameUI(t,{search:'?mode=test'});unlock(ui);ui.click('introLoadout');const same=ui.battle;ui.click('owned-fireArrow');tab(ui,2);ui.click('assign-25');assert.equal(ui.battle.profile.skills.find(s=>s.id==='fireArrow').binding,25);assert.equal(ui.battle.tick,0);assert.equal(ui.battle.stats.shotsFired,0);assert.equal(ui.visible('skillsPanel'),true);ui.click('loadoutContinue');assert.equal(ui.battle,same);assert.equal(ui.visible('intro'),false);assert.equal(ui.visible('skillsPanel'),false);ui.frames();assert.ok(ui.battle.tick>0);});
test('assignment handles a displaced skill explicitly and retains timers and gold',async t=>{const ui=await loadGameUI(t,{search:'?mode=test'});unlock(ui);const fire=ui.battle.profile.skills.find(s=>s.id==='fireArrow'),arrow=ui.battle.profile.skills[0];fire.cooldown=123;ui.click('introLoadout');ui.click('owned-fireArrow');tab(ui,0);ui.click('assign-0');assert.match(ui.get('bindingStatus').textContent,/swapped places/);assert.equal(arrow.binding,1,'modern UI swaps both persisted positions');ui.click('owned-arrow');ui.click('unbindSkill');assert.equal(arrow.binding,-1);assert.equal(fire.binding,0);assert.equal(fire.cooldown,123);assert.equal(ui.battle.profile.gold,10000);ui.click('closeSkills');assert.equal(ui.visible('intro'),true);assert.equal(ui.battle.tick,0);});
test('paused loadout Done keeps explicit Pause and does not cast troop inventory selection',async t=>{const ui=await loadGameUI(t,{search:'?mode=test'});unlock(ui);ui.click('start');ui.frames();ui.click('battlePause');const tick=ui.battle.tick,gold=ui.battle.profile.gold;ui.click('pauseSkills');ui.get('loadoutFilters').querySelector('[data-loadout-type="army"]').click();ui.click('owned-priest');tab(ui,2);ui.click('assign-29');ui.click('loadoutContinue');ui.frames(3);assert.equal(ui.battle.paused,true);assert.equal(ui.battle.tick,tick);assert.equal(ui.battle.profile.gold,gold);assert.equal(ui.battle.friendlyQueue.queue.length,0);assert.equal(ui.visible('pauseOverlay'),true);});
test('assisted victory → purchase → loadout → Begin preserves the camp until explicit launch',async t=>{const ui=await loadGameUI(t,{search:'?mode=test'});ui.click('introTesting');ui.click('testGoldLarge');ui.click('testVictory');ui.frames(105);const ended=ui.battle;ui.click('endingShop');ui.click('buy-fireArrow');ui.click('shopLoadout');assert.equal(ui.battle,ended);assert.equal(ui.battle.summary.outcome,'victory');ui.click('owned-fireArrow');tab(ui,1);ui.click('assign-14');ui.click('loadoutArmory');assert.equal(ui.visible('shopPanel'),true);assert.equal(ui.battle,ended);ui.click('shopLoadout');ui.click('loadoutContinue');assert.notEqual(ui.battle,ended);assert.equal(ui.battle.level,2);assert.equal(ui.battle.profile.skills.find(s=>s.id==='fireArrow').binding,14);assert.equal(ui.battle.profile.gold,9000);assert.equal(ui.visible('intro'),false);assert.equal(ui.visible('skillsPanel'),false);});
test('defeat camp Back and Escape preserve results until Retry',async t=>{const ui=await loadGameUI(t,{search:'?mode=test'});ui.click('introTesting');ui.click('testDefeat');ui.frames(105);const ended=ui.battle;ui.click('endingLoadout');ui.key('keydown','Escape');assert.equal(ui.battle,ended);assert.equal(ui.visible('ending'),true);ui.click('endingLoadout');assert.match(ui.get('loadoutContinue').textContent,/Retry battle 1/);ui.click('loadoutContinue');assert.notEqual(ui.battle,ended);assert.equal(ui.battle.level,1);assert.equal(ui.battle.outcome,null);});
test('completed campaign loadout cannot silently begin an invalid battle 31',async t=>{const ui=await loadGameUI(t,{search:'?mode=test'});ui.click('introTesting');ui.get('testLevel').value='30';ui.click('testLevelApply');ui.click('introTesting');ui.click('testVictory');ui.frames(105);ui.click('endingLoadout');assert.equal(ui.get('loadoutContinue').textContent,'Back to results');assert.equal(ui.visible('loadoutArmory'),false);ui.click('loadoutContinue');assert.equal(ui.battle.level,30);assert.equal(ui.battle.summary.campaignComplete,true);assert.equal(ui.visible('ending'),true);});

test('Army settings opened from Loadout return to that editor without starting a battle',async t=>{const ui=await loadGameUI(t);ui.click('introLoadout');ui.click('openQueue');ui.click('closeQueue');assert.equal(ui.visible('skillsPanel'),true);assert.equal(ui.battle.tick,0);ui.click('openQueue');ui.key('keydown','Escape');assert.equal(ui.visible('skillsPanel'),true);assert.equal(ui.battle.tick,0);});
