import test from 'node:test';import assert from 'node:assert/strict';
import {loadGameUI,deferredFile} from './helpers/game-ui-harness.mjs';
import {CampaignProfiles} from '../site/dist/engine/profile-manager.mjs';
import {PlayerProfile} from '../site/dist/engine/progression.mjs';
import {createLocalCampaignStore,checkpointSlotKey,snapshotCampaign} from '../site/dist/local-campaign-store.mjs';
import {TestLocks,settle} from './helpers/local-storage.mjs';
import {CampaignBattle} from '../site/dist/engine/first-battle.mjs';
class Storage{constructor(){this.data=new Map();this.writes=0;}getItem(k){return this.data.get(k)??null;}setItem(k,v){this.data.set(k,String(v));this.writes++;}removeItem(k){this.data.delete(k);}}
async function saved(storage,{name='Kept',gold=456,level=4,assisted=false}={}){const p=new PlayerProfile(name);p.gold=gold;p.highestLevel=level;p.cheated=assisted;const profiles=new CampaignProfiles({profiles:[p]}),battle=new CampaignBattle({profile:p,level}),store=createLocalCampaignStore({storage,locks:new TestLocks()});await store.write(1,snapshotCampaign({profiles,battle}));return store;}
const localButton=(ui,action,slot=1)=>ui.get('localSlots').querySelector(`[data-local-${action}="${slot}"]`).click();

test('first-time campaign quietly autosaves and starts without a slot gate',async t=>{const storage=new Storage(),ui=await loadGameUI(t,{storage}),store=createLocalCampaignStore({storage,locks:new TestLocks()});assert.equal(ui.visible('localHubChoices'),false);assert.equal(store.read(1).latest.manager.active.name,'Castledecks');ui.click('start');await ui.settle();assert.equal(ui.visible('intro'),false);assert.equal(store.read(1).latest.payload.resume.phase,'opening');assert.equal(storage.writes,2);ui.frames(8);assert.equal(storage.writes,2);});
test('existing save is never overwritten on boot and Continue requires explicit confirmation',async t=>{const storage=new Storage(),store=await saved(storage),before=[...storage.data],ui=await loadGameUI(t,{storage});assert.deepEqual([...storage.data],before);assert.equal(ui.visible('localHubChoices'),true);ui.click('localContinue');await ui.settle();assert.equal(ui.visible('savePanel'),true);assert.equal(ui.visible('localConfirm'),true);assert.equal(ui.battle.profile.name,'Castledecks');ui.click('localConfirmAccept');await ui.settle();assert.equal(ui.battle.profile.name,'Kept');assert.equal(ui.battle.profile.gold,456);assert.equal(ui.battle.level,4);assert.equal(ui.battle.tick,0);assert.equal(ui.visible('intro'),true);assert.deepEqual([...storage.data],before);ui.click('start');await ui.settle();ui.click('start');await ui.settle();assert.equal(store.read(1).latest.manager.active.gold,456);assert.equal(ui.battle.profile.gold,456);});
test('start with existing saves presents a choice, and Session only retains every save',async t=>{const storage=new Storage();await saved(storage);const before=[...storage.data],ui=await loadGameUI(t,{storage});ui.click('start');await ui.settle();assert.equal(ui.battle.tick,0);assert.equal(ui.visible('savePanel'),true);ui.click('localSessionOnlyVault');await ui.settle();ui.click('closeSave');await ui.settle();ui.click('start');await ui.settle();ui.frames();assert.ok(ui.battle.tick>0);assert.deepEqual([...storage.data],before);});
test('new campaign uses a free slot and keeps prior campaign',async t=>{const storage=new Storage(),store=await saved(storage),before=store.read(1).raw,ui=await loadGameUI(t,{storage});ui.click('localNew');await ui.settle();ui.click('localConfirmAccept');await ui.settle();assert.deepEqual(store.read(1).raw,before);assert.equal(store.read(2).latest.manager.active.name,'Castledecks');assert.equal(ui.visible('intro'),true);});
test('import is staged, cancellation preserves running campaign, acceptance uses a new slot',async t=>{const storage=new Storage(),ui=await loadGameUI(t,{storage}),store=createLocalCampaignStore({storage,locks:new TestLocks()}),original=ui.battle;const p=new PlayerProfile('Imported');p.gold=3001;p.highestLevel=7;const bundle=new CampaignProfiles({profiles:[p]}).exportBundle();ui.click('introLoad');await ui.settle();ui.get('loadCode').value=bundle;ui.click('importCode');await ui.settle();assert.equal(ui.battle,original);assert.equal(ui.visible('localConfirm'),true);ui.click('localConfirmCancel');await ui.settle();assert.equal(ui.battle,original);ui.click('importCode');await ui.settle();ui.click('localConfirmAccept');await ui.settle();assert.equal(ui.battle.profile.name,'Imported');assert.equal(ui.battle.level,7);assert.equal(ui.battle.profile.gold,3001);assert.equal(store.read(1).latest.manager.active.name,'Castledecks');assert.equal(store.read(2).latest.manager.active.name,'Imported');ui.click('introArmory');await ui.settle();ui.click('shopCatalogTab');await ui.settle();ui.click('buy-pierceArrow');await ui.settle();assert.equal(ui.battle.profile.gold,1);assert.equal(store.read(2).latest.manager.active.gold,1);assert.equal(store.read(2).latest.manager.active.owned.has('pierceArrow'),true);});
test('active battlefield gains and army expenses do not mutate local opening checkpoint',async t=>{const storage=new Storage(),ui=await loadGameUI(t,{storage}),store=createLocalCampaignStore({storage,locks:new TestLocks()});ui.battle.profile.gold=3001;ui.click('start');await ui.settle();const before=store.read(1).latest.payload;ui.battle.profile.gold=2500;ui.battle.profile.addXP(333);ui.click('battlePause');await ui.settle();ui.click('pauseLobby');await ui.settle();ui.click('introSave');await ui.settle();assert.deepEqual(store.read(1).latest.payload,before);assert.match(ui.get('localVaultStatus').textContent,/battle-opening/);ui.click('closeSave');await ui.settle();ui.frames(30);assert.deepEqual(store.read(1).latest.payload,before);});
test('pending file and staged import are cancelled by navigation',async t=>{const storage=new Storage(),ui=await loadGameUI(t,{storage}),old=ui.battle,deferred=deferredFile();ui.click('introLoad');await ui.settle();const promise=ui.load(deferred.file);ui.click('closeSave');await ui.settle();deferred.resolve(new CampaignProfiles({defaultName:'Late'}).exportBundle());await promise;assert.equal(ui.battle,old);ui.click('introLoad');await ui.settle();ui.get('loadCode').value=new CampaignProfiles({defaultName:'Stage'}).exportBundle();ui.click('importCode');await ui.settle();ui.click('closeSave');await ui.settle();ui.click('introSave');await ui.settle();assert.equal(ui.visible('localConfirm'),false);ui.click('localConfirmAccept');await ui.settle();assert.equal(ui.battle,old);});
test('practice does not create, mutate, or mark campaign local saves',async t=>{for(const search of ['?mode=test','?mode=demo','?mode=demo&showcase=companions'])await t.test(search,async t=>{const storage=new Storage(),store=await saved(storage),before=store.read(1).raw,ui=await loadGameUI(t,{search,storage});ui.click('start');await ui.settle();ui.frames(3);ui.click('battlePause');await ui.settle();ui.click('saveGame');await ui.settle();assert.equal(ui.visible('localSaveManager'),false);assert.deepEqual(store.read(1).raw,before);assert.equal(storage.data.size,1);});});
test('unavailable storage remains playable and exposes manual export',async t=>{const ui=await loadGameUI(t);assert.match(ui.get('localHubStatus').textContent,/unavailable/);ui.click('start');await ui.settle();ui.frames();assert.ok(ui.battle.tick>0);ui.click('battlePause');await ui.settle();ui.click('saveGame');await ui.settle();ui.click('showSaveCode');await ui.settle();assert.match(ui.get('saveCode').value,/bowmaster-reconstruction-profiles-2/);});
test('corrupt newest save explicitly recovers valid older copy',async t=>{const storage=new Storage(),store=await saved(storage),first=store.read(1);await store.write(1,first.latest.payload,{expected:first.raw});storage.setItem(checkpointSlotKey(1,'b'),'corrupt');const ui=await loadGameUI(t,{storage});ui.click('localContinue');await ui.settle();assert.match(ui.get('localSlots').textContent,/unreadable/);ui.click('localConfirmAccept');await ui.settle();assert.equal(ui.battle.profile.name,'Kept');assert.match(ui.get('introNotice').textContent,/Recovered/);});
test('delete confirmation has no effects until accepted and preserves in-memory session',async t=>{const storage=new Storage(),ui=await loadGameUI(t,{storage}),store=createLocalCampaignStore({storage,locks:new TestLocks()}),battle=ui.battle;ui.click('introSave');await ui.settle();localButton(ui,'delete');await ui.settle();ui.click('localConfirmCancel');await ui.settle();assert.ok(store.read(1).latest);localButton(ui,'delete');await ui.settle();ui.click('localConfirmAccept');await ui.settle();assert.equal(store.read(1).status,'empty');assert.equal(ui.battle,battle);ui.click('closeSave');await ui.settle();ui.click('start');await ui.settle();assert.equal(store.read(1).status,'empty');});
test('natural settlement checkpoints exactly once, after reward, and Continue never re-awards',async t=>{const storage=new Storage(),ui=await loadGameUI(t,{storage}),store=createLocalCampaignStore({storage,locks:new TestLocks()});ui.click('start');await ui.settle();const opening=store.read(1).latest.payload;ui.battle.finishOutcome('victory');assert.equal(ui.battle.summary,null);assert.deepEqual(store.read(1).latest.payload,opening);ui.frames(105);await ui.settle();const ended=ui.battle,gold=ended.profile.gold,won=store.read(1);assert.equal(won.latest.payload.resume.phase,'result');assert.equal(won.latest.payload.resume.level,2);assert.equal(won.latest.manager.active.victories,1);assert.equal(won.latest.manager.active.gold,gold);const writes=storage.writes;ui.frames(30);assert.equal(storage.writes,writes);ui.click('endingLobby');await ui.settle();ui.click('introSave');await ui.settle();localButton(ui,'continue');await ui.settle();ui.click('localConfirmAccept');await ui.settle();assert.equal(ui.battle.level,2);assert.equal(ui.battle.profile.gold,gold);assert.equal(ui.battle.profile.victories,1);ui.click('start');await ui.settle();ui.frames(3);assert.equal(ui.battle.profile.gold,gold);assert.equal(ui.battle.profile.victories,1);});
test('a real purchased squad charge is rolled back to opening on explicit checkpoint reload',async t=>{const storage=new Storage(),ui=await loadGameUI(t,{storage}),store=createLocalCampaignStore({storage,locks:new TestLocks()});ui.battle.profile.gold=1101;assert.equal(ui.battle.profile.purchase('grunt'),true);ui.battle.refreshHotbar();assert.equal(ui.battle.profile.gold,101);ui.click('start');await ui.settle();const saved=store.read(1).latest;ui.battle.profile.skills.find(s=>s.id==='grunt').cooldown=0;ui.frames(40);assert.equal(ui.battle.profile.gold,81);ui.click('battlePause');await ui.settle();ui.click('saveGame');await ui.settle();localButton(ui,'continue');await ui.settle();ui.click('localConfirmAccept');await ui.settle();assert.equal(ui.battle.profile.gold,101);assert.equal(ui.battle.friendlyQueue.queue.length,0);assert.equal(ui.battle.friendlyQueue.population,20);assert.equal(ui.battle.projectiles.length,0);assert.equal(ui.battle.profile.victories,0);assert.equal(saved.manager.active.gold,101);});
test('same-tab practice and return keep the exact campaign plus its isolated local slot',async t=>{const storage=new Storage(),ui=await loadGameUI(t,{storage}),store=createLocalCampaignStore({storage,locks:new TestLocks()}),campaign=ui.battle;ui.click('start');await ui.settle();ui.frames(3);ui.click('battlePause');await ui.settle();ui.click('pauseLobby');await ui.settle();const before=store.read(1).raw,tick=campaign.tick;ui.get('hubDestinations').querySelector('[data-hub-destination="training"]').click();ui.click('start');await ui.settle();ui.click('confirmSessionSwitch');await ui.settle();ui.click('introTesting');await ui.settle();ui.click('testGoldLarge');await ui.settle();ui.click('testUnlock');await ui.settle();ui.click('closeTesting');await ui.settle();assert.deepEqual(store.read(1).raw,before);ui.get('hubDestinations').querySelector('[data-hub-destination="campaign"]').click();ui.click('start');await ui.settle();ui.frames();assert.equal(ui.battle,campaign);assert.equal(ui.battle.profile.cheated,false);assert.equal(ui.battle.tick,tick);assert.deepEqual(store.read(1).raw,before);});
test('full slots permit explicit session-only import without replacing any local campaign',async t=>{const storage=new Storage(),store=await saved(storage),first=store.read(1);await store.write(2,first.latest.payload);await store.write(3,first.latest.payload);const before=[...storage.data],ui=await loadGameUI(t,{storage});ui.click('introLoad');await ui.settle();ui.get('loadCode').value=new CampaignProfiles({defaultName:'Portable'}).exportBundle();ui.click('importCode');await ui.settle();assert.equal(ui.get('localConfirmAccept').disabled,true);ui.click('localImportSession');await ui.settle();assert.equal(ui.battle.profile.name,'Portable');assert.deepEqual([...storage.data],before);ui.click('start');await ui.settle();assert.deepEqual([...storage.data],before);});
test('assisted import retains marking in its own slot and never changes earned campaign',async t=>{const storage=new Storage(),store=await saved(storage),before=store.read(1).raw,ui=await loadGameUI(t,{storage}),p=new PlayerProfile('Assisted');p.cheated=true;p.gold=10000;ui.click('introLoad');await ui.settle();ui.get('loadCode').value=new CampaignProfiles({profiles:[p]}).exportBundle();ui.click('importCode');await ui.settle();assert.match(ui.get('localConfirmText').textContent,/assisted/);ui.click('localConfirmAccept');await ui.settle();assert.equal(ui.battle.profile.cheated,true);assert.equal(store.read(2).latest.manager.active.cheated,true);assert.deepEqual(store.read(1).raw,before);});
test('storage conflict pauses autosave, preserves remote save, and new slot recovers current checkpoint',async t=>{const storage=new Storage(),ui=await loadGameUI(t,{storage}),store=createLocalCampaignStore({storage,locks:new TestLocks()});const current=store.read(1),payload=current.latest.payload;const remote=await store.write(1,payload,{expected:current.raw});ui.battle.profile.gold=777;ui.click('introSave');await ui.settle();assert.match(ui.get('localVaultStatus').textContent,/Another tab/);assert.deepEqual(store.read(1).raw,remote.expected);ui.click('localSaveCurrent');await ui.settle();assert.equal(store.read(2).latest.manager.active.gold,777);assert.deepEqual(store.read(1).raw,remote.expected);});
test('quota failure after purchase leaves the live purchase and prior save plus export available',async t=>{const storage=new Storage(),ui=await loadGameUI(t,{storage}),store=createLocalCampaignStore({storage,locks:new TestLocks()});ui.battle.profile.gold=3001;ui.click('introArmory');await ui.settle();ui.click('shopCatalogTab');await ui.settle();const before=store.read(1).raw;storage.setItem=()=>{throw Object.assign(new Error('full'),{name:'QuotaExceededError'});};ui.click('buy-pierceArrow');await ui.settle();assert.equal(ui.battle.profile.gold,1);assert.equal(ui.battle.profile.owned.has('pierceArrow'),true);assert.deepEqual(store.read(1).raw,before);ui.click('closeShop');await ui.settle();ui.click('introSave');await ui.settle();assert.match(ui.get('localVaultStatus').textContent,/full/);ui.click('showSaveCode');await ui.settle();assert.equal(CampaignProfiles.fromBundle(ui.get('saveCode').value).active.gold,1);});
test('a slot changed after Continue review cannot silently load stale data',async t=>{const storage=new Storage(),store=await saved(storage),ui=await loadGameUI(t,{storage});ui.click('localContinue');await ui.settle();const current=store.read(1);await store.write(1,current.latest.payload,{expected:current.raw});ui.click('localConfirmAccept');await ui.settle();assert.equal(ui.battle.profile.name,'Castledecks');assert.match(ui.get('vaultStatus').textContent,/changed/);});
test('previous checkpoint recovery is explicit and leaves the newer checkpoint recoverable',async t=>{const storage=new Storage(),store=await saved(storage),first=store.read(1),payload=structuredClone(first.latest.payload),bundle=JSON.parse(payload.bundle);bundle.profiles[0].profile.gold=999;payload.bundle=JSON.stringify(bundle);await store.write(1,payload,{expected:first.raw});const ui=await loadGameUI(t,{storage});ui.click('localManage');await ui.settle();localButton(ui,'recover');await ui.settle();assert.equal(ui.battle.profile.gold,0);ui.click('localConfirmAccept');await ui.settle();assert.equal(ui.battle.profile.gold,456);assert.equal(store.read(1).latest.manager.active.gold,456);assert.equal(store.read(1).previous.manager.active.gold,999);});
test('rapid purchase then Start captures ordered immutable checkpoints while the lock is pending',async t=>{
 const storage=new Storage(),locks=new TestLocks(),ui=await loadGameUI(t,{storage,locks}),store=createLocalCampaignStore({storage,locks});
 locks.pauseNext=true;ui.battle.profile.gold=3001;ui.click('introArmory');await settle();assert.ok(locks.release);ui.click('shopCatalogTab');ui.click('buy-pierceArrow');ui.click('closeShop');ui.click('start');
 assert.equal(ui.battle.profile.gold,1);assert.equal(ui.visible('intro'),false);assert.match(ui.get('localHubStatus').textContent,/Saving checkpoint/);assert.equal(store.read(1).latest.manager.active.gold,0);
 ui.battle.profile.gold=9876;locks.release();await settle();assert.equal(store.read(1).latest.manager.active.gold,1);assert.equal(store.read(1).latest.manager.active.owned.has('pierceArrow'),true);assert.equal(store.read(1).latest.payload.resume.phase,'opening');assert.doesNotMatch(ui.get('localHubStatus').textContent,/Saving/);
});
test('result then next battle preserves the settled reward once despite a pending save',async t=>{
 const storage=new Storage(),locks=new TestLocks(),ui=await loadGameUI(t,{storage,locks}),store=createLocalCampaignStore({storage,locks});ui.click('start');await settle();locks.pauseNext=true;
 ui.battle.finishOutcome('victory');ui.frames(105);await settle();assert.ok(locks.release);const gold=ui.battle.profile.gold;assert.equal(store.read(1).latest.manager.active.victories,0);
 ui.click('replay');assert.equal(ui.battle.level,2);ui.battle.profile.gold+=999;locks.release();await settle();const saved=store.read(1).latest;assert.equal(saved.manager.active.victories,1);assert.equal(saved.manager.active.gold,gold);assert.equal(saved.payload.resume.level,2);assert.equal(saved.payload.resume.phase,'opening');
});
test('late campaign save completion cannot relabel or contaminate a practice destination',async t=>{
 const storage=new Storage(),locks=new TestLocks(),ui=await loadGameUI(t,{storage,locks}),store=createLocalCampaignStore({storage,locks});locks.pauseNext=true;ui.battle.profile.gold=321;ui.click('introSave');await settle();assert.ok(locks.release);ui.click('closeSave');
 ui.get('hubDestinations').querySelector('[data-hub-destination="training"]').click();ui.click('start');ui.click('introTesting');ui.click('testGoldLarge');ui.click('closeTesting');locks.release();await settle();
 assert.equal(ui.battle.profile.cheated,true);assert.equal(ui.battle.profile.gold,10000);assert.equal(store.read(1).latest.manager.active.gold,321);assert.equal(store.read(1).latest.manager.active.cheated,false);assert.match(ui.get('localHubStatus').textContent,/Practice and showcase/);
});
test('profile selection while a lock is pending saves the final selected profile in order',async t=>{
 const storage=new Storage(),locks=new TestLocks(),ui=await loadGameUI(t,{storage,locks}),store=createLocalCampaignStore({storage,locks});locks.pauseNext=true;ui.battle.profile.gold=456;ui.click('introProfiles');await settle();assert.ok(locks.release);ui.get('newProfileName').value='New profile';ui.click('createProfile');assert.equal(ui.battle.profile.name,'New profile');locks.release();await settle();const saved=store.read(1).latest;assert.equal(saved.payload.activeIndex,1);assert.equal(saved.manager.active.name,'New profile');assert.equal(saved.manager.profiles[0].gold,456);assert.equal(saved.manager.active.gold,0);
});
test('import accepted while a prior manager save is pending reserves a different slot',async t=>{
 const storage=new Storage(),locks=new TestLocks(),ui=await loadGameUI(t,{storage,locks}),store=createLocalCampaignStore({storage,locks});locks.pauseNext=true;ui.battle.profile.gold=654;ui.click('introLoad');await settle();assert.ok(locks.release);ui.get('loadCode').value=new CampaignProfiles({defaultName:'New import'}).exportBundle();ui.click('importCode');ui.click('localConfirmAccept');assert.equal(ui.battle.profile.name,'New import');locks.release();await settle();assert.equal(store.read(1).latest.manager.active.gold,654);assert.equal(store.read(2).latest.manager.active.name,'New import');assert.match(ui.get('localHubStatus').textContent,/Local slot 2/);
});
test('navigating away while Continue waits for pending writes cancels the stale confirmation',async t=>{
 const storage=new Storage(),locks=new TestLocks(),ui=await loadGameUI(t,{storage,locks});locks.pauseNext=true;ui.battle.profile.gold=654;ui.click('introSave');await settle();assert.ok(locks.release);localButton(ui,'continue');ui.click('closeSave');locks.release();await settle();assert.equal(ui.visible('localConfirm'),false);assert.equal(ui.visible('savePanel'),false);assert.equal(ui.battle.profile.name,'Castledecks');
});
test('unsupported lock API keeps saved campaigns readable and gameplay/export usable without writes',async t=>{
 const storage=new Storage(),store=await saved(storage),before=[...storage.data],ui=await loadGameUI(t,{storage,locks:null});assert.match(ui.get('localHubStatus').textContent,/Safe autosave is unavailable/);ui.click('localContinue');await settle();ui.click('localConfirmAccept');await settle();assert.equal(ui.battle.profile.name,'Kept');ui.click('start');ui.frames(3);assert.ok(ui.battle.tick>0);ui.click('battlePause');ui.click('saveGame');ui.click('showSaveCode');assert.equal(CampaignProfiles.fromBundle(ui.get('saveCode').value).active.name,'Kept');assert.deepEqual([...storage.data],before);assert.equal(store.read(1).latest.manager.active.gold,456);
});
test('a changed-then-reverted option while saving still persists the final option',async t=>{
 const storage=new Storage(),locks=new TestLocks(),ui=await loadGameUI(t,{storage,locks}),store=createLocalCampaignStore({storage,locks});locks.pauseNext=true;ui.click('introSettings');ui.get('difficulty').value='hard';ui.click('applySettings');await settle();assert.ok(locks.release);ui.click('introSettings');ui.get('difficulty').value='medium';ui.click('applySettings');locks.release();await settle();assert.equal(store.read(1).latest.manager.active.difficulty,'medium');
});
