import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {syncPortraitDock} from '../site/dist/mobile-hud-layout.mjs';
import {loadGameUI} from './helpers/game-ui-harness.mjs';
const fixture=(height=169)=>{const writes=[];const hud={dataset:{},style:{setProperty:(...args)=>writes.push(args)}};const dock={getBoundingClientRect:()=>({height})};return {hud,dock,writes,root:{querySelector:s=>s==='.live-hud'?hud:s==='.live-arsenal'?dock:null}};};
test('portrait follows measured one/two row docks, company captions and utility columns',()=>{for(const h of [70,113,141,169,181,199.2]){const f=fixture(h);assert.equal(syncPortraitDock(f.root,{width:360,height:640}),Math.ceil(h));assert.deepEqual(f.writes,[['--portrait-dock-height',Math.ceil(h)+'px']]);}});
test('layout writes only when real measured height changes',()=>{const f=fixture();for(let i=0;i<20;i++)syncPortraitDock(f.root,{width:360,height:640});assert.equal(f.writes.length,1);f.dock.getBoundingClientRect=()=>({height:117});syncPortraitDock(f.root,{width:360,height:640});assert.equal(f.writes.length,2);assert.equal(f.hud.dataset.portraitDockHeight,'117px');});
test('landscape and square preserve their accepted layout without writing styles',()=>{for(const [width,height] of [[740,320],[915,360],[1280,720],[240,240]]){const f=fixture();assert.equal(syncPortraitDock(f.root,{width,height}),null);assert.equal(f.writes.length,0);}});
test('hidden, nonfinite, missing and impossible measurements never displace controls',()=>{for(const h of [0,-2,NaN,Infinity,641]){const f=fixture(h);assert.equal(syncPortraitDock(f.root,{width:360,height:640}),null);assert.equal(f.writes.length,0);}assert.equal(syncPortraitDock({querySelector:()=>null},{width:360,height:640}),null);});
test('rotation back into portrait uses new content geometry',()=>{const f=fixture();syncPortraitDock(f.root,{width:360,height:640});syncPortraitDock(f.root,{width:740,height:320});f.dock.getBoundingClientRect=()=>({height:125});syncPortraitDock(f.root,{width:360,height:640});assert.equal(f.hud.dataset.portraitDockHeight,'125px');});
test('ordinary render runs the presentation helper without changing command or shot ownership',async t=>{const ui=await loadGameUI(t,{search:'?mode=demo'});ui.click('start');ui.frames();const picker=ui.get('liveRallyPosition').querySelector('select');const order=ui.battle.armyOrder;assert.ok(picker);ui.frames();assert.deepEqual(ui.battle.armyOrder,order);assert.equal(ui.get('battlePause').disabled,false);});
test('compact styling retains target and label minimums, companion and near-keep actions',()=>{const css=readFileSync(new URL('../site/dist/live-action-bar.css',import.meta.url),'utf8');const patch=css.slice(css.indexOf('/* Compact portrait thumb deck'));assert.match(patch,/height:48px;min-height:48px/);assert.match(patch,/font-size:10px;line-height:12px/);assert.match(patch,/portrait-dock-height/);assert.match(patch,/near-garrison/);assert.doesNotMatch(patch,/visibility:hidden|pointer-events:none|scale\(/);assert.match(patch,/::before\{display:none\}/);});

test('two-line portrait labels keep intrinsic line boxes inside the unchanged48px card',()=>{const css=readFileSync(new URL('../site/dist/live-action-bar.css',import.meta.url),'utf8');const patch=css.slice(css.indexOf('/* Compact portrait thumb deck'));assert.match(patch,/\.live-short-name\{flex:none;font-size:10px;line-height:12px\}/);assert.match(patch,/\.live-slot \.skill-icon\{width:20px;height:20px\}/);assert.match(patch,/\.live-hud \.live-slot\{gap:0;padding:1px\}/);assert.match(patch,/\.live-hud \.live-slot\[aria-pressed="true"\]\{padding:0\}/);assert.equal(20+2*12+2*(1+1),48);assert.equal(20+2*12+2*(2+0),48);});
