import test from 'node:test';import assert from 'node:assert/strict';
import {modalFocusCandidates} from '../site/dist/modal-focus.mjs';
import {loadGameUI} from './helpers/game-ui-harness.mjs';
const fake=(properties={})=>({disabled:false,parentElement:null,inert:false,hidden:false,getAttribute:()=>null,getClientRects:()=>[{}],...properties});
test('Modal focus skips disabled, hidden, negative-tabindex and every inert ancestry path',()=>{const inert=fake({inert:true}),attributeInert=fake({getAttribute:name=>name==='inert'?'':null}),nested=fake({parentElement:inert}),disabled=fake({disabled:true}),fieldsetDisabled=fake({matches:s=>s===':disabled'}),negative=fake({getAttribute:name=>name==='tabindex'?'-1':null}),ariaDisabled=fake({getAttribute:name=>name==='aria-disabled'?'true':null}),hidden=fake({hidden:true}),notRendered=fake({getClientRects:()=>[]}),good=fake(),deep=fake({parentElement:nested}),attr=fake({parentElement:attributeInert}),insideHidden=fake({parentElement:hidden}),root=fake({querySelectorAll:()=>[disabled,fieldsetDisabled,negative,ariaDisabled,hidden,notRendered,deep,attr,insideHidden,good]});assert.deepEqual(modalFocusCandidates(root),[good]);good.parentElement=root;root.inert=true;assert.deepEqual(modalFocusCandidates(root),[]);assert.deepEqual(modalFocusCandidates(null),[]);});
async function ready(t){const ui=await loadGameUI(t,{search:'?mode=test'});ui.click('introTesting');ui.click('testGoldSmall');ui.click('testUnlock');ui.click('testReady');ui.click('closeTesting');ui.click('start');ui.click('battlePause');ui.click('pauseQueue');ui.get('armySearch').value='grunt';ui.dispatch(ui.get('armySearch'),'input');ui.click('army-card-grunt');return ui;}
test('Lost body focus after paid Queue recovers to inspector Back instead of inert Army background',async t=>{const ui=await ready(t),b=ui.battle,gold=b.profile.gold,pop=b.friendlyQueue.population;ui.get('armyRecruit').focus();ui.click('armyRecruit');assert.equal(b.profile.gold,gold-20);assert.equal(b.friendlyQueue.population,pop-4);assert.equal(ui.get('armyRecruit').disabled,true);assert.equal(ui.get('armyLoadout').parentElement.parentElement.inert,true);ui.document.activeElement=ui.document;const event=ui.key('keydown','Tab');assert.equal(event.event.defaultPrevented,true);assert.equal(ui.document.activeElement,ui.get('armyCloseInspector'));assert.equal(b.paused,true);assert.equal(b.friendlyQueue.queue.length,4);assert.deepEqual(modalFocusCandidates(ui.get('queuePanel')).map(e=>e.id||e.tagName),['armyCloseInspector','armyInspectLoadout','armyInspectAuto','SUMMARY']);});
test('Inspector Tab and ShiftTab wrap within Back, Arrange, Auto and details after Queue',async t=>{const ui=await ready(t);ui.click('armyRecruit');const candidates=modalFocusCandidates(ui.get('queuePanel')),first=candidates[0],last=candidates.at(-1);first.focus();let event=ui.key('keydown','Tab',{shiftKey:true});assert.equal(event.event.defaultPrevented,true);assert.equal(ui.document.activeElement,last);event=ui.key('keydown','Tab');assert.equal(event.event.defaultPrevented,true);assert.equal(ui.document.activeElement,first);ui.get('armyInspectAuto').focus();event=ui.key('keydown','Tab');assert.equal(event.event.defaultPrevented,false);assert.equal(modalFocusCandidates(ui.get('armyInspector')).at(-1).tagName,'SUMMARY');ui.click('armyCloseInspector');assert.equal(ui.visible('armyInspector'),false);assert.ok(modalFocusCandidates(ui.get('queuePanel')).includes(ui.get('armyLoadout')));});
test('Initial panel focus uses the same enabled candidate list',async t=>{const ui=await loadGameUI(t);ui.get('closeSettings').disabled=true;ui.click('introSettings');assert.equal(ui.visible('settingsPanel'),true);assert.equal(ui.document.activeElement,modalFocusCandidates(ui.get('settingsPanel'))[0]);assert.notEqual(ui.document.activeElement,ui.get('closeSettings'));assert.equal(ui.battle.tick,0);});
