import test from 'node:test';import assert from 'node:assert/strict';
import {loadGameUI} from './helpers/game-ui-harness.mjs';
import {createMovementOwners} from '../site/dist/movement-input.mjs';
// Actual V24 UI with only the ownership adapter integrations; no event-handler mocks.
const move=ui=>ui.document.querySelector('[data-key="right"]'),p={x:0,y:0};
test('actual keyboard + pointer handlers keep Right held until both owners release',async t=>{const ui=await loadGameUI(t);ui.click('start');const button=move(ui);ui.key('keydown','d');ui.pointer('pointerdown',10,p,button);ui.pointer('pointerup',10,p,button);assert.equal(ui.battle.input.right,true);ui.key('keyup','d');assert.equal(ui.battle.input.right,false);});
test('actual two-finger movement keeps Right held after first release',async t=>{const ui=await loadGameUI(t);ui.click('start');const button=move(ui);ui.pointer('pointerdown',10,p,button);ui.pointer('pointerdown',11,p,button);ui.pointer('pointerup',10,p,button);assert.equal(ui.battle.input.right,true);assert.equal(button.hasPointerCapture(11),true);ui.pointer('pointerup',11,p,button);assert.equal(ui.battle.input.right,false);});
test('actual pause releases every movement capture; old releases do not cancel a new keyboard hold',async t=>{const ui=await loadGameUI(t);ui.click('start');const button=move(ui);ui.pointer('pointerdown',10,p,button);ui.pointer('pointerdown',11,p,button);ui.key('keydown','d');ui.click('battlePause');assert.equal(ui.battle.paused,true);assert.equal(ui.battle.input.right,false);assert.equal(button.hasPointerCapture(10),false);assert.equal(button.hasPointerCapture(11),false);ui.click('resumeGame');ui.key('keydown','d');ui.dispatch(button,'pointerup',{pointerId:10});assert.equal(ui.battle.input.right,true);});
test('actual mixed draw and movement keep independent owners across cancellation',async t=>{const ui=await loadGameUI(t);ui.click('start');ui.frames(31);const button=move(ui),o={...ui.battle.hero.launchPosition},end={x:o.x-150,y:o.y+65};ui.pointer('pointerdown',10,o);ui.frames();ui.pointer('pointermove',10,end);ui.pointer('pointerdown',11,p,button);ui.pointer('pointerdown',12,p,button);ui.pointer('pointercancel',11,p,button);assert.equal(ui.battle.input.right,true);assert.equal(ui.battle.shooter.holding,true);ui.pointer('pointerup',10,end);ui.frames();assert.equal(ui.battle.stats.shotsFired,1);assert.equal(ui.battle.input.right,true);ui.pointer('pointerup',12,p,button);assert.equal(ui.battle.input.right,false);});
test('actual blur cancellation removes every owner and blocks stale movement',async t=>{const ui=await loadGameUI(t);ui.click('start');const button=move(ui);ui.key('keydown','d');ui.pointer('pointerdown',11,p,button);ui.dispatch(ui.window,'blur');assert.equal(ui.battle.paused,true);assert.equal(ui.battle.input.right,false);assert.equal(button.hasPointerCapture(11),false);});
