import test from 'node:test';import assert from 'node:assert/strict';
import {createPortraitView,portraitViewBounds,portraitOffscreenStatus} from '../site/dist/portrait-view.mjs';
import {worldToScreen,screenToWorld} from '../site/dist/world-camera.mjs';
import {CampaignBattle} from '../site/dist/engine/first-battle.mjs';
import {loadGameUI} from './helpers/game-ui-harness.mjs';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-8);
test('portrait doubles actor scale, bounds horizontal view, and keeps input coordinates reversible',()=>{for(const [w,h]of [[360,640],[412,780]])for(const heroX of [0,350,1000,1950]){const c=createPortraitView(w,h,{heroX}),bounds=portraitViewBounds(c);assert.equal(c.scale,w/1000);assert.ok(bounds.left>=0&&bounds.right<=2000);const p={x:heroX,y:450},back=screenToWorld(c,worldToScreen(c,p));near(p.x,back.x);near(p.y,back.y);}});
test('manual panorama can see either field edge; overview restores whole-field view',()=>{for(const center of [-999,500,1500,3000]){const b=portraitViewBounds(createPortraitView(360,640,{center}));assert.ok(b.left>=0&&b.right<=2000);}assert.equal(createPortraitView(360,640,{overview:true}).scale,.18);assert.equal(portraitViewBounds(createPortraitView(360,640,{center:1500})).right,2000);});
test('offscreen notice identifies living enemies and the enemy flag without changing battle',()=>{const b=new CampaignBattle({random:()=>.5}),camera=createPortraitView(360,640),before={flag:b.enemyFlag.x,hp:b.hero.hp};b.badTeam.push({hp:10,x:1500},{hp:0,x:1600});assert.match(portraitOffscreenStatus(b,camera),/1 enemies →.*enemy flag →/);assert.deepEqual({flag:b.enemyFlag.x,hp:b.hero.hp},before);});
function portrait(ui){ui.get('battlefield').getBoundingClientRect=()=>({left:0,top:0,width:360,height:640});ui.document.querySelector('.live-movement').getBoundingClientRect=()=>({left:12,top:393,width:140,height:56});}
function camera(ui,center=null){return createPortraitView(360,640,{heroX:ui.battle.hero.x,center,groundY:Math.max(...ui.battle.terrain.samples),groundBottom:367});}
test('map pan cannot fire and Hero works after inspecting enemies and opening a menu',async t=>{const ui=await loadGameUI(t);portrait(ui);ui.click('start');ui.frames(31);ui.get('viewCenter').value='1500';ui.dispatch(ui.get('viewCenter'),'input');ui.frames();assert.equal(ui.battle.stats.shotsFired,0);assert.match(ui.get('viewStatus').textContent,/Hero off-screen/);ui.click('openSettings');ui.click('closeSettings');ui.click('viewHero');ui.frames();assert.equal(ui.get('viewHero').getAttribute('aria-pressed'),'true');assert.equal(ui.battle.stats.shotsFired,0);});
test('explicit panorama changes cancel an active draw without firing; a subsequent hero draw works',async t=>{const ui=await loadGameUI(t);portrait(ui);ui.click('start');ui.frames(31);const o={...ui.battle.hero.launchPosition},c=camera(ui);ui.pointer('pointerdown',1,worldToScreen(c,o));ui.frames();assert.equal(ui.battle.shooter.holding,true);ui.get('viewCenter').value='1500';ui.dispatch(ui.get('viewCenter'),'input');assert.equal(ui.battle.shooter.holding,false);ui.pointer('pointerup',1,worldToScreen(c,{x:o.x-150,y:o.y+60}));assert.equal(ui.battle.stats.shotsFired,0);ui.click('viewHero');ui.frames();ui.pointer('pointerdown',2,worldToScreen(c,o));ui.frames();ui.pointer('pointerup',2,worldToScreen(c,{x:o.x-150,y:o.y+60}));ui.frames();assert.equal(ui.battle.stats.shotsFired,1);});
test('ordinary paused campaign exposes a separate demo entry without resetting campaign',async t=>{const ui=await loadGameUI(t);ui.click('start');ui.click('battlePause');const b=ui.battle;let target;ui.window.open=(url)=>{target=url;return {};};ui.click('pauseDemo');assert.equal(ui.visible('switchSessionConfirm'),true);ui.click('separateSessionSwitch');assert.match(target,/mode=demo/);assert.equal(ui.battle,b);assert.match(ui.get('introNotice').textContent,/separate tab/);});

test('map keyboard adjustment keeps range focus instead of stealing subsequent keys',async t=>{const ui=await loadGameUI(t);portrait(ui);ui.click('start');const range=ui.get('viewCenter');range.focus();range.value='1000';ui.dispatch(range,'input');assert.equal(ui.document.activeElement,range);ui.click('viewHero');assert.equal(ui.document.activeElement,ui.get('battlefield'));});
