import test from 'node:test';import assert from 'node:assert/strict';import {loadGameUI} from './helpers/game-ui-harness.mjs';
async function ready(t,mode='classic'){const ui=await loadGameUI(t,{search:'?mode=test'});ui.click('introTesting');ui.click('testUnlock');ui.click('closeTesting');ui.click('introSettings');ui.get('aimMode').value=mode;ui.click('applySettings');ui.click('start');ui.click('nextBar');ui.click('quick-arrow');return ui;}
function release(ui,id=1){const o={...ui.battle.hero.launchPosition},drag=['classic','anywhere'].includes(ui.battle.profile.shootingMode);ui.pointer('pointerdown',id,drag?o:{x:900,y:250});ui.pointer('pointerup',id,drag?{x:o.x-110,y:o.y+170}:{x:900,y:250});}
for(const mode of ['classic','anywhere','point_aim','auto_aim'])test(`${mode}: two pre-tick releases retain FIFO skill/velocity and latest UI selection`,async t=>{const ui=await ready(t,mode);release(ui,1);const original={...ui.battle.playerShots[0].aim};ui.click('quick-fireWave');release(ui,2);assert.equal(ui.battle.playerShots.length,2);assert.deepEqual(ui.battle.playerShots.map(x=>x.skill.id),['arrow','fireWave']);assert.equal(ui.battle.projectiles.length,0);ui.frames();assert.equal(ui.battle.projectiles[0].kind,'hero_arrow');assert.equal(ui.battle.projectiles[0].vx,original.vx);assert.equal(ui.battle.activeSkill.id,'fireWave');assert.equal(ui.battle.playerShots.length,1);ui.frames();assert.deepEqual(ui.battle.projectiles.map(x=>x.kind),['hero_arrow','fire_wave_arrow']);assert.equal(ui.battle.activeSkill.id,'fireWave');assert.equal(ui.battle.playerShots.length,0);});
for(const mode of ['point_aim','auto_aim'])test(`${mode}: a held press retains press-time skill if a second finger selects before sample`,async t=>{const ui=await ready(t,mode);ui.pointer('pointerdown',1,{x:900,y:250});ui.click('quick-fireWave');ui.frames();assert.equal(ui.battle.projectiles[0].kind,'hero_arrow');assert.equal(ui.battle.activeSkill.id,'fireWave');ui.pointer('pointerup',1,{x:900,y:250});ui.frames();assert.equal(ui.battle.projectiles.length,1);});
test('precise-shot clicks also retain identity and only dispatch one per tick',async t=>{const ui=await ready(t);ui.click('battleFire');ui.click('quick-fireWave');ui.click('battleFire');assert.equal(ui.battle.playerShots.length,2);ui.frames();assert.equal(ui.battle.projectiles.length,1);ui.frames();assert.deepEqual(ui.battle.projectiles.map(x=>x.kind),['hero_arrow','fire_wave_arrow']);});
for(const boundary of ['pause','menu','blur','hidden','resize','cancel','restart'])test(`pending shots are discarded at ${boundary}, never replayed`,async t=>{const ui=await ready(t);release(ui);const b=ui.battle;assert.equal(b.playerShots.length,1);if(boundary==='pause')ui.click('battlePause');if(boundary==='menu')ui.click('openSettings');if(boundary==='blur')ui.dispatch(ui.window,'blur');if(boundary==='hidden'){ui.document.hidden=true;ui.dispatch(ui.document,'visibilitychange');}if(boundary==='resize')ui.dispatch(ui.window,'resize');if(boundary==='cancel'){const o=ui.battle.hero.launchPosition;ui.pointer('pointerdown',2,o);ui.pointer('pointercancel',2,o);}if(boundary==='restart')ui.click('confirmRestart');assert.equal(b.playerShots.length,0);assert.equal(b.queuedAim,null);ui.frames(2);assert.equal(ui.battle.stats.shotsFired,0);});
for(const invalid of ['cooldown','unbound','dead'])test(`invalid ${invalid} captured skill is rejected without substituting selected FireWave`,async t=>{const ui=await ready(t),basic=ui.battle.activeSkill;release(ui);ui.click('quick-fireWave');if(invalid==='cooldown')basic.cooldown=basic.maximum;if(invalid==='unbound'){basic.binding=-1;ui.battle.refreshHotbar();}if(invalid==='dead')ui.battle.hero.takeDamage(ui.battle.hero.hp);ui.frames();assert.equal(ui.battle.projectiles.length,0);assert.equal(ui.battle.profile.skills.find(s=>s.id==='fireWave').cooldown,0);assert.equal(ui.battle.playerShots.length,0);});
test('intent buffer is bounded to three immediate ticks; overload cannot replace oldest',async t=>{const ui=await ready(t);for(let i=1;i<=4;i++)release(ui,i);assert.equal(ui.battle.playerShots.length,3);assert.match(ui.get('battleStatus').textContent,/queue is full/);ui.frames(3);assert.equal(ui.battle.playerShots.length,0);assert.equal(ui.battle.stats.shotsFired,1,'cooldown rejects repeats instead of retrying later');});
