import test from 'node:test';import assert from 'node:assert/strict';
import {loadGameUI} from './helpers/game-ui-harness.mjs';
const slots=ui=>ui.get('hotbar').querySelectorAll('button');
function unlock(ui){ui.click('introTesting');ui.click('testGoldLarge');ui.click('testUnlock');ui.click('closeTesting');}
function pageFor(ui,id){for(let n=0;n<3;n++){if(slots(ui).some(b=>b.id==='quick-'+id))return;ui.click('nextBar');}throw new Error('Skill not reachable: '+id);}
test('initial combat exposes its actual arrow and contextual movement, with details in Pause',async t=>{const ui=await loadGameUI(t);ui.click('start');ui.frames();assert.equal(slots(ui).length,1);assert.equal(slots(ui)[0].id,'quick-arrow');assert.equal(ui.visible('nextBar'),false);assert.equal(ui.visible('flagHud'),false);assert.equal(ui.visible('activate'),false);ui.document.querySelector('[data-key="down"]').click();ui.frames();assert.equal(ui.document.querySelector('.battle-screen').dataset.heroMode,'foot');ui.click('battlePause');assert.equal(ui.battle.paused,true);assert.ok(ui.get('pauseOverlay').querySelector('#goldHud'));});
test('every represented physical slot is live and bar cycling never pauses or clears held movement',async t=>{const ui=await loadGameUI(t,{search:'?mode=test'});unlock(ui);ui.click('start');ui.frames();ui.key('keydown','d');const seen=new Set();for(let n=0;n<3;n++){const represented=ui.battle.hotbar.bars[ui.battle.hotbar.bar].filter(Boolean);assert.deepEqual(slots(ui).map(b=>b.id),represented.map(s=>'quick-'+s.id));for(const s of represented)seen.add(s.id);ui.click('nextBar');assert.equal(ui.battle.paused,false);assert.equal(ui.battle.input.right,true);}assert.equal(seen.size,25);pageFor(ui,'arrow');assert.equal(slots(ui).length,10);});
test('a rapid live bow click and release fires that chosen bow in the same next tick',async t=>{const ui=await loadGameUI(t,{search:'?mode=test'});unlock(ui);ui.click('start');pageFor(ui,'fireArrow');const o=ui.battle.hero.launchPosition;ui.click('quick-fireArrow');assert.equal(ui.battle.activeSkill.id,'fireArrow');ui.pointer('pointerdown',4,o);ui.pointer('pointerup',4,{x:o.x-150,y:o.y+60});ui.frames();assert.deepEqual(ui.battle.projectiles.map(p=>p.kind),['fire_arrow']);assert.equal(ui.battle.paused,false);assert.equal(ui.document.activeElement.id,'battlefield');});
test('live summon survives immediate bar cycle and bow selection without wrong spend or modal',async t=>{const ui=await loadGameUI(t,{search:'?mode=test'});unlock(ui);ui.click('start');pageFor(ui,'grunt');const gold=ui.battle.profile.gold;ui.click('quick-grunt');pageFor(ui,'fireArrow');ui.click('quick-fireArrow');ui.frames();assert.equal(ui.battle.profile.gold,gold-20);assert.equal(ui.battle.friendlyQueue.queue.length,4);assert.equal(ui.battle.activeSkill.id,'fireArrow');assert.equal(ui.battle.paused,false);assert.equal(ui.visible('skillsPanel'),false);assert.match(ui.get('battleStatus').textContent,/squad queued/);});
test('live bar DOM stays stable across cooldown ticks and enabling precise fire never removes skills',async t=>{const ui=await loadGameUI(t,{search:'?mode=test'});unlock(ui);ui.click('start');pageFor(ui,'arrow');const nodes=slots(ui);ui.frames(10);assert.deepEqual(slots(ui),nodes);ui.get('showAssist').checked=true;ui.dispatch(ui.get('showAssist'),'change',{target:ui.get('showAssist')});ui.frames();assert.equal(slots(ui).length,10);assert.equal(ui.visible('battleFire'),true);});
test('precise configuration returns through Settings and Pause; live firing never opens a panel',async t=>{const ui=await loadGameUI(t);ui.get('showAssist').checked=true;ui.dispatch(ui.get('showAssist'),'change',{target:ui.get('showAssist')});ui.click('start');ui.frames(31);ui.click('battlePause');ui.click('openSettings');ui.click('openAim');ui.click('applyAim');assert.equal(ui.battle.paused,true);assert.equal(ui.visible('settingsPanel'),true);assert.equal(ui.battle.stats.shotsFired,0);ui.click('closeSettings');ui.click('resumeGame');ui.frames();ui.click('battleFire');ui.frames();assert.equal(ui.battle.paused,false);assert.equal(ui.battle.stats.shotsFired,1);assert.equal(ui.visible('aimPanel'),false);});
test('Pause loadout inspection cannot summon, spend gold or silently resume',async t=>{const ui=await loadGameUI(t,{search:'?mode=test'});unlock(ui);ui.click('start');ui.click('battlePause');ui.click('pauseSkills');const gold=ui.battle.profile.gold;ui.click('owned-grunt');assert.equal(ui.battle.paused,true);assert.equal(ui.battle.profile.gold,gold);assert.equal(ui.battle.friendlyQueue.queue.length,0);});
test('closing loadout and Army after a paused held draw keeps Pause and cancels the draw',async t=>{const ui=await loadGameUI(t);ui.click('start');ui.frames(31);const o=ui.battle.hero.launchPosition;ui.pointer('pointerdown',4,o);ui.frames();ui.click('battlePause');ui.click('pauseSkills');ui.click('openQueue');ui.click('closeQueue');ui.frames();assert.equal(ui.battle.paused,true);assert.equal(ui.battle.input.mouseDown,false);assert.equal(ui.battle.stats.shotsFired,0);});
