import test from 'node:test';
import assert from 'node:assert/strict';
import {loadGameUI} from './helpers/game-ui-harness.mjs';
import {encodeSkirmishDescriptor,DEFAULT_SKIRMISH} from '../site/dist/skirmish-model.mjs';
function clipboard(t,writeText){const old=Object.getOwnPropertyDescriptor(globalThis,'navigator');Object.defineProperty(globalThis,'navigator',{configurable:true,value:{clipboard:{writeText}}});t.after(()=>{if(old)Object.defineProperty(globalThis,'navigator',old);else delete globalThis.navigator;});}
function settle(ui){ui.click('skirmishPrepare');ui.click('start');const b=ui.battle;for(let i=0;i<15000&&!b.summary;i++)b.step();assert.equal(b.summary?.outcome,'defeat');return b;}
test('UI review: post-result lobby keeps armory disabled and deck inspection available',async t=>{const ui=await loadGameUI(t,{search:'?mode=skirmish'});settle(ui);ui.click('endingLobby');assert.equal(ui.get('introLoadout').disabled,false);assert.equal(ui.get('introArmory').disabled,true);ui.click('introLoadout');assert.equal(ui.visible('deckPresets'),true);assert.equal(ui.get('closeDeckPresets').textContent,'Back to hall');});
test('UI review: clipboard success writes exactly the displayed canonical code',async t=>{let payload;clipboard(t,async text=>{payload=text;});const ui=await loadGameUI(t,{search:'?mode=skirmish'});ui.get('skirmishSeed').value='42';ui.dispatch(ui.get('skirmishSeed'),'change');const code=ui.get('skirmishCode').value;await ui.click('skirmishCopy').completed;assert.equal(payload,code);assert.equal(code,encodeSkirmishDescriptor({...DEFAULT_SKIRMISH,seed:42}));assert.match(ui.get('skirmishStatus').textContent,/copied/);});
test('UI review: older copy completion must not claim newly edited seed was copied',async t=>{let resolve,payload;clipboard(t,text=>{payload=text;return new Promise(yes=>resolve=yes);});const ui=await loadGameUI(t,{search:'?mode=skirmish'}),oldCode=ui.get('skirmishCode').value;const pending=ui.click('skirmishCopy').completed;ui.get('skirmishSeed').value='42';ui.dispatch(ui.get('skirmishSeed'),'change');const newCode=ui.get('skirmishCode').value;resolve();await pending;assert.equal(payload,oldCode);assert.notEqual(newCode,oldCode);assert.doesNotMatch(ui.get('skirmishStatus').textContent,/^Seed code copied\./);});
test('UI review: old rejected clipboard promise must not replace a new validation error',async t=>{let reject;clipboard(t,()=>new Promise((_,no)=>reject=no));const ui=await loadGameUI(t,{search:'?mode=skirmish'});const pending=ui.click('skirmishCopy').completed;ui.get('skirmishSeed').value='0';ui.dispatch(ui.get('skirmishSeed'),'change');const validation=ui.get('skirmishStatus').textContent;reject(new Error('denied'));await pending;assert.equal(ui.get('skirmishStatus').textContent,validation);assert.equal(ui.get('skirmishPrepare').disabled,true);});
test('UI review: prepare rereads uncommitted numeric draft and rejects unsafe content',async t=>{const ui=await loadGameUI(t,{search:'?mode=skirmish'}),b=ui.battle;ui.get('skirmishSeed').value='<svg onload=alert(1)>';ui.click('skirmishPrepare');assert.equal(ui.battle,b);assert.equal(ui.get('skirmishPrepare').disabled,true);assert.equal(ui.get('skirmishStatus').querySelector('svg'),null);ui.get('skirmishSeed').value='91';ui.dispatch(ui.get('skirmishSeed'),'change');ui.click('skirmishPrepare');assert.equal(ui.battle.skirmish.descriptor.seed,91);});
test('UI review: hidden workshop prepare cannot change a different active campaign',async t=>{const ui=await loadGameUI(t,{search:'?mode=skirmish'});ui.click('skirmishCancel');ui.click('introCampaign');ui.click('start');const campaign=ui.battle;assert.equal(campaign.profile.cheated,false);ui.get('skirmishSeed').value='42';ui.click('skirmishPrepare');assert.equal(ui.battle,campaign);assert.equal(ui.visible('skirmishPanel'),false);});
test('UI review: input editing and modal keyboard shortcuts cannot advance combat',async t=>{const ui=await loadGameUI(t,{search:'?mode=skirmish'}),b=ui.battle;ui.get('skirmishSeed').focus();for(const key of ['a','d','w','s','1',' ','p'])ui.key('keydown',key);ui.frames(12);assert.equal(b.tick,0);assert.equal(b.stats.shotsFired,0);assert.equal(b.goodTeam.length,1);assert.equal(b.input.left,false);assert.equal(b.input.right,false);});
test('UI review: double-clicking result-lobby Prepare cannot immediately start the fresh field',async t=>{const ui=await loadGameUI(t,{search:'?mode=skirmish'});settle(ui);ui.click('endingLobby');assert.equal(ui.get('start').textContent,'Prepare same seed');ui.dispatch(ui.get('start'),'click',{detail:1});const fresh=ui.battle;ui.dispatch(ui.get('start'),'click',{detail:2});ui.frames(5);assert.equal(fresh.tick,0);});
test('UI review: practice lobby does not promise a session save file',async t=>{const ui=await loadGameUI(t,{search:'?mode=skirmish'});ui.click('skirmishCancel');const generic=ui.document.querySelector('.hub-save-note'),note=ui.get('skirmishSessionNote');assert.equal(generic.getClientRects().length,0);assert.ok(note.getClientRects().length);assert.match(note.textContent,/seed code/);assert.match(note.textContent,/attempt itself is not saved/);ui.click('introCampaign');ui.click('start');assert.ok(generic.getClientRects().length);assert.equal(note.getClientRects().length,0);});
test('UI review: post-result Army actions cannot edit a kit about to be discarded',async t=>{const ui=await loadGameUI(t,{search:'?mode=skirmish'});const old=settle(ui),grunt=old.profile.skills.find(s=>s.id==='grunt');ui.click('endingLobby');ui.click('introArmy');if(ui.visible('queuePanel'))ui.click('armyAuto-grunt');assert.equal(grunt.autocast,false);});
test('UI review: clipboard denial focuses and selects the canonical fallback code',async t=>{clipboard(t,async()=>{throw new Error('permission denied');});const ui=await loadGameUI(t,{search:'?mode=skirmish'});let selected=0;ui.get('skirmishCode').select=()=>selected++;await ui.click('skirmishCopy').completed;assert.equal(ui.document.activeElement,ui.get('skirmishCode'));assert.equal(selected,1);assert.equal(ui.get('skirmishCode').value,ui.battle.skirmish.code);assert.match(ui.get('skirmishStatus').textContent,/selected/);});
test('UI review: prepared descriptor is the exact canonical history URL',async t=>{const ui=await loadGameUI(t,{search:'?mode=skirmish'});let replaced;ui.window.history={replaceState:(state,title,url)=>replaced=url};ui.get('skirmishSeed').value='4294967295';ui.get('skirmishBiome').value='pines';ui.get('skirmishThreat').value='veteran';ui.get('skirmishDoctrine').value='skywatch';ui.click('skirmishPrepare');const url=new URL(replaced,'https://example.invalid/base/');assert.equal(url.searchParams.get('mode'),'skirmish');assert.equal(url.searchParams.get('sk'),ui.battle.skirmish.code);assert.equal(ui.battle.skirmish.descriptor.seed,4294967295);assert.equal(ui.battle.tick,0);});
