import test from 'node:test';
import assert from 'node:assert/strict';
import {loadGameUI} from './helpers/game-ui-harness.mjs';
import {MemoryStorage,settle} from './helpers/local-storage.mjs';
import {captureDeck,exportDeckCode,parseDeckCode} from '../site/dist/deck-presets-model.mjs';
import {CONTROL_STORAGE_KEY,DEFAULT_CONTROL_BINDINGS} from '../site/dist/control-bindings.mjs';
const save=(ui,name)=>{ui.get('deckNewName').value=name;ui.dispatch(ui.get('deckSaveForm'),'submit');};
const books=ui=>{ui.click('deckShowExport');return parseDeckCode(ui.get('deckExportCode').value);};
const importDeck=(ui,d)=>{ui.get('deckImportCode').value=exportDeckCode([d]);ui.click('deckImportPrepare');ui.click('deckConfirmAccept');};
const empty=(name='Reserve all')=>({name,slots:Array(30).fill(null),companion:null});
const open=ui=>{ui.click('introLoadout');ui.click('openDeckPresets');};
const close=ui=>{ui.click('closeDeckPresets');if(ui.visible('skillsPanel'))ui.click('closeSkills');};
const switchTo=(ui,id)=>{ui.get('hubDestinations').querySelector(`[data-hub-destination="${id}"]`).click();ui.click('start');if(ui.visible('switchSessionConfirm'))ui.click('confirmSessionSwitch');ui.frames();};
const snapshot=b=>JSON.stringify({profile:b.profile,tick:b.tick,stats:b.stats,queue:b.friendlyQueue.queue,reserve:b.friendlyQueue.population,summary:b.summary,active:b.activeSkill?.id,bar:b.hotbar.bar,glow:b.hotbar.glow});
const result=ui=>{ui.click('start');ui.battle.finishOutcome('defeat');ui.frames(150);assert.equal(ui.battle.summary?.outcome,'defeat');};
const bytes=storage=>[...storage.data].filter(([key])=>key.startsWith('castledecks:campaign:'));

test('48 Skirmish result permits deck inspection, export and bookkeeping but locks actual kit mutations',async t=>{
 const storage=new MemoryStorage(),ui=await loadGameUI(t,{search:'?mode=skirmish',storage});ui.click('skirmishPrepare');open(ui);save(ui,'Original');importDeck(ui,empty());ui.click('deckApply');assert.equal(ui.battle.activeSkill,null);const apply=ui.get('deckApply').onclick,recover=ui.get('loadoutRecoverArrow').onclick,deckRecover=ui.get('deckRecoverArrow').onclick,unbind=ui.get('unbindSkill').onclick;close(ui);result(ui);const b=ui.battle,before=snapshot(b);assert.match(ui.get('endingSaveStatus').textContent,/saved decks.*Export a deck code first/);assert.match(ui.get('endingLoadout').textContent,/Inspect.*export/);ui.click('endingLoadout');assert.equal(ui.visible('deckPresets'),true);assert.equal(ui.get('closeDeckPresets').textContent,'Back to results');assert.equal(ui.get('deckApply').disabled,true);assert.equal(ui.get('deckRecoverArrow').disabled,true);assert.match(ui.get('deckBlockers').textContent,/attempt is over/);assert.match(ui.get('deckStorageNote').textContent,/Export a deck code before a fresh retry/);
 apply();recover();deckRecover();unbind();ui.get('loadoutArmory').onclick();ui.get('endingShop').onclick();assert.equal(ui.visible('shopPanel'),false);assert.equal(snapshot(b),before);
 save(ui,'After result');ui.get('deckRename').value='Renamed result';ui.dispatch(ui.get('deckRenameForm'),'submit');ui.click('deckDuplicate');assert.equal(books(ui).length,4);ui.click('deckDelete');ui.click('deckConfirmAccept');assert.equal(books(ui).length,3);importDeck(ui,empty('Imported result'));assert.equal(books(ui).length,4);assert.equal(snapshot(b),before);await settle();assert.equal(storage.writes,0);
 ui.click('deckDelete');ui.key('keydown','Escape');assert.equal(ui.visible('deckConfirm'),false);assert.equal(ui.visible('deckPresets'),true);ui.key('keydown','Escape');assert.equal(ui.visible('deckPresets'),false);assert.equal(ui.visible('skillsPanel'),false);assert.equal(ui.visible('ending'),true);ui.click('endingLoadout');ui.click('closeDeckPresets');assert.equal(ui.visible('skillsPanel'),false);assert.equal(snapshot(b),before);
});

test('48 saved library survives exact paused sessions and fresh retry discards only its attempt library',async t=>{
 const storage=new MemoryStorage(),ui=await loadGameUI(t,{storage});open(ui);save(ui,'Campaign library');close(ui);await settle();const campaign=ui.battle,campaignBefore=snapshot(campaign),saved=bytes(storage);switchTo(ui,'expedition');open(ui);save(ui,'Charter library');close(ui);const charter=ui.battle,charterBefore=snapshot(charter);
 switchTo(ui,'skirmish');ui.click('skirmishPrepare');open(ui);save(ui,'Practice library');importDeck(ui,empty());ui.click('deckApply');const code=books(ui);close(ui);ui.click('start');ui.frames(3);ui.click('battlePause');ui.click('pauseLobby');const practice=ui.battle,practiceBefore=snapshot(practice);
 switchTo(ui,'campaign');assert.equal(ui.battle,campaign);assert.equal(snapshot(campaign),campaignBefore);open(ui);assert.deepEqual(books(ui).map(d=>d.name),['Campaign library']);close(ui);switchTo(ui,'expedition');assert.equal(ui.battle,charter);assert.equal(snapshot(charter),charterBefore);open(ui);assert.deepEqual(books(ui).map(d=>d.name),['Charter library']);close(ui);switchTo(ui,'skirmish');assert.equal(ui.battle,practice);assert.equal(snapshot(practice),practiceBefore);open(ui);assert.deepEqual(books(ui),code);close(ui);result(ui);ui.click('endingLoadout');assert.deepEqual(books(ui),code);close(ui);ui.click('replay');assert.notEqual(ui.battle.profile,practice.profile);assert.equal(ui.battle.profile.gold,1200);assert.equal(ui.battle.tick,0);assert.equal(ui.battle.stats.goldSpent,0);assert.equal(ui.battle.activeSkill.id,'arrow');open(ui);assert.match(ui.get('deckCount').textContent,/0 \/ 12/);ui.get('deckImportCode').value=exportDeckCode(code);ui.click('deckImportPrepare');ui.click('deckConfirmAccept');assert.deepEqual(books(ui),code);assert.equal(ui.battle.activeSkill.id,'arrow');ui.get('deckList').querySelector('[data-deck-index="1"]').click();ui.click('deckApply');assert.equal(ui.battle.activeSkill,null);ui.click('deckRecoverArrow');assert.equal(ui.battle.activeSkill.id,'arrow');await settle();assert.deepEqual(bytes(storage),saved);
});

test('48 guided Training and remapped controls retain their library across a disposable Skirmish visit',async t=>{
 const storage=new MemoryStorage();storage.data.set(CONTROL_STORAGE_KEY,JSON.stringify({version:1,bindings:{...DEFAULT_CONTROL_BINDINGS,companion:'h',pause:'o',arc:'j'}}));const ui=await loadGameUI(t,{search:'?mode=test&guide=1',storage});open(ui);save(ui,'Guided library');const guideCode=books(ui);close(ui);ui.click('start');ui.frames(2);ui.key('keydown','o');ui.click('pauseLobby');const guide=ui.battle,before=snapshot(guide),run=guide.guidedTraining.run;
 switchTo(ui,'skirmish');ui.click('skirmishPrepare');open(ui);assert.match(ui.get('deckCount').textContent,/0 \/ 12/);const d=captureDeck(ui.battle.profile,'Remapped preview');d.companion='gorath';importDeck(ui,d);assert.match(ui.get('deckChanges').textContent,/separate H slot/);close(ui);result(ui);ui.click('endingLoadout');save(ui,'Result library');const practiceBooks=books(ui);close(ui);ui.click('endingLobby');switchTo(ui,'training');assert.equal(ui.battle,guide);assert.equal(guide.guidedTraining.run,run);assert.equal(snapshot(guide),before);open(ui);assert.deepEqual(books(ui),guideCode);assert.match(ui.get('deckStorageNote').textContent,/this drill.*fresh profile/);close(ui);assert.match(ui.get('pauseControlsReference').textContent,/H commands.*J switches.*O or Escape/);switchTo(ui,'skirmish');open(ui);assert.deepEqual(books(ui),practiceBooks);close(ui);assert.equal(bytes(storage).length,0);
});

test('48 result deck-only entry never repairs bindings and stale companion edit rechecks active profile',async t=>{
 const ui=await loadGameUI(t,{search:'?mode=skirmish'});ui.click('skirmishPrepare');const p=ui.battle.profile;p.companionOwned.add('gorath');p.companionId='gorath';ui.click('introLoadout');const equip=ui.get('equipCompanion').onclick;ui.click('closeSkills');result(ui);p.skills[1].binding=p.skills[0].binding;const b=ui.battle,before=snapshot(b);ui.click('endingLoadout');equip();ui.get('unbindSkill').onclick();assert.equal(snapshot(b),before);close(ui);ui.click('replay');const fresh=ui.battle;ui.click('introLoadout');equip();assert.equal(snapshot(b),before);assert.equal(fresh.profile.companionId,null);
});

test('48 workshop replacement and explicit restart warn before disposing of practice saved decks',async t=>{
 const ui=await loadGameUI(t,{search:'?mode=skirmish'});assert.match(ui.get('skirmishPreview').textContent,/Export their deck codes before a fresh retry/);ui.click('skirmishPrepare');open(ui);save(ui,'Prepared');close(ui);assert.match(ui.get('skirmishSessionNote').textContent,/Export saved deck codes/);ui.click('start');ui.click('battlePause');ui.click('battleRestart');assert.match(ui.get('restartDescription').textContent,/saved decks.*Export a deck code first/);ui.click('cancelRestart');ui.click('pauseWorkshop');ui.click('skirmishPrepare');assert.match(ui.get('skirmishReplaceConfirm').textContent,/saved decks.*Export deck codes/);ui.click('skirmishKeepAttempt');ui.click('closeWorkshop');open(ui);assert.deepEqual(books(ui).map(d=>d.name),['Prepared']);close(ui);
});
