import test from 'node:test';import assert from 'node:assert/strict';
import {FirstBattle} from '../site/dist/engine/first-battle.mjs';
import {stepObjectArray} from '../site/dist/engine/world-order.mjs';
test('candidate runs objects ascending with live indexes and splice skip',()=>{let items=[],trace=[];const a={step(){trace.push('A');items.splice(0,1)}},b={step(){trace.push('B')}},c={step(){trace.push('C')}};items=[a,b,c];stepObjectArray(()=>items);assert.deepEqual(trace,['A','C']);});
test('candidate real battle defers freshly loaded unit until following tick',()=>{let spawned=null,steps=0;const b=new FirstBattle({random:()=>.5,onEvent:e=>{if(e.type==='spawn'&&e.unit.team==='good'){spawned=e.unit;const old=spawned.step.bind(spawned);spawned.step=()=>{steps++;old();};}}});b.friendlyQueue.enqueue({type:'grunt',rank:0});b.step();assert.ok(spawned);assert.equal(steps,0);assert.equal(spawned.x,-50);b.step();assert.equal(steps,1);assert.notEqual(spawned.x,-50);});
test('candidate mutation may pull freshly loaded unit inside old range',()=>{let spawned=null,steps=0;const b=new FirstBattle({random:()=>.5,onEvent:e=>{if(e.type==='spawn'&&e.unit.team==='good'){spawned=e.unit;const old=spawned.step.bind(spawned);spawned.step=()=>{steps++;old();};}}});const remover={step(){b.objects.remove(this);}};b.objects.items.unshift(remover);b.friendlyQueue.enqueue({type:'grunt',rank:0});b.step();assert.ok(spawned);assert.equal(steps,1);});

test('removing an earlier object cannot duplicate a later actor step',()=>{const trace=[],items=[];const a={step(){trace.push('A')}},b={step(){trace.push('B')}},c={step(){trace.push('C');items.splice(items.indexOf(a),1)}};items.push(a,b,c);stepObjectArray(()=>items);assert.deepEqual(trace,['A','B','C']);});
test('new append normally waits until the next captured-count pass',()=>{const trace=[],items=[],b={step(){trace.push('B')}},a={step(){trace.push('A');if(items.length===1)items.push(b)}};items.push(a);stepObjectArray(()=>items);assert.deepEqual(trace,['A']);stepObjectArray(()=>items);assert.deepEqual(trace,['A','A','B']);});
