import test from 'node:test';import assert from 'node:assert/strict';
import {CampaignBattle} from '../site/dist/engine/first-battle.mjs';
import {RANGED_ACTION as R} from '../site/dist/engine/ranged-troop.mjs';
import {createSpecialMotionController,airMotion,siegeMotion} from '../site/dist/special-unit-motion.mjs';
import {drawElementalDragon} from '../site/dist/elemental-feedback.mjs';
function fixture(type){let randomCalls=0;const b=new CampaignBattle({random:()=>{randomCalls++;return .5;}}),u=b.createUnit(type,{rank:1}),c=createSpecialMotionController();u.x=900;u.y=b.elevationAt(u.x);c.attach(b);const step=()=>{b.tick++;u.step();c.observeTick();};return{b,u,c,step,randomCalls:()=>randomCalls};}
for(const kind of ['air','poisonDragon','fireDragon','iceDragon'])test(`${kind} wings advance through mechanically frozen patrol without changing frames or RNG`,()=>{
 const f=fixture(kind),{u,c,step}=f;u.y-=250;u.targetX=1700;u.targetY=u.y;step();step();const first=c.air(u),start=u.x,poses=new Set();
 for(let i=0;i<60;i++){step();const frame=JSON.stringify(u.animation),calls=f.randomCalls();poses.add(c.air(u).wingLift.toFixed(6));assert.equal(JSON.stringify(u.animation),frame);assert.equal(f.randomCalls(),calls);assert.equal(u.animation.frame,15);assert.equal(u.animation.rate,0);}
 assert.ok(u.x-start>100);assert.ok(poses.size>40);assert.notEqual(first.wingLift,c.air(u).wingLift);
});
test('presentation pauses, render reads and disabled actor ticks never advance wings',()=>{const {b,u,c,step}=fixture('air');step();const before={...c.record(u)};for(let i=0;i<100;i++)c.air(u);assert.deepEqual(c.record(u),before);c.observeTick();assert.deepEqual(c.record(u),before);b.tick+=10;c.observeTick({actorsAdvanced:false});assert.deepEqual(c.record(u),before);});
test('falling, dead and <=20 percent air units fold wings while preserving own position',()=>{for(const hp of [0,-2,20]){const u={hp,maxHp:100,x:20,y:100};const before=JSON.stringify(u);assert.deepEqual(airMotion(u,{age:100}),{powered:false,wingLift:-22});assert.equal(JSON.stringify(u),before);}assert.equal(airMotion({hp:21,maxHp:100},{age:4}).powered,true);});
test('wing phase is deterministic by spawn and resets with a new battle',()=>{const a=fixture('air'),b=fixture('air');assert.equal(a.c.air(a.u).wingLift,b.c.air(b.u).wingLift);const another=a.b.createUnit('air',{rank:1});a.c.event({type:'spawn',unit:another});assert.notEqual(a.c.air(another).wingLift,a.c.air(a.u).wingLift);a.c.attach(a.b);assert.equal(a.c.record(a.u).age,0);});
test('trebuchet has one throw, one recovery, and exact actual release origin',()=>{
 const {b,u,c,step}=fixture('trebuchet'),target=b.createUnit('grunt',{team:'good'});target.x=1800;target.y=u.y;target.vx=0;u.rangedTarget=target;u.transition(R.RELEASE_AMMO);const shots=[];u.services.queueProjectile=r=>shots.push(r);const angles=[];let releasePose;
 for(let i=0;i<80;i++){step();const pose=c.siege(u);angles.push(pose.angle);if(shots.length===1&&!releasePose){releasePose=pose;assert.equal(pose.loaded,false);assert.ok(Math.abs(pose.tip.x-(shots[0].x-u.x))<1e-9);assert.ok(Math.abs(pose.tip.y-(shots[0].y-u.y))<1e-9);}}
 assert.equal(shots.length,1);assert.ok(releasePose);let reversals=0,last=0;for(let i=1;i<angles.length;i++){const d=Math.sign(angles[i]-angles[i-1]);if(d&&last&&d!==last)reversals++;if(d)last=d;}assert.equal(reversals,1);
});
test('trebuchet waits at release position for a late target, then uses the real fired edge',()=>{const{b,u,c,step}=fixture('trebuchet'),t=b.createUnit('grunt',{team:'good'});t.x=2100;t.y=u.y;t.vx=0;u.rangedTarget=t;u.transition(R.RELEASE_AMMO);let fired=0;u.services.queueProjectile=()=>fired++;for(let i=0;i<26;i++)step();assert.equal(fired,0);assert.equal(c.siege(u).loaded,true);assert.ok(Math.abs(c.siege(u).tip.y+150)<1e-9);t.x=1800;step();assert.equal(fired,1);assert.ok(c.record(u).firedRemaining<130);assert.ok(Math.abs(c.siege(u).tip.y+150)<1e-9);assert.equal(c.siege(u).loaded,false);});
test('Gorath impact hold only starts on actual landed edge or companion wave event',()=>{const{b,u,c}=fixture('gorath');assert.equal(c.record(u).impactAge,null);u.axeLanded=true;b.tick++;c.observeTick();assert.equal(c.record(u).impactAge,0);b.tick++;c.observeTick();assert.equal(c.record(u).impactAge,1);c.event({type:'companion-signature',unit:u});assert.equal(c.record(u).impactAge,0);b.tick+=30;c.observeTick({actorsAdvanced:false});assert.equal(c.record(u).impactAge,0);});
test('elemental renderer receives visual wing phase and retains body identity at zero health',()=>{const calls=[];const ctx=new Proxy({globalAlpha:.65},{get:(o,k)=>k in o?o[k]:(...a)=>{for(const x of a)if(typeof x==='number')assert.ok(Number.isFinite(x));calls.push([k,...a]);},set:(o,k,v)=>(o[k]=v,true)});const u={type:'dragon_scout_fire',hp:0,maxHp:100,animation:{frame:15}};assert.equal(drawElementalDragon(ctx,u,{wingLift:-22}),true);const folded=JSON.stringify(calls);calls.length=0;drawElementalDragon(ctx,u,{wingLift:14});assert.notEqual(JSON.stringify(calls),folded);assert.equal(ctx.globalAlpha,.65);});
