import test from 'node:test';
import assert from 'node:assert/strict';
import {paintedVisible,interactionVisible} from '../site/dist/viewport-visibility.mjs';
import {touchConflicts} from '../site/dist/viewport-metrics.mjs';
import {Element,child,box,computedStyle,gameFixture,loadViewportLab} from './helpers/viewport-lab-fixture.mjs';
const win={getComputedStyle:computedStyle},visible=node=>interactionVisible(node,win),controls=root=>root.querySelectorAll('button,input,select,a,summary').filter(visible);
function disclosure(parent=new Element(),open=false){const details=child(parent,'details');details.open=open;const summary=child(details,'summary'),content=child(details,'div'),button=child(content,'button');return {parent,details,summary,content,button};}

test('closed disclosure keeps first direct summary and descendants despite stale content rectangles',()=>{const f=disclosure(),span=child(f.summary,'span'),button=child(span,'button');assert.equal(paintedVisible(f.button,win),true);assert.equal(visible(f.button),false);assert.equal(visible(f.summary),true);assert.equal(visible(span),true);assert.equal(visible(button),true);assert.deepEqual(controls(f.parent),[f.summary,button]);});
test('opening and reclosing disclosure restores and removes content immediately',()=>{const f=disclosure();f.details.open=true;assert.equal(visible(f.button),true);f.details.open=false;assert.equal(visible(f.button),false);});
test('closed outer disclosure excludes open inner content and summary',()=>{const outer=disclosure(),inner=disclosure(outer.content,true);assert.equal(visible(inner.summary),false);assert.equal(visible(inner.button),false);outer.details.open=true;assert.equal(visible(inner.summary),true);assert.equal(visible(inner.button),true);});
test('open outer and closed inner preserve inner summary but not inner content',()=>{const outer=disclosure(undefined,true),inner=disclosure(outer.content);assert.equal(visible(inner.summary),true);assert.equal(visible(inner.button),false);});
test('nested disclosure inside exposed summary independently gates its content',()=>{const outer=disclosure(),inner=disclosure(outer.summary);assert.equal(visible(inner.summary),true);assert.equal(visible(inner.button),false);inner.details.open=true;assert.equal(visible(inner.button),true);});
test('only first direct summary is active; hiding it does not promote later summaries',()=>{const f=disclosure(),second=child(f.details,'summary'),nested=child(f.content,'summary');assert.equal(visible(second),false);assert.equal(visible(nested),false);f.details.open=true;assert.equal(visible(second),false);f.summary.hidden=true;assert.equal(visible(f.summary),false);assert.equal(visible(second),false);const button=child(second,'button');assert.equal(visible(button),true);f.details.open=false;assert.equal(visible(button),false);});
test('disclosure without summary exposes no closed contents',()=>{const root=new Element('details'),button=child(root,'button');assert.equal(visible(button),false);root.open=true;assert.equal(visible(button),true);});
for(const mode of ['self property','ancestor property','ancestor attribute'])test('inert exclusion: '+mode,()=>{const parent=new Element(),button=child(parent,'button');if(mode==='self property')button.inert=true;else if(mode==='ancestor property')parent.inert=true;else parent.setAttribute('inert','');assert.equal(paintedVisible(button,win),true);assert.equal(visible(button),false);});
for(const [name,apply] of [['hidden',node=>node.hidden=true],['display',node=>node.style.display='none'],['visibility',node=>node.style.visibility='hidden'],['opacity',node=>node.style.opacity='0']])test('hidden/style ancestor exclusion: '+name,()=>{const parent=new Element(),button=child(parent,'button');apply(parent);assert.equal(visible(button),false);assert.equal(paintedVisible(button,win),false);});
test('missing rectangles exclude controls while disabled controls remain measured',()=>{const button=new Element('button');button.noRects=true;assert.equal(visible(button),false);button.noRects=false;button.disabled=true;button.setAttribute('aria-disabled','true');assert.equal(visible(button),true);});
test('44px threshold and overlap tolerance preserve genuine tiny/overlap negative controls',()=>{const result=touchConflicts([{...box(0,0,44,44),label:'exact'},{...box(42,0,43.49,44),label:'tiny-overlap'},{...box(200,0,43.5,43.5),label:'half-pixel-tolerance'},{...box(243.5,0,44,44),label:'touching'},{...box(286.5,0,44,44),label:'one-pixel-overlap'}]);assert.deepEqual(result.undersized.map(x=>x.label),['tiny-overlap']);assert.deepEqual(result.overlaps.map(x=>[x.a,x.b]),[['exact','tiny-overlap']]);});
test('actual diagnostic filters inert/closed details but reports live summary tiny/overlap errors',async()=>{const game=gameFixture(),modal=child(game.doc,'section',{class:'panel'}),f=disclosure(modal),under=child(modal,'div');under.inert=true;f.summary.rect=box(10,10,44,44);f.button.rect=box(10,10,14,44);child(under,'button',{},box(10,10,12,12));const lab=await loadViewportLab(game);await lab.refresh();assert.equal(lab.get('touchMeasure').textContent,'0 / 0');const tiny=child(modal,'button',{},box(40,10,20,44));tiny.disabled=true;await lab.refresh();assert.equal(lab.get('touchMeasure').textContent,'1 / 1');assert.equal(lab.measurement.dataset.state,'warn');tiny.rect=box(80,10,44,44);f.details.open=true;await lab.refresh();assert.equal(lab.get('touchMeasure').textContent,'1 / 1');});
test('checkbox/radio labels normalize and deduplicate without hiding unlabelled tiny inputs',async()=>{const game=gameFixture(),modal=child(game.doc,'section',{class:'panel'}),label=child(modal,'label',{},box(10,10,100,44));child(label,'input',{type:'checkbox'},box(10,10,14,14));child(label,'input',{type:'radio'},box(30,10,14,14));const lab=await loadViewportLab(game);await lab.refresh();assert.equal(lab.get('touchMeasure').textContent,'0 / 0');child(modal,'input',{type:'checkbox'},box(200,10,14,14));await lab.refresh();assert.equal(lab.get('touchMeasure').textContent,'1 / 0');});
test('modal viewport/ancestor clipping still exclude partial controls and count fully exposed tiny targets',async()=>{const game=gameFixture(),modal=child(game.doc,'section',{class:'panel'}),scroller=child(modal,'div',{},box(0,0,200,100));scroller.style.overflowY='auto';child(scroller,'button',{},box(20,80,100,44));child(modal,'button',{},box(980,150,44,44));child(modal,'button',{},box(1010,150,10,10));const lab=await loadViewportLab(game);await lab.refresh();assert.equal(lab.get('touchMeasure').textContent,'0 / 0');child(scroller,'button',{},box(20,30,20,44));await lab.refresh();assert.equal(lab.get('touchMeasure').textContent,'1 / 0');});
test('nonmodal partial clipping continues to report remaining small visible target',async()=>{const game=gameFixture();child(game.doc,'button',{'data-hud-control':''},box(980,10,44,44));const lab=await loadViewportLab(game);await lab.refresh();assert.equal(lab.get('touchMeasure').textContent,'1 / 0');});
test('inert painted HUD stays in occlusion and all 35 aim samples detect real interception',async()=>{const game=gameFixture(),hud=child(game.doc,'div',{'data-hud-surface':''},box(200,100,700,400));hud.inert=true;const points=[];game.doc.elementFromPoint=(x,y)=>{points.push({x,y});return hud;};const lab=await loadViewportLab(game);await lab.refresh();assert.equal(lab.get('hudMeasure').textContent,'46.7%');assert.equal(lab.get('zoneMeasure').textContent,'100.0%');assert.equal(points.length,35);assert.equal(new Set(points.map(p=>p.x)).size,7);assert.equal(new Set(points.map(p=>p.y)).size,5);assert.match(lab.get('details').textContent,/35 of 35 combat points intercept aim input/);assert.match(lab.get('details').textContent,/persistent HUD enters the clear combat zone/);assert.match(lab.get('details').textContent,/HUD exceeds 16% area budget/);assert.equal(lab.measurement.dataset.state,'warn');game.screen.dataset.heroMode='foot';await lab.refresh();assert.match(lab.get('details').textContent,/HUD exceeds 22% area budget/);});
test('clean live canvas has zero interception; only actual blocked sample points are reported',async()=>{const game=gameFixture(),lab=await loadViewportLab(game);await lab.refresh();assert.match(lab.get('details').textContent,/35 combat points pass input through/);let count=0;game.doc.elementFromPoint=()=>++count===13?game.screen:game.battlefield;await lab.refresh();assert.equal(count,35);assert.match(lab.get('details').textContent,/1 of 35 combat points intercept aim input/);});
