import {readFileSync} from 'node:fs';
import test from 'node:test';import assert from 'node:assert/strict';
import {loadGameUI} from '../tests/helpers/game-ui-harness.mjs';
import {SKILLS} from '../site/dist/engine/progression.mjs';
import {RECRUIT_SKILLS,REGULAR_RECRUIT_IDS} from '../site/dist/engine/recruitment.mjs';
import {skillIcon} from '../site/dist/skill-icons.mjs';
const unlock=ui=>{ui.click('introTesting');ui.click('testGoldLarge');ui.click('testUnlock');ui.click('closeTesting');};
test('unowned companion slot is hidden, appears when owned, stays separate from skills and never triggers pre-battle',async t=>{const ui=await loadGameUI(t,{search:'?mode=test'});assert.equal(ui.visible('companionDock'),false);unlock(ui);assert.equal(ui.visible('companionDock'),true);assert.equal(ui.get('companionAction').disabled,true);ui.click('companionAction');assert.equal(ui.battle.companions.unit,null);assert.equal(ui.battle.profile.skills.length,25);assert.ok(!ui.battle.profile.skills.some(s=>s.id==='gorath'));ui.click('introLoadout');assert.match(ui.get('companionLoadout').textContent,/150 gold to summon/);assert.equal(ui.get('ownedSkillList').querySelectorAll('button').length,25);ui.click('equipCompanion');assert.equal(ui.battle.profile.companionId,null);ui.click('equipCompanion');assert.equal(ui.battle.profile.companionId,'gorath');});
test('live summon charges only once, signature has independent cooldown, recall shows recovery and Space remains separate',async t=>{const ui=await loadGameUI(t,{search:'?mode=test'});unlock(ui);ui.click('start');ui.frames();const gold=ui.battle.profile.gold,bar=ui.battle.hotbar.bar;ui.click('companionAction');assert.equal(ui.battle.profile.gold,gold-150);assert.equal(ui.battle.companions.status().active,true);assert.match(ui.get('companionAction').getAttribute('aria-label'),/Earthshatter/);ui.click('companionAction');assert.equal(ui.get('companionAction').disabled,true);ui.click('companionAction');assert.equal(ui.battle.profile.gold,gold-150);assert.equal(ui.battle.hotbar.bar,bar);assert.equal(ui.battle.input.space,false);ui.click('battlePause');ui.frames();ui.click('companionRecall');assert.equal(ui.battle.companions.status().active,false);assert.match(ui.get('companionActionState').textContent,/60s/);assert.equal(ui.get('companionAction').disabled,true);});
test('companion controls remain inert during pause and menus; active companion cannot be unequipped',async t=>{const ui=await loadGameUI(t,{search:'?mode=test'});unlock(ui);ui.click('start');ui.frames();ui.click('companionAction');const unit=ui.battle.companions.unit;ui.click('battlePause');ui.frames();ui.click('companionAction');assert.equal(ui.battle.companions.unit,unit);assert.equal(unit.signatureCooldown,0);ui.click('pauseSkills');assert.equal(ui.get('equipCompanion').disabled,true);ui.click('equipCompanion');assert.equal(ui.battle.profile.companionId,'gorath');});
test('armory separates regular recruits from companion cards and updates hire funds',async t=>{const ui=await loadGameUI(t,{search:'?mode=test'});ui.click('introTesting');ui.click('testGoldLarge');ui.click('testVictory');ui.frames(105);ui.click('endingShop');ui.get('shopFilters').querySelector('[data-ability-filter="army"]').click();assert.equal(ui.get('shopGrid').querySelectorAll('article').length,12);assert.ok(!ui.document.querySelector('#buy-gorath'));for(const id of REGULAR_RECRUIT_IDS)assert.ok(ui.get('buy-'+id));ui.get('shopFilters').querySelector('[data-ability-filter="companions"]').click();ui.click('inspect-gorath');assert.match(ui.get('shopDetails').textContent,/7,500 gold/);assert.match(ui.get('shopDetails').textContent,/150 gold/);assert.match(ui.get('shopDetails').textContent,/provisional balance/);ui.click('buy-gorath');assert.equal(ui.battle.profile.gold,2500);assert.equal(ui.get('shopBalance').textContent,'2,500 gold');assert.match(ui.get('buy-gorath').textContent,/Manage companion slot/);assert.equal(ui.battle.profile.companionId,'gorath');ui.click('buy-gorath');assert.equal(ui.visible('shopDetailDrawer'),true);assert.ok(ui.get('shopCompanionEquip'));ui.click('shopCompanionEquip');assert.equal(ui.battle.profile.companionId,null);assert.ok(!ui.battle.profile.skills.some(skill=>skill.id==='gorath'));});
test('new recruits have meaningful descriptions/icons and can use a third-page live slot',async t=>{for(const [id,item]of Object.entries(RECRUIT_SKILLS)){assert.ok(item.description);assert.match(skillIcon(id),/<svg/);}const ui=await loadGameUI(t,{search:'?mode=test'});unlock(ui);ui.click('introLoadout');ui.click('owned-fireDragon');assert.match(ui.get('selectedSkillDescription').textContent,/enemy-only burn/);ui.click('closeSkills');ui.click('start');ui.frames();while(!ui.document.querySelector('#quick-fireDragon'))ui.click('nextBar');const gold=ui.battle.profile.gold;ui.click('quick-fireDragon');ui.frames();assert.equal(ui.battle.profile.gold,gold-SKILLS.fireDragon.summon.cost);assert.ok(ui.battle.friendlyQueue.queue.some(t=>t.type==='fireDragon')||ui.battle.goodTeam.some(u=>u.type==='dragon_scout_fire'));});
test('assisted allies showcase starts with a visible friendly Fire Dragon and separate ready companion without changing the ordinary demo',async t=>{const ui=await loadGameUI(t,{search:'?mode=demo&showcase=companions'});const b=ui.battle;assert.equal(b.profile.cheated,true);assert.equal(b.profile.name,'Allies Demo');const flyer=b.goodTeam.find(u=>u.type==='dragon_scout_fire');assert.ok(flyer);assert.equal(flyer.team,'good');assert.equal(flyer.x,580);assert.equal(b.regularArmyCount<=b.friendlyQueue.cap,true);assert.equal(b.profile.companionId,'gorath');assert.equal(b.companions.status().canSummon,true);assert.equal(ui.visible('companionDock'),true);assert.match(ui.get('demoPresetDescription').textContent,/supplied Fire Dragon/);assert.equal(ui.visible('intro'),true);assert.equal(ui.get('companionAction').disabled,true);ui.click('start');ui.click('companionAction');assert.equal(b.companions.status().active,true);ui.click('battlePause');ui.click('demoRestart');assert.notEqual(ui.battle,b);assert.equal(ui.battle.goodTeam.some(u=>u.type==='dragon_scout_fire'),true);assert.equal(ui.battle.companions.unit,null);});

test('shipping companion markup has unique IDs and no merge markers',()=>{const html=readFileSync(new URL('../site/dist/battle.html',import.meta.url),'utf8');assert.doesNotMatch(html,/<<<<<<<|>>>>>>>|=======/);const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length);});


test('companion reuses the vitals seal in landscape and existing utility rail in portrait without duplicating controls',async t=>{
 const beforeW=globalThis.innerWidth,beforeH=globalThis.innerHeight;
 t.after(()=>{if(beforeW===undefined)delete globalThis.innerWidth;else globalThis.innerWidth=beforeW;if(beforeH===undefined)delete globalThis.innerHeight;else globalThis.innerHeight=beforeH;});
 globalThis.innerWidth=915;globalThis.innerHeight=360;
 const ui=await loadGameUI(t,{search:'?mode=demo&showcase=companions'});ui.click('start');
 assert.ok(ui.get('companionDock').parentElement.classList.contains('live-vitals'));
 globalThis.innerWidth=360;globalThis.innerHeight=640;ui.frames();
 assert.ok(ui.get('companionDock').parentElement.classList.contains('live-utility-column'));
 globalThis.innerWidth=915;globalThis.innerHeight=360;ui.frames();
 assert.ok(ui.get('companionDock').parentElement.classList.contains('live-vitals'));
 assert.equal(ui.document.querySelectorAll('#companionAction').length,1);
});
