import test from 'node:test';
import assert from 'node:assert/strict';
import {FirstBattle} from '../site/dist/engine/first-battle.mjs';
import {PlayerProfile,SKILLS,summonSquad,serializeProfile,restoreProfile} from '../site/dist/engine/progression.mjs';
import {CampaignProfiles} from '../site/dist/engine/profile-manager.mjs';
import {REGULAR_RECRUIT_IDS,RECRUIT_SKILLS,COMPANIONS} from '../site/dist/engine/recruitment.mjs';
import {getLevel} from '../site/dist/engine/levels.mjs';
import {collectProjectileTargets} from '../site/dist/engine/projectile-targets.mjs';
import {createStatusEffect,ReactiveElement} from '../site/dist/engine/special-projectiles.mjs';
import {createSupportEffect} from '../site/dist/engine/ranged-troop.mjs';
import {FLAG_ACTION as A,FLAG_STATUS as F} from '../site/dist/engine/flag-troop.mjs';
import {CompanionShockWave} from '../site/dist/engine/companions.mjs';
import {unlockTestSkills,readyTestSkills} from '../site/dist/testing.mjs';
const fresh=()=>{const profile=new PlayerProfile();profile.gold=100000;const battle=new FirstBattle({profile});battle.enemies.roster=['grunt'];battle.enemies.timer=1e9;return battle;};
const summonBoss=b=>{b.profile.recruitCompanion('gorath');assert.equal(b.companions.summon(),true);return b.companions.unit;};

test('every actual campaign fighter maps to a regular recruit or a unique companion; structures are excluded',()=>{const ids=new Set();for(let level=1;level<=30;level++){const data=getLevel(level);for(const id of [...Object.keys(data.fixedCounts),...Object.keys(data.randomCounts)])ids.add(id);}assert.deepEqual([...ids].sort(),[...REGULAR_RECRUIT_IDS,...Object.keys(COMPANIONS)].sort());assert.equal(REGULAR_RECRUIT_IDS.length,12);assert.equal(Object.keys(SKILLS).length,25);for(const id of ['gorath','castle','tower'])assert.equal(SKILLS[id],undefined);});
for(const id of REGULAR_RECRUIT_IDS){
 test(`${id}: acquire, queue, charge once, allied factory/targets/geometry, and portable ownership`,()=>{const b=fresh(),p=b.profile;assert.equal(p.purchase(id),true);const skill=p.skills.find(s=>s.id===id),config=SKILLS[id].summon;skill.cooldown=0;skill.autocast=false;const gold=p.gold,reserve=b.friendlyQueue.population;assert.equal(summonSquad(skill,p,b.friendlyQueue,b.stats),true);assert.equal(summonSquad(skill,p,b.friendlyQueue,b.stats),false);assert.equal(p.gold,gold-config.cost);assert.equal(b.friendlyQueue.population,reserve-config.amount*config.population);b.step();const unit=b.goodTeam.find(u=>u!==b.hero);assert.ok(unit);assert.equal(unit.team,'good');assert.ok(unit.hitbox);assert.equal(unit.recruited,true);assert.ok(!unit.enemies().includes(b.hero));assert.equal(b.badTeam.includes(unit),false);assert.equal(restoreProfile(serializeProfile(p)).owned.has(id),true);});
 test(`${id}: reserve/queue/price failures do not consume gold or cooldown`,()=>{const b=fresh(),s=b.profile.addSkill(id);s.cooldown=0;b.friendlyQueue.population=0;const gold=b.profile.gold;assert.equal(summonSquad(s,b.profile,b.friendlyQueue,b.stats),false);assert.equal(b.profile.gold,gold);assert.equal(s.cooldown,0);b.friendlyQueue.population=100;b.friendlyQueue.queue=Array(15).fill({});assert.equal(summonSquad(s,b.profile,b.friendlyQueue,b.stats),false);b.friendlyQueue.queue=[];b.profile.gold=0;assert.equal(summonSquad(s,b.profile,b.friendlyQueue,b.stats),false);});
}
for(const id of ['air','poisonDragon','fireDragon','iceDragon']){
 test(`${id}: projectiles target hostiles, retain allied skill ownership, and air registration cleans up`,()=>{const b=fresh(),s=b.profile.addSkill(id),u=b.createUnit(id,{team:'good',rank:1,skill:s}),enemy=b.createUnit('grunt'),ally=b.createUnit('grunt',{team:'good'});u.x=650;u.y=b.elevationAt(650)-200;enemy.x=750;enemy.y=b.elevationAt(750);ally.x=740;ally.y=enemy.y;b.updateGeometry(enemy);const request=u.shootAtTarget(enemy),p=b.projectiles.at(-1);assert.equal(request.team,'good');assert.equal(p.team,'good');assert.equal(p.skill,s);p.x=700;p.y=b.elevationAt(700);p.vx=10;const targets=collectProjectileTargets(p,b);assert.ok(targets.includes(enemy));assert.ok(!targets.includes(ally));assert.ok(!targets.includes(b.hero));assert.equal(u.holdingFlag(),false);u.destroy();assert.ok(!b.airUnits.includes(u));assert.ok(!b.goodTeam.includes(u));});
}
for(const id of ['fireDragon','iceDragon'])test(`${id}: lingering elemental field never damages allied units`,()=>{const b=fresh(),u=b.createUnit(id,{team:'good',rank:1}),e=b.createUnit('grunt'),friend=b.createUnit('grunt',{team:'good'});e.x=friend.x=600;e.y=friend.y=b.elevationAt(600);b.updateGeometry(e);b.updateGeometry(friend);u.x=550;u.y=e.y-120;u.shootAtTarget(e);const p=b.projectiles.at(-1);p.x=e.x;p.y=e.y-15;p.impact(e);const reactive=b.reactiveElements.at(-1);assert.equal(reactive.damageTeam,'good');assert.ok(!reactive.targets.includes(friend));const hp=friend.hp;reactive.damageTarget(friend);friend.effects.step();assert.equal(friend.hp,hp);assert.ok(e.effects.effects.length>0);});
for(const id of ['fireDemon','iceDemon'])test(`${id}: allied flag acquisition, capture and death-drop use the opposing flag`,()=>{const b=fresh(),u=b.createUnit(id,{team:'good',rank:1});assert.equal(u.friendFlag,b.ownFlag);assert.equal(u.enemyFlag,b.enemyFlag);u.x=b.enemyFlag.x;u.y=b.elevationAt(u.x);u.transition(A.PICKUP_ENEMY);assert.equal(b.enemyFlag.holder,u);u.destroy();assert.equal(b.enemyFlag.status,F.GROUNDED);assert.equal(b.enemyFlag.holder,null);assert.ok(!b.goodTeam.includes(u));});
test('all new living recruits accept allied healing and poison/ice statuses without changing allegiance',()=>{for(const id of Object.keys(RECRUIT_SKILLS)){const b=fresh(),u=b.createUnit(id,{team:'good',rank:1});u.hp-=10;u.effects.add(createSupportEffect({kind:'heal',target:u,amount:10,duration:10,interval:1},{random:()=>0}));u.effects.step();assert.equal(u.hp,u.maxHp);u.effects.add(createStatusEffect({kind:'ice',target:u,duration:10,interval:1,slowFactor:.5}));u.effects.step();assert.equal(u.speedFactor,.5);assert.equal(u.team,'good');}});

test('boss cannot be purchased as a squad or spawned through regular ally path',()=>{const b=fresh();assert.equal(b.profile.purchase('gorath'),false);assert.throws(()=>b.createUnit('gorath',{team:'good'}),/companion/);});
test('companion hire and summon costs are separate, exact funds supported, no reserve or ordinary army slots',()=>{const b=fresh(),p=b.profile;p.gold=COMPANIONS.gorath.price;assert.equal(p.recruitCompanion('gorath'),true);assert.equal(p.gold,0);assert.equal(p.recruitCompanion('gorath'),false);assert.equal(b.companions.summon(),false);p.gold=COMPANIONS.gorath.summonCost;const reserve=b.friendlyQueue.population;for(let i=0;i<10;i++)b.createUnit('grunt',{team:'good'});assert.equal(b.companions.summon(),true);assert.equal(p.gold,0);assert.equal(b.friendlyQueue.population,reserve);assert.equal(b.regularArmyCount,10);assert.equal(b.companions.summon(),false);assert.equal(b.goodTeam.length,12);});
test('companion does not consume the tenth regular reinforcement slot',()=>{const b=fresh();summonBoss(b);for(let i=0;i<9;i++)b.createUnit('grunt',{team:'good'});b.friendlyQueue.enqueue({type:'grunt',cost:1,rank:1});b.step();assert.equal(b.regularArmyCount,10);assert.equal(b.goodTeam.length,12);});
test('persistent companion remains longer than45seconds and does not capture flags',()=>{const b=fresh(),u=summonBoss(b);u.stomp=()=>{};for(let i=0;i<50*33;i++)b.step();assert.equal(b.companions.unit,u);assert.equal(b.companions.status().active,true);assert.equal(u.holdingFlag(),false);assert.equal(b.enemyFlag.holder,null);});
test('companion walks toward enemies and auto-stomps only opposing ground troops',()=>{const b=fresh(),u=summonBoss(b),enemy=b.createUnit('grunt'),friend=b.createUnit('grunt',{team:'good'});enemy.x=1000;enemy.y=b.elevationAt(1000);const x=u.x;u.step();assert.ok(u.x>x);assert.equal(u.facing,-1);enemy.x=friend.x=u.x+65;enemy.y=friend.y=u.y;u.stomp();const hp=friend.hp;friend.effects.step();enemy.effects.step();assert.equal(friend.hp,hp);assert.ok(enemy.hp<enemy.maxHp);});
test('Earthshatter has bounded range, one hit per enemy, no friendly/air hits, and normal spell cleanup',()=>{const b=fresh(),u=summonBoss(b),enemy=b.createUnit('grunt'),ally=b.createUnit('grunt',{team:'good'}),air=b.createUnit('air');enemy.x=ally.x=air.x=u.x+100;enemy.y=ally.y=air.y=b.elevationAt(enemy.x);const wave=new CompanionShockWave({source:u,world:b,damage:30});b.addSpell(wave);for(let i=0;i<40;i++)wave.step();assert.equal(wave.seen.has(enemy),true);assert.equal(wave.seen.has(ally),false);assert.equal(wave.seen.has(air),false);assert.equal(enemy.effects.effects.filter(e=>e.kind==='impact').length,1);assert.equal(ally.effects.effects.length,0);assert.equal(wave.dead,true);assert.ok(!b.spells.includes(wave));});
test('signature input is edge-safe, winds up, cools down, and does not auto-repeat',()=>{const b=fresh(),u=summonBoss(b);assert.equal(b.companions.useSignature(),true);assert.equal(b.companions.useSignature(),false);for(let i=0;i<18;i++)u.step();assert.equal(b.spells.filter(s=>s.kind==='gorath_shock_wave').length,1);for(let i=18;i<495;i++)u.step();assert.equal(u.signatureCooldown,0);assert.equal(b.spells.length,1);assert.equal(b.companions.useSignature(),true);});
test('recall is idempotent,60second recovery pauses with battle and permits resummon exactly at readiness',()=>{const b=fresh(),u=summonBoss(b);assert.equal(b.companions.recall(),true);assert.equal(b.companions.recall(),false);assert.equal(u.destroyed,true);assert.ok(!b.goodTeam.includes(u));assert.equal(b.companions.status().cooldownSeconds,60);b.paused=true;for(let i=0;i<100;i++)b.step();assert.equal(b.companions.status().cooldownSeconds,60);b.paused=false;for(let i=0;i<1980;i++)b.companions.step();assert.equal(b.companions.status().canSummon,true);assert.equal(b.companions.summon(),true);});
test('defeat releases engagements and starts90second recovery without charging again',()=>{const b=fresh(),u=summonBoss(b),gold=b.profile.gold;u.takeDamage(1e9);u.step();b.companions.step();assert.equal(b.companions.unit,null);assert.equal(b.companions.status().cooldownSeconds,90);assert.equal(b.companions.status().recoveryReason,'defeated');assert.equal(b.profile.gold,gold);assert.ok(!b.goodTeam.includes(u));});
test('battle outcome disposes companion and blocks summon, recall, signature and recovery ticking',()=>{const b=fresh(),u=summonBoss(b);b.finishOutcome('defeat');assert.equal(u.destroyed,true);assert.equal(b.companions.unit,null);assert.equal(b.companions.summon(),false);assert.equal(b.companions.useSignature(),false);assert.equal(b.companions.recall(),false);});
test('companion supports priest healing, ice slow and knockdown recovery',()=>{const b=fresh(),u=summonBoss(b);u.hp-=100;u.effects.add(createSupportEffect({kind:'heal',target:u,amount:40,duration:10,interval:1},{random:()=>0}));u.step();assert.equal(u.hp,u.maxHp-60);u.effects.add(createStatusEffect({kind:'ice',target:u,duration:90,interval:20,slowFactor:.5}));u.step();assert.equal(u.speedFactor,.5);u.transition('knock_back');assert.equal(b.companions.useSignature(),false);for(let i=0;i<33;i++)u.step();assert.equal(u.standing,true);assert.equal(b.companions.useSignature(),true);});
test('schema2 stores only owned/equipped companion; oldschema1 migrates to none',()=>{const b=fresh();summonBoss(b);const value=JSON.parse(serializeProfile(b.profile));assert.equal(value.schema,'bowmaster-reconstruction-2');assert.deepEqual(value.companions,{owned:['gorath'],selected:'gorath'});assert.deepEqual(restoreProfile(JSON.stringify(value)).companionOwned,new Set(['gorath']));const legacy={...value,schema:'bowmaster-reconstruction-1'};delete legacy.companions;const old=restoreProfile(JSON.stringify(legacy));assert.equal(old.companionId,null);assert.equal(old.companionOwned.size,0);assert.equal(CampaignProfiles.fromBundle(JSON.stringify(legacy)).active.companionId,null);assert.equal(CampaignProfiles.fromBundle(JSON.stringify(value)).active.companionId,'gorath');});
test('strict companion persistence rejects unknown, duplicate, unowned selection and unsafe scalar values transactionally',()=>{const b=fresh();summonBoss(b);const text=serializeProfile(b.profile);for(const companions of [{owned:['unknown'],selected:null},{owned:['gorath','gorath'],selected:'gorath'},{owned:[],selected:'gorath'},{owned:['gorath'],selected:'gorath',recoveryTicks:0},{owned:[{}],selected:null}]){const value=JSON.parse(text);value.companions=companions;assert.throws(()=>restoreProfile(JSON.stringify(value)));}b.profile.companionOwned=new Set([{toJSON:()=> 'gorath'}]);assert.throws(()=>serializeProfile(b.profile));});
test('assist unlock/readiness includes all normal recruits and separate companion without charging or claiming earned progression',()=>{const b=new FirstBattle({testing:true});unlockTestSkills(b);assert.equal(b.profile.skills.length,25);assert.equal(b.profile.companionId,'gorath');assert.equal(b.profile.cheated,true);b.companions.recoveryTicks=100;readyTestSkills(b);assert.equal(b.companions.recoveryTicks,0);assert.equal(b.profile.gold,0);});
